// This file is auto-generated, don't edit it. Thanks.
package client

import (
	"github.com/alibabacloud-go/tea/dara"
)

type iDescribeSoarRecordsResponseBody interface {
	dara.Model
	String() string
	GoString() string
	SetPage(v *DescribeSoarRecordsResponseBodyPage) *DescribeSoarRecordsResponseBody
	GetPage() *DescribeSoarRecordsResponseBodyPage
	SetRequestId(v string) *DescribeSoarRecordsResponseBody
	GetRequestId() *string
	SetSoarExecuteRecords(v []*DescribeSoarRecordsResponseBodySoarExecuteRecords) *DescribeSoarRecordsResponseBody
	GetSoarExecuteRecords() []*DescribeSoarRecordsResponseBodySoarExecuteRecords
}

type DescribeSoarRecordsResponseBody struct {
	// Information displayed on the page.
	//
	// This parameter is required.
	Page *DescribeSoarRecordsResponseBodyPage `json:"Page,omitempty" xml:"Page,omitempty" type:"Struct"`
	// The ID of the current request, generated by Alibaba Cloud as a unique identifier for the request, which can be used for troubleshooting and problem localization.
	//
	// example:
	//
	// 601C2DAC-6A67-5237-BEE8-5BF1CEE96296
	RequestId *string `json:"RequestId,omitempty" xml:"RequestId,omitempty"`
	// Execution record result set.
	SoarExecuteRecords []*DescribeSoarRecordsResponseBodySoarExecuteRecords `json:"SoarExecuteRecords,omitempty" xml:"SoarExecuteRecords,omitempty" type:"Repeated"`
}

func (s DescribeSoarRecordsResponseBody) String() string {
	return dara.Prettify(s)
}

func (s DescribeSoarRecordsResponseBody) GoString() string {
	return s.String()
}

func (s *DescribeSoarRecordsResponseBody) GetPage() *DescribeSoarRecordsResponseBodyPage {
	return s.Page
}

func (s *DescribeSoarRecordsResponseBody) GetRequestId() *string {
	return s.RequestId
}

func (s *DescribeSoarRecordsResponseBody) GetSoarExecuteRecords() []*DescribeSoarRecordsResponseBodySoarExecuteRecords {
	return s.SoarExecuteRecords
}

func (s *DescribeSoarRecordsResponseBody) SetPage(v *DescribeSoarRecordsResponseBodyPage) *DescribeSoarRecordsResponseBody {
	s.Page = v
	return s
}

func (s *DescribeSoarRecordsResponseBody) SetRequestId(v string) *DescribeSoarRecordsResponseBody {
	s.RequestId = &v
	return s
}

func (s *DescribeSoarRecordsResponseBody) SetSoarExecuteRecords(v []*DescribeSoarRecordsResponseBodySoarExecuteRecords) *DescribeSoarRecordsResponseBody {
	s.SoarExecuteRecords = v
	return s
}

func (s *DescribeSoarRecordsResponseBody) Validate() error {
	if s.Page != nil {
		if err := s.Page.Validate(); err != nil {
			return err
		}
	}
	if s.SoarExecuteRecords != nil {
		for _, item := range s.SoarExecuteRecords {
			if item != nil {
				if err := item.Validate(); err != nil {
					return err
				}
			}
		}
	}
	return nil
}

type DescribeSoarRecordsResponseBodyPage struct {
	// The current page number in paginated queries.
	//
	// example:
	//
	// 1
	PageNumber *int32 `json:"PageNumber,omitempty" xml:"PageNumber,omitempty"`
	// The number of items per page in paginated queries.
	//
	// example:
	//
	// 10
	PageSize *int32 `json:"PageSize,omitempty" xml:"PageSize,omitempty"`
	// The total number of queried items.
	//
	// example:
	//
	// 22
	TotalCount *int32 `json:"TotalCount,omitempty" xml:"TotalCount,omitempty"`
}

func (s DescribeSoarRecordsResponseBodyPage) String() string {
	return dara.Prettify(s)
}

func (s DescribeSoarRecordsResponseBodyPage) GoString() string {
	return s.String()
}

func (s *DescribeSoarRecordsResponseBodyPage) GetPageNumber() *int32 {
	return s.PageNumber
}

func (s *DescribeSoarRecordsResponseBodyPage) GetPageSize() *int32 {
	return s.PageSize
}

func (s *DescribeSoarRecordsResponseBodyPage) GetTotalCount() *int32 {
	return s.TotalCount
}

func (s *DescribeSoarRecordsResponseBodyPage) SetPageNumber(v int32) *DescribeSoarRecordsResponseBodyPage {
	s.PageNumber = &v
	return s
}

func (s *DescribeSoarRecordsResponseBodyPage) SetPageSize(v int32) *DescribeSoarRecordsResponseBodyPage {
	s.PageSize = &v
	return s
}

func (s *DescribeSoarRecordsResponseBodyPage) SetTotalCount(v int32) *DescribeSoarRecordsResponseBodyPage {
	s.TotalCount = &v
	return s
}

func (s *DescribeSoarRecordsResponseBodyPage) Validate() error {
	return dara.Validate(s)
}

type DescribeSoarRecordsResponseBodySoarExecuteRecords struct {
	// The end time of the component execution, in 13-digit timestamp format.
	//
	// example:
	//
	// 1686294686000
	EndTime *int64 `json:"EndTime,omitempty" xml:"EndTime,omitempty"`
	// The error message of the playbook task. This field is empty when the task succeeds.
	//
	// example:
	//
	// stime not match
	ErrorMsg   *string                                                        `json:"ErrorMsg,omitempty" xml:"ErrorMsg,omitempty"`
	OutputList []*DescribeSoarRecordsResponseBodySoarExecuteRecordsOutputList `json:"OutputList,omitempty" xml:"OutputList,omitempty" type:"Repeated"`
	// The request parameters of the playbook task.
	//
	// example:
	//
	// {
	//
	//     "input1": "xx.xx.xx.xx",
	//
	//     "input2": "7d"
	//
	// }
	RawEventReq *string `json:"RawEventReq,omitempty" xml:"RawEventReq,omitempty"`
	// The request ID of the playbook task, a unique ID for each task run.
	//
	// example:
	//
	// ba1ec480-aa90-4bb6-a1a7-9e311ae79321
	RequestUuid *string `json:"RequestUuid,omitempty" xml:"RequestUuid,omitempty"`
	// The start time of the task execution, in 13-digit timestamp format.
	//
	// example:
	//
	// 1675823338433
	StartTime *int64 `json:"StartTime,omitempty" xml:"StartTime,omitempty"`
	// The status of the playbook task. Values:
	//
	// - **success**: Indicates successful execution.
	//
	// - **fail**: Indicates failed execution.
	//
	// - **running**: Indicates the task is running
	//
	// example:
	//
	// success
	Status *string `json:"Status,omitempty" xml:"Status,omitempty"`
	// The name of the playbook task, which is the same as the playbook\\"s UUID.
	//
	// example:
	//
	// 82848ebc-eaff-4791-acd4-xxxxx
	TaskName *string `json:"TaskName,omitempty" xml:"TaskName,omitempty"`
	// The MD5 value of the playbook configuration.
	//
	// example:
	//
	// dea65a3db87fb9bd84bbxxxxx
	TaskflowMd5 *string `json:"TaskflowMd5,omitempty" xml:"TaskflowMd5,omitempty"`
	// The type of the playbook task. Values:
	//
	// - **debug**: Indicates a debugging task.
	//
	// - **manual**: Indicates a manual task.
	//
	// - **siem**: Indicates a task triggered by an event or alert.
	//
	// example:
	//
	// debug
	TriggerType *string `json:"TriggerType,omitempty" xml:"TriggerType,omitempty"`
	// The Alibaba Cloud account ID that executes the playbook task.
	//
	// example:
	//
	// 127xxxx4392
	TriggerUser *string `json:"TriggerUser,omitempty" xml:"TriggerUser,omitempty"`
}

func (s DescribeSoarRecordsResponseBodySoarExecuteRecords) String() string {
	return dara.Prettify(s)
}

func (s DescribeSoarRecordsResponseBodySoarExecuteRecords) GoString() string {
	return s.String()
}

func (s *DescribeSoarRecordsResponseBodySoarExecuteRecords) GetEndTime() *int64 {
	return s.EndTime
}

func (s *DescribeSoarRecordsResponseBodySoarExecuteRecords) GetErrorMsg() *string {
	return s.ErrorMsg
}

func (s *DescribeSoarRecordsResponseBodySoarExecuteRecords) GetOutputList() []*DescribeSoarRecordsResponseBodySoarExecuteRecordsOutputList {
	return s.OutputList
}

func (s *DescribeSoarRecordsResponseBodySoarExecuteRecords) GetRawEventReq() *string {
	return s.RawEventReq
}

func (s *DescribeSoarRecordsResponseBodySoarExecuteRecords) GetRequestUuid() *string {
	return s.RequestUuid
}

func (s *DescribeSoarRecordsResponseBodySoarExecuteRecords) GetStartTime() *int64 {
	return s.StartTime
}

func (s *DescribeSoarRecordsResponseBodySoarExecuteRecords) GetStatus() *string {
	return s.Status
}

func (s *DescribeSoarRecordsResponseBodySoarExecuteRecords) GetTaskName() *string {
	return s.TaskName
}

func (s *DescribeSoarRecordsResponseBodySoarExecuteRecords) GetTaskflowMd5() *string {
	return s.TaskflowMd5
}

func (s *DescribeSoarRecordsResponseBodySoarExecuteRecords) GetTriggerType() *string {
	return s.TriggerType
}

func (s *DescribeSoarRecordsResponseBodySoarExecuteRecords) GetTriggerUser() *string {
	return s.TriggerUser
}

func (s *DescribeSoarRecordsResponseBodySoarExecuteRecords) SetEndTime(v int64) *DescribeSoarRecordsResponseBodySoarExecuteRecords {
	s.EndTime = &v
	return s
}

func (s *DescribeSoarRecordsResponseBodySoarExecuteRecords) SetErrorMsg(v string) *DescribeSoarRecordsResponseBodySoarExecuteRecords {
	s.ErrorMsg = &v
	return s
}

func (s *DescribeSoarRecordsResponseBodySoarExecuteRecords) SetOutputList(v []*DescribeSoarRecordsResponseBodySoarExecuteRecordsOutputList) *DescribeSoarRecordsResponseBodySoarExecuteRecords {
	s.OutputList = v
	return s
}

func (s *DescribeSoarRecordsResponseBodySoarExecuteRecords) SetRawEventReq(v string) *DescribeSoarRecordsResponseBodySoarExecuteRecords {
	s.RawEventReq = &v
	return s
}

func (s *DescribeSoarRecordsResponseBodySoarExecuteRecords) SetRequestUuid(v string) *DescribeSoarRecordsResponseBodySoarExecuteRecords {
	s.RequestUuid = &v
	return s
}

func (s *DescribeSoarRecordsResponseBodySoarExecuteRecords) SetStartTime(v int64) *DescribeSoarRecordsResponseBodySoarExecuteRecords {
	s.StartTime = &v
	return s
}

func (s *DescribeSoarRecordsResponseBodySoarExecuteRecords) SetStatus(v string) *DescribeSoarRecordsResponseBodySoarExecuteRecords {
	s.Status = &v
	return s
}

func (s *DescribeSoarRecordsResponseBodySoarExecuteRecords) SetTaskName(v string) *DescribeSoarRecordsResponseBodySoarExecuteRecords {
	s.TaskName = &v
	return s
}

func (s *DescribeSoarRecordsResponseBodySoarExecuteRecords) SetTaskflowMd5(v string) *DescribeSoarRecordsResponseBodySoarExecuteRecords {
	s.TaskflowMd5 = &v
	return s
}

func (s *DescribeSoarRecordsResponseBodySoarExecuteRecords) SetTriggerType(v string) *DescribeSoarRecordsResponseBodySoarExecuteRecords {
	s.TriggerType = &v
	return s
}

func (s *DescribeSoarRecordsResponseBodySoarExecuteRecords) SetTriggerUser(v string) *DescribeSoarRecordsResponseBodySoarExecuteRecords {
	s.TriggerUser = &v
	return s
}

func (s *DescribeSoarRecordsResponseBodySoarExecuteRecords) Validate() error {
	if s.OutputList != nil {
		for _, item := range s.OutputList {
			if item != nil {
				if err := item.Validate(); err != nil {
					return err
				}
			}
		}
	}
	return nil
}

type DescribeSoarRecordsResponseBodySoarExecuteRecordsOutputList struct {
	ActionUuid *string `json:"ActionUuid,omitempty" xml:"ActionUuid,omitempty"`
	Content    *string `json:"Content,omitempty" xml:"Content,omitempty"`
	NodeName   *string `json:"NodeName,omitempty" xml:"NodeName,omitempty"`
}

func (s DescribeSoarRecordsResponseBodySoarExecuteRecordsOutputList) String() string {
	return dara.Prettify(s)
}

func (s DescribeSoarRecordsResponseBodySoarExecuteRecordsOutputList) GoString() string {
	return s.String()
}

func (s *DescribeSoarRecordsResponseBodySoarExecuteRecordsOutputList) GetActionUuid() *string {
	return s.ActionUuid
}

func (s *DescribeSoarRecordsResponseBodySoarExecuteRecordsOutputList) GetContent() *string {
	return s.Content
}

func (s *DescribeSoarRecordsResponseBodySoarExecuteRecordsOutputList) GetNodeName() *string {
	return s.NodeName
}

func (s *DescribeSoarRecordsResponseBodySoarExecuteRecordsOutputList) SetActionUuid(v string) *DescribeSoarRecordsResponseBodySoarExecuteRecordsOutputList {
	s.ActionUuid = &v
	return s
}

func (s *DescribeSoarRecordsResponseBodySoarExecuteRecordsOutputList) SetContent(v string) *DescribeSoarRecordsResponseBodySoarExecuteRecordsOutputList {
	s.Content = &v
	return s
}

func (s *DescribeSoarRecordsResponseBodySoarExecuteRecordsOutputList) SetNodeName(v string) *DescribeSoarRecordsResponseBodySoarExecuteRecordsOutputList {
	s.NodeName = &v
	return s
}

func (s *DescribeSoarRecordsResponseBodySoarExecuteRecordsOutputList) Validate() error {
	return dara.Validate(s)
}
