// This file is auto-generated, don't edit it. Thanks.
package client

import (
	"github.com/alibabacloud-go/tea/dara"
)

type iDescribeProcessTaskCountResponseBody interface {
	dara.Model
	String() string
	GoString() string
	SetData(v []*DescribeProcessTaskCountResponseBodyData) *DescribeProcessTaskCountResponseBody
	GetData() []*DescribeProcessTaskCountResponseBodyData
	SetRequestId(v string) *DescribeProcessTaskCountResponseBody
	GetRequestId() *string
}

type DescribeProcessTaskCountResponseBody struct {
	// Transmitted data.
	Data []*DescribeProcessTaskCountResponseBodyData `json:"Data,omitempty" xml:"Data,omitempty" type:"Repeated"`
	// The ID of this call request, which is a unique identifier generated by Alibaba Cloud for this request, used for troubleshooting and problem localization.
	//
	// example:
	//
	// e866cce0-****-41de-817e-****8d5e2650
	RequestId *string `json:"RequestId,omitempty" xml:"RequestId,omitempty"`
}

func (s DescribeProcessTaskCountResponseBody) String() string {
	return dara.Prettify(s)
}

func (s DescribeProcessTaskCountResponseBody) GoString() string {
	return s.String()
}

func (s *DescribeProcessTaskCountResponseBody) GetData() []*DescribeProcessTaskCountResponseBodyData {
	return s.Data
}

func (s *DescribeProcessTaskCountResponseBody) GetRequestId() *string {
	return s.RequestId
}

func (s *DescribeProcessTaskCountResponseBody) SetData(v []*DescribeProcessTaskCountResponseBodyData) *DescribeProcessTaskCountResponseBody {
	s.Data = v
	return s
}

func (s *DescribeProcessTaskCountResponseBody) SetRequestId(v string) *DescribeProcessTaskCountResponseBody {
	s.RequestId = &v
	return s
}

func (s *DescribeProcessTaskCountResponseBody) Validate() error {
	if s.Data != nil {
		for _, item := range s.Data {
			if item != nil {
				if err := item.Validate(); err != nil {
					return err
				}
			}
		}
	}
	return nil
}

type DescribeProcessTaskCountResponseBodyData struct {
	// Count.
	//
	// example:
	//
	// 67
	Count *int64 `json:"Count,omitempty" xml:"Count,omitempty"`
	// Entity UUID.
	//
	// example:
	//
	// a680c9ae-****-4c39-****-0302****fc8e
	EntityUuid *string `json:"EntityUuid,omitempty" xml:"EntityUuid,omitempty"`
}

func (s DescribeProcessTaskCountResponseBodyData) String() string {
	return dara.Prettify(s)
}

func (s DescribeProcessTaskCountResponseBodyData) GoString() string {
	return s.String()
}

func (s *DescribeProcessTaskCountResponseBodyData) GetCount() *int64 {
	return s.Count
}

func (s *DescribeProcessTaskCountResponseBodyData) GetEntityUuid() *string {
	return s.EntityUuid
}

func (s *DescribeProcessTaskCountResponseBodyData) SetCount(v int64) *DescribeProcessTaskCountResponseBodyData {
	s.Count = &v
	return s
}

func (s *DescribeProcessTaskCountResponseBodyData) SetEntityUuid(v string) *DescribeProcessTaskCountResponseBodyData {
	s.EntityUuid = &v
	return s
}

func (s *DescribeProcessTaskCountResponseBodyData) Validate() error {
	return dara.Validate(s)
}
