// This file is auto-generated, don't edit it. Thanks.
package client

import (
	"github.com/alibabacloud-go/tea/dara"
)

type iDescribeDeviceInfoRequest interface {
	dara.Model
	String() string
	GoString() string
	SetBizType(v string) *DescribeDeviceInfoRequest
	GetBizType() *string
	SetCurrentPage(v int32) *DescribeDeviceInfoRequest
	GetCurrentPage() *int32
	SetDeviceId(v string) *DescribeDeviceInfoRequest
	GetDeviceId() *string
	SetExpiredEndDay(v string) *DescribeDeviceInfoRequest
	GetExpiredEndDay() *string
	SetExpiredStartDay(v string) *DescribeDeviceInfoRequest
	GetExpiredStartDay() *string
	SetPageSize(v int32) *DescribeDeviceInfoRequest
	GetPageSize() *int32
	SetUserDeviceId(v string) *DescribeDeviceInfoRequest
	GetUserDeviceId() *string
}

type DescribeDeviceInfoRequest struct {
	// The business type. Maximum of 64 characters.
	//
	// example:
	//
	// FACE_TEST
	BizType *string `json:"BizType,omitempty" xml:"BizType,omitempty"`
	// The current page number.
	//
	// example:
	//
	// 1
	CurrentPage *int32 `json:"CurrentPage,omitempty" xml:"CurrentPage,omitempty"`
	// The unique ID generated by the China Real Identity Authentication server for the device of the integrating party. This ID is generated only after the device is successfully activated and can be obtained by calling the getLicenseExtraInfo function in the offline facial recognition SDK.
	//
	// example:
	//
	// wd.6ziUffspAeW5FVYbaqmexR-1qwNjM
	DeviceId *string `json:"DeviceId,omitempty" xml:"DeviceId,omitempty"`
	// The end time of the query, which queries the authorizations that expire between ExpiredStartDay and ExpiredEndDay.
	//
	// example:
	//
	// 20200330
	ExpiredEndDay *string `json:"ExpiredEndDay,omitempty" xml:"ExpiredEndDay,omitempty"`
	// The start time of the query, which queries the authorizations that expire between ExpiredStartDay and ExpiredEndDay.
	//
	// example:
	//
	// 20190401
	ExpiredStartDay *string `json:"ExpiredStartDay,omitempty" xml:"ExpiredStartDay,omitempty"`
	// The number of entries per page.
	//
	// example:
	//
	// 20
	PageSize *int32 `json:"PageSize,omitempty" xml:"PageSize,omitempty"`
	// Maximum of 64 characters. Custom-defined by the integrating party to identify a specific device.
	//
	// example:
	//
	// 3iJ1AY$oHcu7mC69
	UserDeviceId *string `json:"UserDeviceId,omitempty" xml:"UserDeviceId,omitempty"`
}

func (s DescribeDeviceInfoRequest) String() string {
	return dara.Prettify(s)
}

func (s DescribeDeviceInfoRequest) GoString() string {
	return s.String()
}

func (s *DescribeDeviceInfoRequest) GetBizType() *string {
	return s.BizType
}

func (s *DescribeDeviceInfoRequest) GetCurrentPage() *int32 {
	return s.CurrentPage
}

func (s *DescribeDeviceInfoRequest) GetDeviceId() *string {
	return s.DeviceId
}

func (s *DescribeDeviceInfoRequest) GetExpiredEndDay() *string {
	return s.ExpiredEndDay
}

func (s *DescribeDeviceInfoRequest) GetExpiredStartDay() *string {
	return s.ExpiredStartDay
}

func (s *DescribeDeviceInfoRequest) GetPageSize() *int32 {
	return s.PageSize
}

func (s *DescribeDeviceInfoRequest) GetUserDeviceId() *string {
	return s.UserDeviceId
}

func (s *DescribeDeviceInfoRequest) SetBizType(v string) *DescribeDeviceInfoRequest {
	s.BizType = &v
	return s
}

func (s *DescribeDeviceInfoRequest) SetCurrentPage(v int32) *DescribeDeviceInfoRequest {
	s.CurrentPage = &v
	return s
}

func (s *DescribeDeviceInfoRequest) SetDeviceId(v string) *DescribeDeviceInfoRequest {
	s.DeviceId = &v
	return s
}

func (s *DescribeDeviceInfoRequest) SetExpiredEndDay(v string) *DescribeDeviceInfoRequest {
	s.ExpiredEndDay = &v
	return s
}

func (s *DescribeDeviceInfoRequest) SetExpiredStartDay(v string) *DescribeDeviceInfoRequest {
	s.ExpiredStartDay = &v
	return s
}

func (s *DescribeDeviceInfoRequest) SetPageSize(v int32) *DescribeDeviceInfoRequest {
	s.PageSize = &v
	return s
}

func (s *DescribeDeviceInfoRequest) SetUserDeviceId(v string) *DescribeDeviceInfoRequest {
	s.UserDeviceId = &v
	return s
}

func (s *DescribeDeviceInfoRequest) Validate() error {
	return dara.Validate(s)
}
