// This file is auto-generated, don't edit it. Thanks.
package client

import (
	"github.com/alibabacloud-go/tea/dara"
)

type iCreateScalingRuleResponseBody interface {
	dara.Model
	String() string
	GoString() string
	SetRequestId(v string) *CreateScalingRuleResponseBody
	GetRequestId() *string
	SetScalingRuleAri(v string) *CreateScalingRuleResponseBody
	GetScalingRuleAri() *string
	SetScalingRuleId(v string) *CreateScalingRuleResponseBody
	GetScalingRuleId() *string
}

type CreateScalingRuleResponseBody struct {
	// The ID of the request.
	//
	// example:
	//
	// 473469C7-AA6F-4DC5-B3DB-A3DC0DE3****
	RequestId *string `json:"RequestId,omitempty" xml:"RequestId,omitempty"`
	// The unique identifier of the scaling rule.
	//
	// example:
	//
	// ari:acs:ess:cn-hangzhou:140692647406****:scalingrule/asr-bp1dvirgwkoowxk7****
	ScalingRuleAri *string `json:"ScalingRuleAri,omitempty" xml:"ScalingRuleAri,omitempty"`
	// The ID of the scaling rule, which is generated by the system and is globally unique.
	//
	// example:
	//
	// asr-bp1dvirgwkoowxk7****
	ScalingRuleId *string `json:"ScalingRuleId,omitempty" xml:"ScalingRuleId,omitempty"`
}

func (s CreateScalingRuleResponseBody) String() string {
	return dara.Prettify(s)
}

func (s CreateScalingRuleResponseBody) GoString() string {
	return s.String()
}

func (s *CreateScalingRuleResponseBody) GetRequestId() *string {
	return s.RequestId
}

func (s *CreateScalingRuleResponseBody) GetScalingRuleAri() *string {
	return s.ScalingRuleAri
}

func (s *CreateScalingRuleResponseBody) GetScalingRuleId() *string {
	return s.ScalingRuleId
}

func (s *CreateScalingRuleResponseBody) SetRequestId(v string) *CreateScalingRuleResponseBody {
	s.RequestId = &v
	return s
}

func (s *CreateScalingRuleResponseBody) SetScalingRuleAri(v string) *CreateScalingRuleResponseBody {
	s.ScalingRuleAri = &v
	return s
}

func (s *CreateScalingRuleResponseBody) SetScalingRuleId(v string) *CreateScalingRuleResponseBody {
	s.ScalingRuleId = &v
	return s
}

func (s *CreateScalingRuleResponseBody) Validate() error {
	return dara.Validate(s)
}
