// This file is auto-generated, don't edit it. Thanks.
package client

import (
	"github.com/alibabacloud-go/tea/dara"
)

type iDeleteScheduledTaskRequest interface {
	dara.Model
	String() string
	GoString() string
	SetOwnerAccount(v string) *DeleteScheduledTaskRequest
	GetOwnerAccount() *string
	SetOwnerId(v int64) *DeleteScheduledTaskRequest
	GetOwnerId() *int64
	SetRegionId(v string) *DeleteScheduledTaskRequest
	GetRegionId() *string
	SetResourceOwnerAccount(v string) *DeleteScheduledTaskRequest
	GetResourceOwnerAccount() *string
	SetScheduledTaskId(v string) *DeleteScheduledTaskRequest
	GetScheduledTaskId() *string
}

type DeleteScheduledTaskRequest struct {
	OwnerAccount *string `json:"OwnerAccount,omitempty" xml:"OwnerAccount,omitempty"`
	OwnerId      *int64  `json:"OwnerId,omitempty" xml:"OwnerId,omitempty"`
	// The region ID of the scheduled task.
	//
	// example:
	//
	// cn-qingdao
	RegionId             *string `json:"RegionId,omitempty" xml:"RegionId,omitempty"`
	ResourceOwnerAccount *string `json:"ResourceOwnerAccount,omitempty" xml:"ResourceOwnerAccount,omitempty"`
	// The ID of the scheduled task. An ID is a globally unique identifier (GUID) that is generated by the system for a scheduled task.
	//
	// This parameter is required.
	//
	// example:
	//
	// edRtShc57WGXdt8TlPbr****
	ScheduledTaskId *string `json:"ScheduledTaskId,omitempty" xml:"ScheduledTaskId,omitempty"`
}

func (s DeleteScheduledTaskRequest) String() string {
	return dara.Prettify(s)
}

func (s DeleteScheduledTaskRequest) GoString() string {
	return s.String()
}

func (s *DeleteScheduledTaskRequest) GetOwnerAccount() *string {
	return s.OwnerAccount
}

func (s *DeleteScheduledTaskRequest) GetOwnerId() *int64 {
	return s.OwnerId
}

func (s *DeleteScheduledTaskRequest) GetRegionId() *string {
	return s.RegionId
}

func (s *DeleteScheduledTaskRequest) GetResourceOwnerAccount() *string {
	return s.ResourceOwnerAccount
}

func (s *DeleteScheduledTaskRequest) GetScheduledTaskId() *string {
	return s.ScheduledTaskId
}

func (s *DeleteScheduledTaskRequest) SetOwnerAccount(v string) *DeleteScheduledTaskRequest {
	s.OwnerAccount = &v
	return s
}

func (s *DeleteScheduledTaskRequest) SetOwnerId(v int64) *DeleteScheduledTaskRequest {
	s.OwnerId = &v
	return s
}

func (s *DeleteScheduledTaskRequest) SetRegionId(v string) *DeleteScheduledTaskRequest {
	s.RegionId = &v
	return s
}

func (s *DeleteScheduledTaskRequest) SetResourceOwnerAccount(v string) *DeleteScheduledTaskRequest {
	s.ResourceOwnerAccount = &v
	return s
}

func (s *DeleteScheduledTaskRequest) SetScheduledTaskId(v string) *DeleteScheduledTaskRequest {
	s.ScheduledTaskId = &v
	return s
}

func (s *DeleteScheduledTaskRequest) Validate() error {
	return dara.Validate(s)
}
