// This file is auto-generated, don't edit it. Thanks.
package client

import (
	"github.com/alibabacloud-go/tea/dara"
)

type iDeleteSnapshotRepoRequest interface {
	dara.Model
	String() string
	GoString() string
	SetClientToken(v string) *DeleteSnapshotRepoRequest
	GetClientToken() *string
	SetRepoPath(v string) *DeleteSnapshotRepoRequest
	GetRepoPath() *string
}

type DeleteSnapshotRepoRequest struct {
	// A client token that is used to ensure the idempotence of the request. The value is generated by the client and must be unique among different requests. The value can contain up to 64 ASCII characters.
	//
	// example:
	//
	// 5A2CFF0E-5718-45B5-9D4D-70B3FF****
	ClientToken *string `json:"clientToken,omitempty" xml:"clientToken,omitempty"`
	// The referenced instance ID. To obtain this parameter, see [ListSnapshotReposByInstanceId](https://help.aliyun.com/document_detail/178513.html).
	//
	// .
	//
	// This parameter is required.
	//
	// example:
	//
	// es-cn-n6w1rux8i000w****
	RepoPath *string `json:"repoPath,omitempty" xml:"repoPath,omitempty"`
}

func (s DeleteSnapshotRepoRequest) String() string {
	return dara.Prettify(s)
}

func (s DeleteSnapshotRepoRequest) GoString() string {
	return s.String()
}

func (s *DeleteSnapshotRepoRequest) GetClientToken() *string {
	return s.ClientToken
}

func (s *DeleteSnapshotRepoRequest) GetRepoPath() *string {
	return s.RepoPath
}

func (s *DeleteSnapshotRepoRequest) SetClientToken(v string) *DeleteSnapshotRepoRequest {
	s.ClientToken = &v
	return s
}

func (s *DeleteSnapshotRepoRequest) SetRepoPath(v string) *DeleteSnapshotRepoRequest {
	s.RepoPath = &v
	return s
}

func (s *DeleteSnapshotRepoRequest) Validate() error {
	return dara.Validate(s)
}
