// This file is auto-generated, don't edit it. Thanks.
package client

import (
	"github.com/alibabacloud-go/tea/dara"
)

type iDeleteCollectorRequest interface {
	dara.Model
	String() string
	GoString() string
	SetClientToken(v string) *DeleteCollectorRequest
	GetClientToken() *string
}

type DeleteCollectorRequest struct {
	// A unique token used to ensure idempotence. Generated by the client. The value must be unique across different requests and cannot exceed 64 ASCII characters in length.
	//
	// example:
	//
	// 5A2CFF0E-5718-45B5-9D4D-70B3FF****
	ClientToken *string `json:"ClientToken,omitempty" xml:"ClientToken,omitempty"`
}

func (s DeleteCollectorRequest) String() string {
	return dara.Prettify(s)
}

func (s DeleteCollectorRequest) GoString() string {
	return s.String()
}

func (s *DeleteCollectorRequest) GetClientToken() *string {
	return s.ClientToken
}

func (s *DeleteCollectorRequest) SetClientToken(v string) *DeleteCollectorRequest {
	s.ClientToken = &v
	return s
}

func (s *DeleteCollectorRequest) Validate() error {
	return dara.Validate(s)
}
