// This file is auto-generated, don't edit it. Thanks.
package client

import (
	"github.com/alibabacloud-go/tea/dara"
)

type iRunPipelinesRequest interface {
	dara.Model
	String() string
	GoString() string
	SetClientToken(v string) *RunPipelinesRequest
	GetClientToken() *string
	SetBody(v string) *RunPipelinesRequest
	GetBody() *string
}

type RunPipelinesRequest struct {
	// A unique token generated by the client to ensure idempotence of the request. The token can contain up to 64 ASCII characters and must be unique across different requests.
	//
	// example:
	//
	// 5A2CFF0E-5718-45B5-9D4D-70B3FF****
	ClientToken *string `json:"ClientToken,omitempty" xml:"ClientToken,omitempty"`
	Body        *string `json:"body,omitempty" xml:"body,omitempty"`
}

func (s RunPipelinesRequest) String() string {
	return dara.Prettify(s)
}

func (s RunPipelinesRequest) GoString() string {
	return s.String()
}

func (s *RunPipelinesRequest) GetClientToken() *string {
	return s.ClientToken
}

func (s *RunPipelinesRequest) GetBody() *string {
	return s.Body
}

func (s *RunPipelinesRequest) SetClientToken(v string) *RunPipelinesRequest {
	s.ClientToken = &v
	return s
}

func (s *RunPipelinesRequest) SetBody(v string) *RunPipelinesRequest {
	s.Body = &v
	return s
}

func (s *RunPipelinesRequest) Validate() error {
	return dara.Validate(s)
}
