// This file is auto-generated, don't edit it. Thanks.
package client

import (
	"github.com/alibabacloud-go/tea/dara"
)

type iUpdateInstanceChargeTypeRequest interface {
	dara.Model
	String() string
	GoString() string
	SetPaymentInfo(v *UpdateInstanceChargeTypeRequestPaymentInfo) *UpdateInstanceChargeTypeRequest
	GetPaymentInfo() *UpdateInstanceChargeTypeRequestPaymentInfo
	SetPaymentType(v string) *UpdateInstanceChargeTypeRequest
	GetPaymentType() *string
	SetClientToken(v string) *UpdateInstanceChargeTypeRequest
	GetClientToken() *string
}

type UpdateInstanceChargeTypeRequest struct {
	// The billing information of the instance after the conversion.
	PaymentInfo *UpdateInstanceChargeTypeRequestPaymentInfo `json:"paymentInfo,omitempty" xml:"paymentInfo,omitempty" type:"Struct"`
	// The billing method. Valid values:
	//
	// - prepaid: subscription
	//
	// - postpaid: pay-as-you-go.
	//
	// example:
	//
	// prepaid
	PaymentType *string `json:"paymentType,omitempty" xml:"paymentType,omitempty"`
	// A unique token generated by the client to ensure idempotence of the request. The value must be unique across different requests and can contain up to 64 ASCII characters.
	//
	// example:
	//
	// 5A2CFF0E-5718-45B5-9D4D-70B3FF****
	ClientToken *string `json:"clientToken,omitempty" xml:"clientToken,omitempty"`
}

func (s UpdateInstanceChargeTypeRequest) String() string {
	return dara.Prettify(s)
}

func (s UpdateInstanceChargeTypeRequest) GoString() string {
	return s.String()
}

func (s *UpdateInstanceChargeTypeRequest) GetPaymentInfo() *UpdateInstanceChargeTypeRequestPaymentInfo {
	return s.PaymentInfo
}

func (s *UpdateInstanceChargeTypeRequest) GetPaymentType() *string {
	return s.PaymentType
}

func (s *UpdateInstanceChargeTypeRequest) GetClientToken() *string {
	return s.ClientToken
}

func (s *UpdateInstanceChargeTypeRequest) SetPaymentInfo(v *UpdateInstanceChargeTypeRequestPaymentInfo) *UpdateInstanceChargeTypeRequest {
	s.PaymentInfo = v
	return s
}

func (s *UpdateInstanceChargeTypeRequest) SetPaymentType(v string) *UpdateInstanceChargeTypeRequest {
	s.PaymentType = &v
	return s
}

func (s *UpdateInstanceChargeTypeRequest) SetClientToken(v string) *UpdateInstanceChargeTypeRequest {
	s.ClientToken = &v
	return s
}

func (s *UpdateInstanceChargeTypeRequest) Validate() error {
	if s.PaymentInfo != nil {
		if err := s.PaymentInfo.Validate(); err != nil {
			return err
		}
	}
	return nil
}

type UpdateInstanceChargeTypeRequestPaymentInfo struct {
	// The billing duration. If pricingCycle is set to Year, valid values: 1 to 3. If pricingCycle is set to Month, valid values: 1 to 9.
	//
	// example:
	//
	// 1
	Duration *int32 `json:"duration,omitempty" xml:"duration,omitempty"`
	// The subscription unit. This parameter is required. Valid values:
	//
	// - Year: year
	//
	// - Month: month.
	//
	// example:
	//
	// Month
	PricingCycle *string `json:"pricingCycle,omitempty" xml:"pricingCycle,omitempty"`
}

func (s UpdateInstanceChargeTypeRequestPaymentInfo) String() string {
	return dara.Prettify(s)
}

func (s UpdateInstanceChargeTypeRequestPaymentInfo) GoString() string {
	return s.String()
}

func (s *UpdateInstanceChargeTypeRequestPaymentInfo) GetDuration() *int32 {
	return s.Duration
}

func (s *UpdateInstanceChargeTypeRequestPaymentInfo) GetPricingCycle() *string {
	return s.PricingCycle
}

func (s *UpdateInstanceChargeTypeRequestPaymentInfo) SetDuration(v int32) *UpdateInstanceChargeTypeRequestPaymentInfo {
	s.Duration = &v
	return s
}

func (s *UpdateInstanceChargeTypeRequestPaymentInfo) SetPricingCycle(v string) *UpdateInstanceChargeTypeRequestPaymentInfo {
	s.PricingCycle = &v
	return s
}

func (s *UpdateInstanceChargeTypeRequestPaymentInfo) Validate() error {
	return dara.Validate(s)
}
