// This file is auto-generated, don't edit it. Thanks.
package client

import (
	"github.com/alibabacloud-go/tea/dara"
)

type iRejectOperationTaskApprovalResponseBody interface {
	dara.Model
	String() string
	GoString() string
	SetRequestId(v string) *RejectOperationTaskApprovalResponseBody
	GetRequestId() *string
	SetResults(v []*RejectOperationTaskApprovalResponseBodyResults) *RejectOperationTaskApprovalResponseBody
	GetResults() []*RejectOperationTaskApprovalResponseBodyResults
}

type RejectOperationTaskApprovalResponseBody struct {
	// The unique request ID generated by Alibaba Cloud for this request.
	//
	// example:
	//
	// EC9BF0F4-8983-491A-BC8C-1B4DD94976DE
	RequestId *string `json:"RequestId,omitempty" xml:"RequestId,omitempty"`
	// The returned results.
	Results []*RejectOperationTaskApprovalResponseBodyResults `json:"Results,omitempty" xml:"Results,omitempty" type:"Repeated"`
}

func (s RejectOperationTaskApprovalResponseBody) String() string {
	return dara.Prettify(s)
}

func (s RejectOperationTaskApprovalResponseBody) GoString() string {
	return s.String()
}

func (s *RejectOperationTaskApprovalResponseBody) GetRequestId() *string {
	return s.RequestId
}

func (s *RejectOperationTaskApprovalResponseBody) GetResults() []*RejectOperationTaskApprovalResponseBodyResults {
	return s.Results
}

func (s *RejectOperationTaskApprovalResponseBody) SetRequestId(v string) *RejectOperationTaskApprovalResponseBody {
	s.RequestId = &v
	return s
}

func (s *RejectOperationTaskApprovalResponseBody) SetResults(v []*RejectOperationTaskApprovalResponseBodyResults) *RejectOperationTaskApprovalResponseBody {
	s.Results = v
	return s
}

func (s *RejectOperationTaskApprovalResponseBody) Validate() error {
	if s.Results != nil {
		for _, item := range s.Results {
			if item != nil {
				if err := item.Validate(); err != nil {
					return err
				}
			}
		}
	}
	return nil
}

type RejectOperationTaskApprovalResponseBodyResults struct {
	// example:
	//
	// OK
	Code *string `json:"Code,omitempty" xml:"Code,omitempty"`
	// The error message.
	//
	// example:
	//
	// None
	Message *string `json:"Message,omitempty" xml:"Message,omitempty"`
	// The O&M task ID.
	//
	// example:
	//
	// 1
	TaskId *string `json:"TaskId,omitempty" xml:"TaskId,omitempty"`
}

func (s RejectOperationTaskApprovalResponseBodyResults) String() string {
	return dara.Prettify(s)
}

func (s RejectOperationTaskApprovalResponseBodyResults) GoString() string {
	return s.String()
}

func (s *RejectOperationTaskApprovalResponseBodyResults) GetCode() *string {
	return s.Code
}

func (s *RejectOperationTaskApprovalResponseBodyResults) GetMessage() *string {
	return s.Message
}

func (s *RejectOperationTaskApprovalResponseBodyResults) GetTaskId() *string {
	return s.TaskId
}

func (s *RejectOperationTaskApprovalResponseBodyResults) SetCode(v string) *RejectOperationTaskApprovalResponseBodyResults {
	s.Code = &v
	return s
}

func (s *RejectOperationTaskApprovalResponseBodyResults) SetMessage(v string) *RejectOperationTaskApprovalResponseBodyResults {
	s.Message = &v
	return s
}

func (s *RejectOperationTaskApprovalResponseBodyResults) SetTaskId(v string) *RejectOperationTaskApprovalResponseBodyResults {
	s.TaskId = &v
	return s
}

func (s *RejectOperationTaskApprovalResponseBodyResults) Validate() error {
	return dara.Validate(s)
}
