// This file is auto-generated, don't edit it. Thanks.
package client

import (
	"github.com/alibabacloud-go/tea/dara"
)

type iQueryMMLActiveResponseBody interface {
	dara.Model
	String() string
	GoString() string
	SetAccessDeniedDetail(v string) *QueryMMLActiveResponseBody
	GetAccessDeniedDetail() *string
	SetCode(v string) *QueryMMLActiveResponseBody
	GetCode() *string
	SetData(v string) *QueryMMLActiveResponseBody
	GetData() *string
	SetMessage(v string) *QueryMMLActiveResponseBody
	GetMessage() *string
	SetRequestId(v string) *QueryMMLActiveResponseBody
	GetRequestId() *string
	SetSuccess(v bool) *QueryMMLActiveResponseBody
	GetSuccess() *bool
}

type QueryMMLActiveResponseBody struct {
	// The details about the access denial.
	//
	// example:
	//
	// None
	AccessDeniedDetail *string `json:"AccessDeniedDetail,omitempty" xml:"AccessDeniedDetail,omitempty"`
	// The request status code.
	//
	// - OK indicates that the request was successful.
	//
	// - For other error codes, see [Error codes](https://help.aliyun.com/document_detail/196974.html).
	//
	// example:
	//
	// Sample value.
	Code *string `json:"Code,omitempty" xml:"Code,omitempty"`
	// The returned data object.
	//
	// example:
	//
	// Sample value Sample value.
	Data *string `json:"Data,omitempty" xml:"Data,omitempty"`
	// The response message.
	//
	// example:
	//
	// success
	Message *string `json:"Message,omitempty" xml:"Message,omitempty"`
	// The ID of the request. It is a unique identifier generated by Alibaba Cloud for the request and can be used to troubleshoot issues.
	//
	// example:
	//
	// Sample value Sample value Sample value.
	RequestId *string `json:"RequestId,omitempty" xml:"RequestId,omitempty"`
	// Indicates whether the call was successful. Valid values:
	//
	// - **true**: The call was successful.
	//
	// - **false**: The call failed.
	//
	// example:
	//
	// false
	Success *bool `json:"Success,omitempty" xml:"Success,omitempty"`
}

func (s QueryMMLActiveResponseBody) String() string {
	return dara.Prettify(s)
}

func (s QueryMMLActiveResponseBody) GoString() string {
	return s.String()
}

func (s *QueryMMLActiveResponseBody) GetAccessDeniedDetail() *string {
	return s.AccessDeniedDetail
}

func (s *QueryMMLActiveResponseBody) GetCode() *string {
	return s.Code
}

func (s *QueryMMLActiveResponseBody) GetData() *string {
	return s.Data
}

func (s *QueryMMLActiveResponseBody) GetMessage() *string {
	return s.Message
}

func (s *QueryMMLActiveResponseBody) GetRequestId() *string {
	return s.RequestId
}

func (s *QueryMMLActiveResponseBody) GetSuccess() *bool {
	return s.Success
}

func (s *QueryMMLActiveResponseBody) SetAccessDeniedDetail(v string) *QueryMMLActiveResponseBody {
	s.AccessDeniedDetail = &v
	return s
}

func (s *QueryMMLActiveResponseBody) SetCode(v string) *QueryMMLActiveResponseBody {
	s.Code = &v
	return s
}

func (s *QueryMMLActiveResponseBody) SetData(v string) *QueryMMLActiveResponseBody {
	s.Data = &v
	return s
}

func (s *QueryMMLActiveResponseBody) SetMessage(v string) *QueryMMLActiveResponseBody {
	s.Message = &v
	return s
}

func (s *QueryMMLActiveResponseBody) SetRequestId(v string) *QueryMMLActiveResponseBody {
	s.RequestId = &v
	return s
}

func (s *QueryMMLActiveResponseBody) SetSuccess(v bool) *QueryMMLActiveResponseBody {
	s.Success = &v
	return s
}

func (s *QueryMMLActiveResponseBody) Validate() error {
	return dara.Validate(s)
}
