// This file is auto-generated, don't edit it. Thanks.
package client

import (
	"github.com/alibabacloud-go/tea/dara"
)

type iUpdateAiModelProviderResponseBody interface {
	dara.Model
	String() string
	GoString() string
	SetCode(v string) *UpdateAiModelProviderResponseBody
	GetCode() *string
	SetData(v *UpdateAiModelProviderResponseBodyData) *UpdateAiModelProviderResponseBody
	GetData() *UpdateAiModelProviderResponseBodyData
	SetMessage(v string) *UpdateAiModelProviderResponseBody
	GetMessage() *string
	SetRequestId(v string) *UpdateAiModelProviderResponseBody
	GetRequestId() *string
}

type UpdateAiModelProviderResponseBody struct {
	// The response status code. Ok is returned if the request is successful.
	//
	// example:
	//
	// Ok
	Code *string `json:"code,omitempty" xml:"code,omitempty"`
	// The response data.
	Data *UpdateAiModelProviderResponseBodyData `json:"data,omitempty" xml:"data,omitempty" type:"Struct"`
	// The response message. success is returned if the request is successful.
	//
	// example:
	//
	// success
	Message *string `json:"message,omitempty" xml:"message,omitempty"`
	// The request ID generated by the system for troubleshooting purposes.
	//
	// example:
	//
	// 473469C7-AA6F-4DC5-B3DB-A3DC0DE3C83E
	RequestId *string `json:"requestId,omitempty" xml:"requestId,omitempty"`
}

func (s UpdateAiModelProviderResponseBody) String() string {
	return dara.Prettify(s)
}

func (s UpdateAiModelProviderResponseBody) GoString() string {
	return s.String()
}

func (s *UpdateAiModelProviderResponseBody) GetCode() *string {
	return s.Code
}

func (s *UpdateAiModelProviderResponseBody) GetData() *UpdateAiModelProviderResponseBodyData {
	return s.Data
}

func (s *UpdateAiModelProviderResponseBody) GetMessage() *string {
	return s.Message
}

func (s *UpdateAiModelProviderResponseBody) GetRequestId() *string {
	return s.RequestId
}

func (s *UpdateAiModelProviderResponseBody) SetCode(v string) *UpdateAiModelProviderResponseBody {
	s.Code = &v
	return s
}

func (s *UpdateAiModelProviderResponseBody) SetData(v *UpdateAiModelProviderResponseBodyData) *UpdateAiModelProviderResponseBody {
	s.Data = v
	return s
}

func (s *UpdateAiModelProviderResponseBody) SetMessage(v string) *UpdateAiModelProviderResponseBody {
	s.Message = &v
	return s
}

func (s *UpdateAiModelProviderResponseBody) SetRequestId(v string) *UpdateAiModelProviderResponseBody {
	s.RequestId = &v
	return s
}

func (s *UpdateAiModelProviderResponseBody) Validate() error {
	if s.Data != nil {
		if err := s.Data.Validate(); err != nil {
			return err
		}
	}
	return nil
}

type UpdateAiModelProviderResponseBodyData struct {
	// The list of AI service summaries currently bound to the model provider.
	BoundServices []*ServiceInfo `json:"boundServices,omitempty" xml:"boundServices,omitempty" type:"Repeated"`
	// The display name of the model provider. The name can be up to 128 characters in length.
	//
	// example:
	//
	// Qwen Cloud / Alibaba Cloud Bailian.
	DisplayName *string `json:"displayName,omitempty" xml:"displayName,omitempty"`
	// The ID of the AI gateway instance to which the model provider belongs.
	//
	// example:
	//
	// gw-8c13d2b4f8a1
	GatewayId *string `json:"gatewayId,omitempty" xml:"gatewayId,omitempty"`
	// The list of model cards currently associated with the model provider.
	ModelCards []*UpdateAiModelProviderResponseBodyDataModelCards `json:"modelCards,omitempty" xml:"modelCards,omitempty" type:"Repeated"`
	// The number of model cards currently associated with the model provider.
	//
	// example:
	//
	// 2
	ModelCount *int32 `json:"modelCount,omitempty" xml:"modelCount,omitempty"`
	// The model provider ID. The ID is generated by the system and starts with mp-.
	//
	// example:
	//
	// mp-8c13d2b4f8a1
	ModelProviderId *string `json:"modelProviderId,omitempty" xml:"modelProviderId,omitempty"`
	// The stable identifier of the model provider. The identifier can be up to 128 characters in length.
	//
	// example:
	//
	// qwen
	Provider *string `json:"provider,omitempty" xml:"provider,omitempty"`
	// The source of the model provider. Valid values: user and builtin.
	//
	// example:
	//
	// user
	Source *string `json:"source,omitempty" xml:"source,omitempty"`
	// The last update time of the model provider, in the format of yyyy-MM-dd HH:mm:ss.
	//
	// example:
	//
	// 2026-07-14 18:30:00
	UpdateTime *string `json:"updateTime,omitempty" xml:"updateTime,omitempty"`
}

func (s UpdateAiModelProviderResponseBodyData) String() string {
	return dara.Prettify(s)
}

func (s UpdateAiModelProviderResponseBodyData) GoString() string {
	return s.String()
}

func (s *UpdateAiModelProviderResponseBodyData) GetBoundServices() []*ServiceInfo {
	return s.BoundServices
}

func (s *UpdateAiModelProviderResponseBodyData) GetDisplayName() *string {
	return s.DisplayName
}

func (s *UpdateAiModelProviderResponseBodyData) GetGatewayId() *string {
	return s.GatewayId
}

func (s *UpdateAiModelProviderResponseBodyData) GetModelCards() []*UpdateAiModelProviderResponseBodyDataModelCards {
	return s.ModelCards
}

func (s *UpdateAiModelProviderResponseBodyData) GetModelCount() *int32 {
	return s.ModelCount
}

func (s *UpdateAiModelProviderResponseBodyData) GetModelProviderId() *string {
	return s.ModelProviderId
}

func (s *UpdateAiModelProviderResponseBodyData) GetProvider() *string {
	return s.Provider
}

func (s *UpdateAiModelProviderResponseBodyData) GetSource() *string {
	return s.Source
}

func (s *UpdateAiModelProviderResponseBodyData) GetUpdateTime() *string {
	return s.UpdateTime
}

func (s *UpdateAiModelProviderResponseBodyData) SetBoundServices(v []*ServiceInfo) *UpdateAiModelProviderResponseBodyData {
	s.BoundServices = v
	return s
}

func (s *UpdateAiModelProviderResponseBodyData) SetDisplayName(v string) *UpdateAiModelProviderResponseBodyData {
	s.DisplayName = &v
	return s
}

func (s *UpdateAiModelProviderResponseBodyData) SetGatewayId(v string) *UpdateAiModelProviderResponseBodyData {
	s.GatewayId = &v
	return s
}

func (s *UpdateAiModelProviderResponseBodyData) SetModelCards(v []*UpdateAiModelProviderResponseBodyDataModelCards) *UpdateAiModelProviderResponseBodyData {
	s.ModelCards = v
	return s
}

func (s *UpdateAiModelProviderResponseBodyData) SetModelCount(v int32) *UpdateAiModelProviderResponseBodyData {
	s.ModelCount = &v
	return s
}

func (s *UpdateAiModelProviderResponseBodyData) SetModelProviderId(v string) *UpdateAiModelProviderResponseBodyData {
	s.ModelProviderId = &v
	return s
}

func (s *UpdateAiModelProviderResponseBodyData) SetProvider(v string) *UpdateAiModelProviderResponseBodyData {
	s.Provider = &v
	return s
}

func (s *UpdateAiModelProviderResponseBodyData) SetSource(v string) *UpdateAiModelProviderResponseBodyData {
	s.Source = &v
	return s
}

func (s *UpdateAiModelProviderResponseBodyData) SetUpdateTime(v string) *UpdateAiModelProviderResponseBodyData {
	s.UpdateTime = &v
	return s
}

func (s *UpdateAiModelProviderResponseBodyData) Validate() error {
	if s.BoundServices != nil {
		for _, item := range s.BoundServices {
			if item != nil {
				if err := item.Validate(); err != nil {
					return err
				}
			}
		}
	}
	if s.ModelCards != nil {
		for _, item := range s.ModelCards {
			if item != nil {
				if err := item.Validate(); err != nil {
					return err
				}
			}
		}
	}
	return nil
}

type UpdateAiModelProviderResponseBodyDataModelCards struct {
	// The list of invocation paths supported by the model. Each item contains both path and type.
	AvailablePaths []*UpdateAiModelProviderResponseBodyDataModelCardsAvailablePaths `json:"availablePaths,omitempty" xml:"availablePaths,omitempty" type:"Repeated"`
	// The credit billing information of the model. The unit is Credits per million tokens.
	Credit *UpdateAiModelProviderResponseBodyDataModelCardsCredit `json:"credit,omitempty" xml:"credit,omitempty" type:"Struct"`
	// The model capability switches. Keys are model capability names supported by the API gateway, and values are Boolean values.
	//
	// example:
	//
	// {"functionCalling":true,"toolChoice":true}
	Features map[string]interface{} `json:"features,omitempty" xml:"features,omitempty"`
	// The ID of the AI gateway instance to which the model card belongs.
	//
	// example:
	//
	// gw-8c13d2b4f8a1
	GatewayId *string `json:"gatewayId,omitempty" xml:"gatewayId,omitempty"`
	// The token limits and input/output modality information of the model.
	Meta *UpdateAiModelProviderResponseBodyDataModelCardsMeta `json:"meta,omitempty" xml:"meta,omitempty" type:"Struct"`
	// The model card ID. The ID is generated by the system and starts with mc-.
	//
	// example:
	//
	// mc-8c13d2b4f8a1
	ModelCardId *string `json:"modelCardId,omitempty" xml:"modelCardId,omitempty"`
	// The model name.
	//
	// example:
	//
	// qwen-plus
	ModelName *string `json:"modelName,omitempty" xml:"modelName,omitempty"`
	// The model provider identifier.
	//
	// example:
	//
	// qwen
	ModelProvider *string `json:"modelProvider,omitempty" xml:"modelProvider,omitempty"`
	// The source of the model card. Instance-level model cards return user.
	//
	// example:
	//
	// user
	Source *string `json:"source,omitempty" xml:"source,omitempty"`
	// The URL of the model metadata.
	//
	// example:
	//
	// http://https://dashscope-intl.aliyuncs.com
	SourceURL *string `json:"sourceURL,omitempty" xml:"sourceURL,omitempty"`
	// The last update time of the model card, in the format of yyyy-MM-dd HH:mm:ss.
	//
	// example:
	//
	// 2026-07-14 18:30:00
	UpdateTime *string `json:"updateTime,omitempty" xml:"updateTime,omitempty"`
}

func (s UpdateAiModelProviderResponseBodyDataModelCards) String() string {
	return dara.Prettify(s)
}

func (s UpdateAiModelProviderResponseBodyDataModelCards) GoString() string {
	return s.String()
}

func (s *UpdateAiModelProviderResponseBodyDataModelCards) GetAvailablePaths() []*UpdateAiModelProviderResponseBodyDataModelCardsAvailablePaths {
	return s.AvailablePaths
}

func (s *UpdateAiModelProviderResponseBodyDataModelCards) GetCredit() *UpdateAiModelProviderResponseBodyDataModelCardsCredit {
	return s.Credit
}

func (s *UpdateAiModelProviderResponseBodyDataModelCards) GetFeatures() map[string]interface{} {
	return s.Features
}

func (s *UpdateAiModelProviderResponseBodyDataModelCards) GetGatewayId() *string {
	return s.GatewayId
}

func (s *UpdateAiModelProviderResponseBodyDataModelCards) GetMeta() *UpdateAiModelProviderResponseBodyDataModelCardsMeta {
	return s.Meta
}

func (s *UpdateAiModelProviderResponseBodyDataModelCards) GetModelCardId() *string {
	return s.ModelCardId
}

func (s *UpdateAiModelProviderResponseBodyDataModelCards) GetModelName() *string {
	return s.ModelName
}

func (s *UpdateAiModelProviderResponseBodyDataModelCards) GetModelProvider() *string {
	return s.ModelProvider
}

func (s *UpdateAiModelProviderResponseBodyDataModelCards) GetSource() *string {
	return s.Source
}

func (s *UpdateAiModelProviderResponseBodyDataModelCards) GetSourceURL() *string {
	return s.SourceURL
}

func (s *UpdateAiModelProviderResponseBodyDataModelCards) GetUpdateTime() *string {
	return s.UpdateTime
}

func (s *UpdateAiModelProviderResponseBodyDataModelCards) SetAvailablePaths(v []*UpdateAiModelProviderResponseBodyDataModelCardsAvailablePaths) *UpdateAiModelProviderResponseBodyDataModelCards {
	s.AvailablePaths = v
	return s
}

func (s *UpdateAiModelProviderResponseBodyDataModelCards) SetCredit(v *UpdateAiModelProviderResponseBodyDataModelCardsCredit) *UpdateAiModelProviderResponseBodyDataModelCards {
	s.Credit = v
	return s
}

func (s *UpdateAiModelProviderResponseBodyDataModelCards) SetFeatures(v map[string]interface{}) *UpdateAiModelProviderResponseBodyDataModelCards {
	s.Features = v
	return s
}

func (s *UpdateAiModelProviderResponseBodyDataModelCards) SetGatewayId(v string) *UpdateAiModelProviderResponseBodyDataModelCards {
	s.GatewayId = &v
	return s
}

func (s *UpdateAiModelProviderResponseBodyDataModelCards) SetMeta(v *UpdateAiModelProviderResponseBodyDataModelCardsMeta) *UpdateAiModelProviderResponseBodyDataModelCards {
	s.Meta = v
	return s
}

func (s *UpdateAiModelProviderResponseBodyDataModelCards) SetModelCardId(v string) *UpdateAiModelProviderResponseBodyDataModelCards {
	s.ModelCardId = &v
	return s
}

func (s *UpdateAiModelProviderResponseBodyDataModelCards) SetModelName(v string) *UpdateAiModelProviderResponseBodyDataModelCards {
	s.ModelName = &v
	return s
}

func (s *UpdateAiModelProviderResponseBodyDataModelCards) SetModelProvider(v string) *UpdateAiModelProviderResponseBodyDataModelCards {
	s.ModelProvider = &v
	return s
}

func (s *UpdateAiModelProviderResponseBodyDataModelCards) SetSource(v string) *UpdateAiModelProviderResponseBodyDataModelCards {
	s.Source = &v
	return s
}

func (s *UpdateAiModelProviderResponseBodyDataModelCards) SetSourceURL(v string) *UpdateAiModelProviderResponseBodyDataModelCards {
	s.SourceURL = &v
	return s
}

func (s *UpdateAiModelProviderResponseBodyDataModelCards) SetUpdateTime(v string) *UpdateAiModelProviderResponseBodyDataModelCards {
	s.UpdateTime = &v
	return s
}

func (s *UpdateAiModelProviderResponseBodyDataModelCards) Validate() error {
	if s.AvailablePaths != nil {
		for _, item := range s.AvailablePaths {
			if item != nil {
				if err := item.Validate(); err != nil {
					return err
				}
			}
		}
	}
	if s.Credit != nil {
		if err := s.Credit.Validate(); err != nil {
			return err
		}
	}
	if s.Meta != nil {
		if err := s.Meta.Validate(); err != nil {
			return err
		}
	}
	return nil
}

type UpdateAiModelProviderResponseBodyDataModelCardsAvailablePaths struct {
	// The model invocation path. The path can be up to 2048 characters in length.
	//
	// example:
	//
	// /v1/chat/completions
	Path *string `json:"path,omitempty" xml:"path,omitempty"`
	// The protocol type corresponding to the path. The value can be up to 64 characters in length.
	//
	// example:
	//
	// OpenAICompatible
	Type *string `json:"type,omitempty" xml:"type,omitempty"`
}

func (s UpdateAiModelProviderResponseBodyDataModelCardsAvailablePaths) String() string {
	return dara.Prettify(s)
}

func (s UpdateAiModelProviderResponseBodyDataModelCardsAvailablePaths) GoString() string {
	return s.String()
}

func (s *UpdateAiModelProviderResponseBodyDataModelCardsAvailablePaths) GetPath() *string {
	return s.Path
}

func (s *UpdateAiModelProviderResponseBodyDataModelCardsAvailablePaths) GetType() *string {
	return s.Type
}

func (s *UpdateAiModelProviderResponseBodyDataModelCardsAvailablePaths) SetPath(v string) *UpdateAiModelProviderResponseBodyDataModelCardsAvailablePaths {
	s.Path = &v
	return s
}

func (s *UpdateAiModelProviderResponseBodyDataModelCardsAvailablePaths) SetType(v string) *UpdateAiModelProviderResponseBodyDataModelCardsAvailablePaths {
	s.Type = &v
	return s
}

func (s *UpdateAiModelProviderResponseBodyDataModelCardsAvailablePaths) Validate() error {
	return dara.Validate(s)
}

type UpdateAiModelProviderResponseBodyDataModelCardsCredit struct {
	// The cost of cache-hit tokens, in Credits per million tokens.
	//
	// example:
	//
	// 0.5
	CacheCost *float32 `json:"cacheCost,omitempty" xml:"cacheCost,omitempty"`
	// The cost of input tokens, in Credits per million tokens.
	//
	// example:
	//
	// 1.5
	InputCost *float32 `json:"inputCost,omitempty" xml:"inputCost,omitempty"`
	// The cost of output tokens, in Credits per million tokens.
	//
	// example:
	//
	// 3
	OutputCost *float32 `json:"outputCost,omitempty" xml:"outputCost,omitempty"`
	// The billing type. Only fixed is supported.
	//
	// example:
	//
	// fixed
	Type *string `json:"type,omitempty" xml:"type,omitempty"`
}

func (s UpdateAiModelProviderResponseBodyDataModelCardsCredit) String() string {
	return dara.Prettify(s)
}

func (s UpdateAiModelProviderResponseBodyDataModelCardsCredit) GoString() string {
	return s.String()
}

func (s *UpdateAiModelProviderResponseBodyDataModelCardsCredit) GetCacheCost() *float32 {
	return s.CacheCost
}

func (s *UpdateAiModelProviderResponseBodyDataModelCardsCredit) GetInputCost() *float32 {
	return s.InputCost
}

func (s *UpdateAiModelProviderResponseBodyDataModelCardsCredit) GetOutputCost() *float32 {
	return s.OutputCost
}

func (s *UpdateAiModelProviderResponseBodyDataModelCardsCredit) GetType() *string {
	return s.Type
}

func (s *UpdateAiModelProviderResponseBodyDataModelCardsCredit) SetCacheCost(v float32) *UpdateAiModelProviderResponseBodyDataModelCardsCredit {
	s.CacheCost = &v
	return s
}

func (s *UpdateAiModelProviderResponseBodyDataModelCardsCredit) SetInputCost(v float32) *UpdateAiModelProviderResponseBodyDataModelCardsCredit {
	s.InputCost = &v
	return s
}

func (s *UpdateAiModelProviderResponseBodyDataModelCardsCredit) SetOutputCost(v float32) *UpdateAiModelProviderResponseBodyDataModelCardsCredit {
	s.OutputCost = &v
	return s
}

func (s *UpdateAiModelProviderResponseBodyDataModelCardsCredit) SetType(v string) *UpdateAiModelProviderResponseBodyDataModelCardsCredit {
	s.Type = &v
	return s
}

func (s *UpdateAiModelProviderResponseBodyDataModelCardsCredit) Validate() error {
	return dara.Validate(s)
}

type UpdateAiModelProviderResponseBodyDataModelCardsMeta struct {
	// The maximum number of input tokens supported by the model. The value is greater than or equal to 0.
	//
	// example:
	//
	// 131072
	MaxInputTokens *int64 `json:"maxInputTokens,omitempty" xml:"maxInputTokens,omitempty"`
	// The maximum number of output tokens supported by the model. The value is greater than or equal to 0.
	//
	// example:
	//
	// 8192
	MaxOutputTokens *int64 `json:"maxOutputTokens,omitempty" xml:"maxOutputTokens,omitempty"`
	// The maximum total number of context tokens supported by the model. The value is greater than or equal to 0.
	//
	// example:
	//
	// 131072
	MaxTokens *int64 `json:"maxTokens,omitempty" xml:"maxTokens,omitempty"`
	// The list of input modalities supported by the model. The list contains up to 16 items, and each item must not be empty.
	SupportedInputModalities []*string `json:"supportedInputModalities,omitempty" xml:"supportedInputModalities,omitempty" type:"Repeated"`
	// The list of output modalities supported by the model. The list contains up to 16 items, and each item must not be empty.
	SupportedOutputModalities []*string `json:"supportedOutputModalities,omitempty" xml:"supportedOutputModalities,omitempty" type:"Repeated"`
}

func (s UpdateAiModelProviderResponseBodyDataModelCardsMeta) String() string {
	return dara.Prettify(s)
}

func (s UpdateAiModelProviderResponseBodyDataModelCardsMeta) GoString() string {
	return s.String()
}

func (s *UpdateAiModelProviderResponseBodyDataModelCardsMeta) GetMaxInputTokens() *int64 {
	return s.MaxInputTokens
}

func (s *UpdateAiModelProviderResponseBodyDataModelCardsMeta) GetMaxOutputTokens() *int64 {
	return s.MaxOutputTokens
}

func (s *UpdateAiModelProviderResponseBodyDataModelCardsMeta) GetMaxTokens() *int64 {
	return s.MaxTokens
}

func (s *UpdateAiModelProviderResponseBodyDataModelCardsMeta) GetSupportedInputModalities() []*string {
	return s.SupportedInputModalities
}

func (s *UpdateAiModelProviderResponseBodyDataModelCardsMeta) GetSupportedOutputModalities() []*string {
	return s.SupportedOutputModalities
}

func (s *UpdateAiModelProviderResponseBodyDataModelCardsMeta) SetMaxInputTokens(v int64) *UpdateAiModelProviderResponseBodyDataModelCardsMeta {
	s.MaxInputTokens = &v
	return s
}

func (s *UpdateAiModelProviderResponseBodyDataModelCardsMeta) SetMaxOutputTokens(v int64) *UpdateAiModelProviderResponseBodyDataModelCardsMeta {
	s.MaxOutputTokens = &v
	return s
}

func (s *UpdateAiModelProviderResponseBodyDataModelCardsMeta) SetMaxTokens(v int64) *UpdateAiModelProviderResponseBodyDataModelCardsMeta {
	s.MaxTokens = &v
	return s
}

func (s *UpdateAiModelProviderResponseBodyDataModelCardsMeta) SetSupportedInputModalities(v []*string) *UpdateAiModelProviderResponseBodyDataModelCardsMeta {
	s.SupportedInputModalities = v
	return s
}

func (s *UpdateAiModelProviderResponseBodyDataModelCardsMeta) SetSupportedOutputModalities(v []*string) *UpdateAiModelProviderResponseBodyDataModelCardsMeta {
	s.SupportedOutputModalities = v
	return s
}

func (s *UpdateAiModelProviderResponseBodyDataModelCardsMeta) Validate() error {
	return dara.Validate(s)
}
