// This file is auto-generated, don't edit it. Thanks.
package client

import (
	"github.com/alibabacloud-go/tea/dara"
)

type iDescribeDBInstanceCLSResponseBody interface {
	dara.Model
	String() string
	GoString() string
	SetAlgorithm(v string) *DescribeDBInstanceCLSResponseBody
	GetAlgorithm() *string
	SetEncryptionKey(v string) *DescribeDBInstanceCLSResponseBody
	GetEncryptionKey() *string
	SetEncryptionKeyMode(v string) *DescribeDBInstanceCLSResponseBody
	GetEncryptionKeyMode() *string
	SetRequestId(v string) *DescribeDBInstanceCLSResponseBody
	GetRequestId() *string
	SetWhiteListMode(v bool) *DescribeDBInstanceCLSResponseBody
	GetWhiteListMode() *bool
}

type DescribeDBInstanceCLSResponseBody struct {
	// Encryption algorithm used. The following options are available:
	//
	// - AES_128_CBC
	//
	// - AES_128_GCM
	//
	// - AES_128_CTR
	//
	// - AES_128_ECB
	//
	// - AES_256_CBC
	//
	// - AES_256_GCM
	//
	// - AES_256_CTR
	//
	// - AES_256_ECB
	//
	// - SM4_128_CBC
	//
	// - SM4_128_GCM
	//
	// - SM4_128_CTR
	//
	// - SM4_128_ECB
	//
	// example:
	//
	// AES_256_GCM
	Algorithm *string `json:"Algorithm,omitempty" xml:"Algorithm,omitempty"`
	// Custom KMS master key ID.
	//
	// Note:
	//
	// This parameter takes effect only when the column encryption key mode is set to kms_key. If this parameter is not provided, the current database column encryption key settings will not be changed.
	//
	// example:
	//
	// 749c1df7-****-****-****-****
	EncryptionKey *string `json:"EncryptionKey,omitempty" xml:"EncryptionKey,omitempty"`
	// Column encryption key mode. The following options are available:
	//
	// - client_key (configure a random key generated by the user on the client side)
	//
	// - kms_key (use Alibaba Cloud KMS to configure a custom key)
	//
	// Note:
	//
	// Once an instance is configured to use a KMS-managed key, it can no longer use the client-side random key configuration method.
	//
	// example:
	//
	// kms_key
	EncryptionKeyMode *string `json:"EncryptionKeyMode,omitempty" xml:"EncryptionKeyMode,omitempty"`
	// Request ID
	//
	// example:
	//
	// D0073A98-52F1-3075-8256-3943F*******
	RequestId *string `json:"RequestId,omitempty" xml:"RequestId,omitempty"`
	// Indicates whether whitelist mode is enabled.
	//
	// example:
	//
	// true
	WhiteListMode *bool `json:"WhiteListMode,omitempty" xml:"WhiteListMode,omitempty"`
}

func (s DescribeDBInstanceCLSResponseBody) String() string {
	return dara.Prettify(s)
}

func (s DescribeDBInstanceCLSResponseBody) GoString() string {
	return s.String()
}

func (s *DescribeDBInstanceCLSResponseBody) GetAlgorithm() *string {
	return s.Algorithm
}

func (s *DescribeDBInstanceCLSResponseBody) GetEncryptionKey() *string {
	return s.EncryptionKey
}

func (s *DescribeDBInstanceCLSResponseBody) GetEncryptionKeyMode() *string {
	return s.EncryptionKeyMode
}

func (s *DescribeDBInstanceCLSResponseBody) GetRequestId() *string {
	return s.RequestId
}

func (s *DescribeDBInstanceCLSResponseBody) GetWhiteListMode() *bool {
	return s.WhiteListMode
}

func (s *DescribeDBInstanceCLSResponseBody) SetAlgorithm(v string) *DescribeDBInstanceCLSResponseBody {
	s.Algorithm = &v
	return s
}

func (s *DescribeDBInstanceCLSResponseBody) SetEncryptionKey(v string) *DescribeDBInstanceCLSResponseBody {
	s.EncryptionKey = &v
	return s
}

func (s *DescribeDBInstanceCLSResponseBody) SetEncryptionKeyMode(v string) *DescribeDBInstanceCLSResponseBody {
	s.EncryptionKeyMode = &v
	return s
}

func (s *DescribeDBInstanceCLSResponseBody) SetRequestId(v string) *DescribeDBInstanceCLSResponseBody {
	s.RequestId = &v
	return s
}

func (s *DescribeDBInstanceCLSResponseBody) SetWhiteListMode(v bool) *DescribeDBInstanceCLSResponseBody {
	s.WhiteListMode = &v
	return s
}

func (s *DescribeDBInstanceCLSResponseBody) Validate() error {
	return dara.Validate(s)
}
