// This file is auto-generated, don't edit it. Thanks.
package client

import (
	"github.com/alibabacloud-go/tea/dara"
)

type iListPlaybooksResponseBody interface {
	dara.Model
	String() string
	GoString() string
	SetMaxResults(v int32) *ListPlaybooksResponseBody
	GetMaxResults() *int32
	SetNextToken(v string) *ListPlaybooksResponseBody
	GetNextToken() *string
	SetPageNumber(v int32) *ListPlaybooksResponseBody
	GetPageNumber() *int32
	SetPageSize(v int32) *ListPlaybooksResponseBody
	GetPageSize() *int32
	SetPlaybooks(v []*ListPlaybooksResponseBodyPlaybooks) *ListPlaybooksResponseBody
	GetPlaybooks() []*ListPlaybooksResponseBodyPlaybooks
	SetRequestId(v string) *ListPlaybooksResponseBody
	GetRequestId() *string
	SetTotalCount(v int32) *ListPlaybooksResponseBody
	GetTotalCount() *int32
}

type ListPlaybooksResponseBody struct {
	// Maximum number of results allowed to be returned. Range: 0~100.
	//
	// example:
	//
	// 50
	MaxResults *int32 `json:"MaxResults,omitempty" xml:"MaxResults,omitempty"`
	// Token for the start of the next page query.
	//
	// example:
	//
	// 7fbb1c****07c1f79a740f039a8dcfda
	NextToken *string `json:"NextToken,omitempty" xml:"NextToken,omitempty"`
	// Current page number. The default value is 1.
	//
	// example:
	//
	// 1
	PageNumber *int32 `json:"PageNumber,omitempty" xml:"PageNumber,omitempty"`
	// Number of items per page in a paginated query.
	//
	// example:
	//
	// 10
	PageSize *int32 `json:"PageSize,omitempty" xml:"PageSize,omitempty"`
	// List of playbooks.
	Playbooks []*ListPlaybooksResponseBodyPlaybooks `json:"Playbooks,omitempty" xml:"Playbooks,omitempty" type:"Repeated"`
	// The unique identifier generated by Alibaba Cloud for this request, which can be used for troubleshooting and problem localization.
	//
	// example:
	//
	// 567D3D0B-2153-5860-BF9A-F9DEED55FB73
	RequestId *string `json:"RequestId,omitempty" xml:"RequestId,omitempty"`
	// Total number of items found.
	//
	// example:
	//
	// 100
	TotalCount *int32 `json:"TotalCount,omitempty" xml:"TotalCount,omitempty"`
}

func (s ListPlaybooksResponseBody) String() string {
	return dara.Prettify(s)
}

func (s ListPlaybooksResponseBody) GoString() string {
	return s.String()
}

func (s *ListPlaybooksResponseBody) GetMaxResults() *int32 {
	return s.MaxResults
}

func (s *ListPlaybooksResponseBody) GetNextToken() *string {
	return s.NextToken
}

func (s *ListPlaybooksResponseBody) GetPageNumber() *int32 {
	return s.PageNumber
}

func (s *ListPlaybooksResponseBody) GetPageSize() *int32 {
	return s.PageSize
}

func (s *ListPlaybooksResponseBody) GetPlaybooks() []*ListPlaybooksResponseBodyPlaybooks {
	return s.Playbooks
}

func (s *ListPlaybooksResponseBody) GetRequestId() *string {
	return s.RequestId
}

func (s *ListPlaybooksResponseBody) GetTotalCount() *int32 {
	return s.TotalCount
}

func (s *ListPlaybooksResponseBody) SetMaxResults(v int32) *ListPlaybooksResponseBody {
	s.MaxResults = &v
	return s
}

func (s *ListPlaybooksResponseBody) SetNextToken(v string) *ListPlaybooksResponseBody {
	s.NextToken = &v
	return s
}

func (s *ListPlaybooksResponseBody) SetPageNumber(v int32) *ListPlaybooksResponseBody {
	s.PageNumber = &v
	return s
}

func (s *ListPlaybooksResponseBody) SetPageSize(v int32) *ListPlaybooksResponseBody {
	s.PageSize = &v
	return s
}

func (s *ListPlaybooksResponseBody) SetPlaybooks(v []*ListPlaybooksResponseBodyPlaybooks) *ListPlaybooksResponseBody {
	s.Playbooks = v
	return s
}

func (s *ListPlaybooksResponseBody) SetRequestId(v string) *ListPlaybooksResponseBody {
	s.RequestId = &v
	return s
}

func (s *ListPlaybooksResponseBody) SetTotalCount(v int32) *ListPlaybooksResponseBody {
	s.TotalCount = &v
	return s
}

func (s *ListPlaybooksResponseBody) Validate() error {
	if s.Playbooks != nil {
		for _, item := range s.Playbooks {
			if item != nil {
				if err := item.Validate(); err != nil {
					return err
				}
			}
		}
	}
	return nil
}

type ListPlaybooksResponseBodyPlaybooks struct {
	// Creation time (in milliseconds).
	//
	// example:
	//
	// 1667792399000
	CreateTime *int64 `json:"CreateTime,omitempty" xml:"CreateTime,omitempty"`
	// Description of the playbook.
	//
	// example:
	//
	// alb block
	PlaybookDescription *string `json:"PlaybookDescription,omitempty" xml:"PlaybookDescription,omitempty"`
	// Extended information of the playbook.
	//
	// example:
	//
	// {}
	PlaybookExtension *string `json:"PlaybookExtension,omitempty" xml:"PlaybookExtension,omitempty"`
	// List of input parameter configurations for the playbook.
	PlaybookInputConfigs []*FieldInputConfig `json:"PlaybookInputConfigs,omitempty" xml:"PlaybookInputConfigs,omitempty" type:"Repeated"`
	// Name of the playbook.
	//
	// example:
	//
	// system_aliyun_alb_process_book
	PlaybookName *string `json:"PlaybookName,omitempty" xml:"PlaybookName,omitempty"`
	// List of output parameter configurations for the playbook.
	PlaybookOutputConfigs []*FieldOutputConfig `json:"PlaybookOutputConfigs,omitempty" xml:"PlaybookOutputConfigs,omitempty" type:"Repeated"`
	// The parameter type of the playbook, with values as follows:
	//
	// - **template-ip**: IP entity.
	//
	// - **template-file**: File entity.
	//
	// - **template-process**: Process entity.
	//
	// - **template-host**: Host entity.
	//
	// - **template-domain**: Domain entity.
	//
	// - **template-container**: Container entity.
	//
	// - **template-incident**: Security incident.
	//
	// - **template-alert**: Security alert.
	//
	// - **custom**: Custom.
	//
	// example:
	//
	// template-ip
	PlaybookParamType *string `json:"PlaybookParamType,omitempty" xml:"PlaybookParamType,omitempty"`
	// The publication status of the playbook, with values as follows:
	//
	// - **0**: Unpublished.
	//
	// - **1**: Published.
	//
	// example:
	//
	// 1
	PlaybookStatus *int32 `json:"PlaybookStatus,omitempty" xml:"PlaybookStatus,omitempty"`
	// Type of the playbook, with values as follows:
	//
	// - **preset**: Predefined playbook.
	//
	// - **user**: Custom playbook.
	//
	// - **component**: Security response component.
	//
	// example:
	//
	// user
	PlaybookType *string `json:"PlaybookType,omitempty" xml:"PlaybookType,omitempty"`
	// UUID of the playbook.
	//
	// example:
	//
	// bb5a8640-a14f-44ef-8376-cxxxxx
	PlaybookUuid *string `json:"PlaybookUuid,omitempty" xml:"PlaybookUuid,omitempty"`
	// Update time (in milliseconds).
	//
	// example:
	//
	// 1731378251000
	UpdateTime *int64 `json:"UpdateTime,omitempty" xml:"UpdateTime,omitempty"`
}

func (s ListPlaybooksResponseBodyPlaybooks) String() string {
	return dara.Prettify(s)
}

func (s ListPlaybooksResponseBodyPlaybooks) GoString() string {
	return s.String()
}

func (s *ListPlaybooksResponseBodyPlaybooks) GetCreateTime() *int64 {
	return s.CreateTime
}

func (s *ListPlaybooksResponseBodyPlaybooks) GetPlaybookDescription() *string {
	return s.PlaybookDescription
}

func (s *ListPlaybooksResponseBodyPlaybooks) GetPlaybookExtension() *string {
	return s.PlaybookExtension
}

func (s *ListPlaybooksResponseBodyPlaybooks) GetPlaybookInputConfigs() []*FieldInputConfig {
	return s.PlaybookInputConfigs
}

func (s *ListPlaybooksResponseBodyPlaybooks) GetPlaybookName() *string {
	return s.PlaybookName
}

func (s *ListPlaybooksResponseBodyPlaybooks) GetPlaybookOutputConfigs() []*FieldOutputConfig {
	return s.PlaybookOutputConfigs
}

func (s *ListPlaybooksResponseBodyPlaybooks) GetPlaybookParamType() *string {
	return s.PlaybookParamType
}

func (s *ListPlaybooksResponseBodyPlaybooks) GetPlaybookStatus() *int32 {
	return s.PlaybookStatus
}

func (s *ListPlaybooksResponseBodyPlaybooks) GetPlaybookType() *string {
	return s.PlaybookType
}

func (s *ListPlaybooksResponseBodyPlaybooks) GetPlaybookUuid() *string {
	return s.PlaybookUuid
}

func (s *ListPlaybooksResponseBodyPlaybooks) GetUpdateTime() *int64 {
	return s.UpdateTime
}

func (s *ListPlaybooksResponseBodyPlaybooks) SetCreateTime(v int64) *ListPlaybooksResponseBodyPlaybooks {
	s.CreateTime = &v
	return s
}

func (s *ListPlaybooksResponseBodyPlaybooks) SetPlaybookDescription(v string) *ListPlaybooksResponseBodyPlaybooks {
	s.PlaybookDescription = &v
	return s
}

func (s *ListPlaybooksResponseBodyPlaybooks) SetPlaybookExtension(v string) *ListPlaybooksResponseBodyPlaybooks {
	s.PlaybookExtension = &v
	return s
}

func (s *ListPlaybooksResponseBodyPlaybooks) SetPlaybookInputConfigs(v []*FieldInputConfig) *ListPlaybooksResponseBodyPlaybooks {
	s.PlaybookInputConfigs = v
	return s
}

func (s *ListPlaybooksResponseBodyPlaybooks) SetPlaybookName(v string) *ListPlaybooksResponseBodyPlaybooks {
	s.PlaybookName = &v
	return s
}

func (s *ListPlaybooksResponseBodyPlaybooks) SetPlaybookOutputConfigs(v []*FieldOutputConfig) *ListPlaybooksResponseBodyPlaybooks {
	s.PlaybookOutputConfigs = v
	return s
}

func (s *ListPlaybooksResponseBodyPlaybooks) SetPlaybookParamType(v string) *ListPlaybooksResponseBodyPlaybooks {
	s.PlaybookParamType = &v
	return s
}

func (s *ListPlaybooksResponseBodyPlaybooks) SetPlaybookStatus(v int32) *ListPlaybooksResponseBodyPlaybooks {
	s.PlaybookStatus = &v
	return s
}

func (s *ListPlaybooksResponseBodyPlaybooks) SetPlaybookType(v string) *ListPlaybooksResponseBodyPlaybooks {
	s.PlaybookType = &v
	return s
}

func (s *ListPlaybooksResponseBodyPlaybooks) SetPlaybookUuid(v string) *ListPlaybooksResponseBodyPlaybooks {
	s.PlaybookUuid = &v
	return s
}

func (s *ListPlaybooksResponseBodyPlaybooks) SetUpdateTime(v int64) *ListPlaybooksResponseBodyPlaybooks {
	s.UpdateTime = &v
	return s
}

func (s *ListPlaybooksResponseBodyPlaybooks) Validate() error {
	if s.PlaybookInputConfigs != nil {
		for _, item := range s.PlaybookInputConfigs {
			if item != nil {
				if err := item.Validate(); err != nil {
					return err
				}
			}
		}
	}
	if s.PlaybookOutputConfigs != nil {
		for _, item := range s.PlaybookOutputConfigs {
			if item != nil {
				if err := item.Validate(); err != nil {
					return err
				}
			}
		}
	}
	return nil
}
