// This file is auto-generated, don't edit it. Thanks.
package client

import (
	"github.com/alibabacloud-go/tea/dara"
)

type iAddCasterEpisodeGroupRequest interface {
	dara.Model
	String() string
	GoString() string
	SetCallbackUrl(v string) *AddCasterEpisodeGroupRequest
	GetCallbackUrl() *string
	SetClientToken(v string) *AddCasterEpisodeGroupRequest
	GetClientToken() *string
	SetDomainName(v string) *AddCasterEpisodeGroupRequest
	GetDomainName() *string
	SetItem(v []*AddCasterEpisodeGroupRequestItem) *AddCasterEpisodeGroupRequest
	GetItem() []*AddCasterEpisodeGroupRequestItem
	SetOwnerId(v int64) *AddCasterEpisodeGroupRequest
	GetOwnerId() *int64
	SetRegionId(v string) *AddCasterEpisodeGroupRequest
	GetRegionId() *string
	SetRepeatNum(v int32) *AddCasterEpisodeGroupRequest
	GetRepeatNum() *int32
	SetSideOutputUrl(v string) *AddCasterEpisodeGroupRequest
	GetSideOutputUrl() *string
	SetStartTime(v string) *AddCasterEpisodeGroupRequest
	GetStartTime() *string
}

type AddCasterEpisodeGroupRequest struct {
	// The callback URL.
	//
	// The URL must be a valid URL that complies with RFC 2396. The host must be a real domain name or IP address that can be resolved by DNS.
	//
	// If you query the production studio configuration by calling the [DescribeCasterConfig operation](https://help.aliyun.com/document_detail/2848011.html), check the CallbackUrl parameter value returned by the DescribeCasterConfig operation.
	//
	// This parameter is required.
	//
	// example:
	//
	// http://developer.aliyundoc.com/caster/4a82a3d1b7f0462ea37348366201****?auth_key=1608953344-0-0-53f0758162964516ac850f2ddc3f****
	CallbackUrl *string `json:"CallbackUrl,omitempty" xml:"CallbackUrl,omitempty"`
	// The request token generated by the user. This parameter is used to ensure the idempotence of the request.
	//
	// 	Notice:  This parameter value is generated by the client. Ensure that the value is unique across different requests. The maximum length is 64 ASCII characters.
	//
	// This parameter is required.
	//
	// example:
	//
	// 8751ad99-2ddb-4aac-ad44-84b21102****
	ClientToken *string `json:"ClientToken,omitempty" xml:"ClientToken,omitempty"`
	// The primary streaming domain.
	//
	// This parameter is required.
	//
	// example:
	//
	// example.com
	DomainName *string `json:"DomainName,omitempty" xml:"DomainName,omitempty"`
	// The program list.
	//
	// This parameter is required.
	Item    []*AddCasterEpisodeGroupRequestItem `json:"Item,omitempty" xml:"Item,omitempty" type:"Repeated"`
	OwnerId *int64                              `json:"OwnerId,omitempty" xml:"OwnerId,omitempty"`
	// The region ID.
	//
	// example:
	//
	// cn-shanghai
	RegionId *string `json:"RegionId,omitempty" xml:"RegionId,omitempty"`
	// The number of repetitions. Valid values:
	//
	// - **0**: no loop.
	//
	// - **-1**: infinite loop.
	//
	// This parameter is required.
	//
	// example:
	//
	// 0
	RepeatNum *int32 `json:"RepeatNum,omitempty" xml:"RepeatNum,omitempty"`
	// The ingest URL corresponding to the custom bypass output address of the production studio.
	//
	// This parameter is required.
	//
	// example:
	//
	// rtmp://guide.aliyundoc.com/caster/4a82a3d1b7f0462ea37348366201****?auth_key=1608953344-0-0-53f0758162964516ac850f2ddc3f****
	SideOutputUrl *string `json:"SideOutputUrl,omitempty" xml:"SideOutputUrl,omitempty"`
	// The start time. Format: <i>yyyy-MM-dd</i>T<i>HH:mm:ss</i>Z (UTC).
	//
	// This parameter is required.
	//
	// example:
	//
	// 2018-03-06T19:00:00Z
	StartTime *string `json:"StartTime,omitempty" xml:"StartTime,omitempty"`
}

func (s AddCasterEpisodeGroupRequest) String() string {
	return dara.Prettify(s)
}

func (s AddCasterEpisodeGroupRequest) GoString() string {
	return s.String()
}

func (s *AddCasterEpisodeGroupRequest) GetCallbackUrl() *string {
	return s.CallbackUrl
}

func (s *AddCasterEpisodeGroupRequest) GetClientToken() *string {
	return s.ClientToken
}

func (s *AddCasterEpisodeGroupRequest) GetDomainName() *string {
	return s.DomainName
}

func (s *AddCasterEpisodeGroupRequest) GetItem() []*AddCasterEpisodeGroupRequestItem {
	return s.Item
}

func (s *AddCasterEpisodeGroupRequest) GetOwnerId() *int64 {
	return s.OwnerId
}

func (s *AddCasterEpisodeGroupRequest) GetRegionId() *string {
	return s.RegionId
}

func (s *AddCasterEpisodeGroupRequest) GetRepeatNum() *int32 {
	return s.RepeatNum
}

func (s *AddCasterEpisodeGroupRequest) GetSideOutputUrl() *string {
	return s.SideOutputUrl
}

func (s *AddCasterEpisodeGroupRequest) GetStartTime() *string {
	return s.StartTime
}

func (s *AddCasterEpisodeGroupRequest) SetCallbackUrl(v string) *AddCasterEpisodeGroupRequest {
	s.CallbackUrl = &v
	return s
}

func (s *AddCasterEpisodeGroupRequest) SetClientToken(v string) *AddCasterEpisodeGroupRequest {
	s.ClientToken = &v
	return s
}

func (s *AddCasterEpisodeGroupRequest) SetDomainName(v string) *AddCasterEpisodeGroupRequest {
	s.DomainName = &v
	return s
}

func (s *AddCasterEpisodeGroupRequest) SetItem(v []*AddCasterEpisodeGroupRequestItem) *AddCasterEpisodeGroupRequest {
	s.Item = v
	return s
}

func (s *AddCasterEpisodeGroupRequest) SetOwnerId(v int64) *AddCasterEpisodeGroupRequest {
	s.OwnerId = &v
	return s
}

func (s *AddCasterEpisodeGroupRequest) SetRegionId(v string) *AddCasterEpisodeGroupRequest {
	s.RegionId = &v
	return s
}

func (s *AddCasterEpisodeGroupRequest) SetRepeatNum(v int32) *AddCasterEpisodeGroupRequest {
	s.RepeatNum = &v
	return s
}

func (s *AddCasterEpisodeGroupRequest) SetSideOutputUrl(v string) *AddCasterEpisodeGroupRequest {
	s.SideOutputUrl = &v
	return s
}

func (s *AddCasterEpisodeGroupRequest) SetStartTime(v string) *AddCasterEpisodeGroupRequest {
	s.StartTime = &v
	return s
}

func (s *AddCasterEpisodeGroupRequest) Validate() error {
	if s.Item != nil {
		for _, item := range s.Item {
			if item != nil {
				if err := item.Validate(); err != nil {
					return err
				}
			}
		}
	}
	return nil
}

type AddCasterEpisodeGroupRequestItem struct {
	// The program name.
	//
	// example:
	//
	// 节目1
	ItemName *string `json:"ItemName,omitempty" xml:"ItemName,omitempty"`
	// The video-on-demand file URL.
	//
	// If you query the video sources of a production studio by calling the [DescribeCasterVideoResources operation](https://help.aliyun.com/document_detail/2848023.html), check the VodUrl parameter value returned by the DescribeCasterVideoResources operation.
	//
	// > This parameter is used only when the resource is a file video and the video file has not been imported to the media library.<br>
	//
	// Supported formats: MP4, FLV, and TS.
	//
	// example:
	//
	// http://learn.aliyundoc.com/caster/4a82a3d1b7f0462ea37348366201****.flv?auth_key=1608953344-0-0-53f0758162964516ac850f2ddc3f****
	VodUrl *string `json:"VodUrl,omitempty" xml:"VodUrl,omitempty"`
}

func (s AddCasterEpisodeGroupRequestItem) String() string {
	return dara.Prettify(s)
}

func (s AddCasterEpisodeGroupRequestItem) GoString() string {
	return s.String()
}

func (s *AddCasterEpisodeGroupRequestItem) GetItemName() *string {
	return s.ItemName
}

func (s *AddCasterEpisodeGroupRequestItem) GetVodUrl() *string {
	return s.VodUrl
}

func (s *AddCasterEpisodeGroupRequestItem) SetItemName(v string) *AddCasterEpisodeGroupRequestItem {
	s.ItemName = &v
	return s
}

func (s *AddCasterEpisodeGroupRequestItem) SetVodUrl(v string) *AddCasterEpisodeGroupRequestItem {
	s.VodUrl = &v
	return s
}

func (s *AddCasterEpisodeGroupRequestItem) Validate() error {
	return dara.Validate(s)
}
