// This file is auto-generated, don't edit it. Thanks.
package client

import (
	"github.com/alibabacloud-go/tea/dara"
)

type iBindAuthToMachineResponseBody interface {
	dara.Model
	String() string
	GoString() string
	SetBindCount(v int32) *BindAuthToMachineResponseBody
	GetBindCount() *int32
	SetInsufficientCoreCount(v int32) *BindAuthToMachineResponseBody
	GetInsufficientCoreCount() *int32
	SetInsufficientEcsCount(v int32) *BindAuthToMachineResponseBody
	GetInsufficientEcsCount() *int32
	SetRequestId(v string) *BindAuthToMachineResponseBody
	GetRequestId() *string
	SetResultCode(v int32) *BindAuthToMachineResponseBody
	GetResultCode() *int32
	SetUnBindCount(v int32) *BindAuthToMachineResponseBody
	GetUnBindCount() *int32
}

type BindAuthToMachineResponseBody struct {
	// The number of servers that are successfully bound.
	//
	// example:
	//
	// 1
	BindCount *int32 `json:"BindCount,omitempty" xml:"BindCount,omitempty"`
	// The number of cores for which the authorization quota is insufficient.
	//
	// example:
	//
	// 1
	InsufficientCoreCount *int32 `json:"InsufficientCoreCount,omitempty" xml:"InsufficientCoreCount,omitempty"`
	// The number of servers for which the authorization quota is insufficient.
	//
	// example:
	//
	// 1
	InsufficientEcsCount *int32 `json:"InsufficientEcsCount,omitempty" xml:"InsufficientEcsCount,omitempty"`
	// The request ID, which is a unique identifier generated by Alibaba Cloud for the request. You can use this ID to troubleshoot issues.
	//
	// example:
	//
	// 23AD0BD2-8771-5647-819E-6BA51E212F80
	RequestId *string `json:"RequestId,omitempty" xml:"RequestId,omitempty"`
	// The status code of the binding result. Valid values:
	//
	// - **0**: Succeeded.
	//
	// - **1**: Parameter error.
	//
	// - **2**: Insufficient server authorization quota.
	//
	// - **3**: Insufficient server core authorization quota.
	//
	// example:
	//
	// 2
	ResultCode *int32 `json:"ResultCode,omitempty" xml:"ResultCode,omitempty"`
	// The number of servers that are successfully unbound.
	//
	// example:
	//
	// 1
	UnBindCount *int32 `json:"UnBindCount,omitempty" xml:"UnBindCount,omitempty"`
}

func (s BindAuthToMachineResponseBody) String() string {
	return dara.Prettify(s)
}

func (s BindAuthToMachineResponseBody) GoString() string {
	return s.String()
}

func (s *BindAuthToMachineResponseBody) GetBindCount() *int32 {
	return s.BindCount
}

func (s *BindAuthToMachineResponseBody) GetInsufficientCoreCount() *int32 {
	return s.InsufficientCoreCount
}

func (s *BindAuthToMachineResponseBody) GetInsufficientEcsCount() *int32 {
	return s.InsufficientEcsCount
}

func (s *BindAuthToMachineResponseBody) GetRequestId() *string {
	return s.RequestId
}

func (s *BindAuthToMachineResponseBody) GetResultCode() *int32 {
	return s.ResultCode
}

func (s *BindAuthToMachineResponseBody) GetUnBindCount() *int32 {
	return s.UnBindCount
}

func (s *BindAuthToMachineResponseBody) SetBindCount(v int32) *BindAuthToMachineResponseBody {
	s.BindCount = &v
	return s
}

func (s *BindAuthToMachineResponseBody) SetInsufficientCoreCount(v int32) *BindAuthToMachineResponseBody {
	s.InsufficientCoreCount = &v
	return s
}

func (s *BindAuthToMachineResponseBody) SetInsufficientEcsCount(v int32) *BindAuthToMachineResponseBody {
	s.InsufficientEcsCount = &v
	return s
}

func (s *BindAuthToMachineResponseBody) SetRequestId(v string) *BindAuthToMachineResponseBody {
	s.RequestId = &v
	return s
}

func (s *BindAuthToMachineResponseBody) SetResultCode(v int32) *BindAuthToMachineResponseBody {
	s.ResultCode = &v
	return s
}

func (s *BindAuthToMachineResponseBody) SetUnBindCount(v int32) *BindAuthToMachineResponseBody {
	s.UnBindCount = &v
	return s
}

func (s *BindAuthToMachineResponseBody) Validate() error {
	return dara.Validate(s)
}
