// This file is auto-generated, don't edit it. Thanks.
package client

import (
	"github.com/alibabacloud-go/tea/dara"
)

type iCreateCheckPolicyResponseBody interface {
	dara.Model
	String() string
	GoString() string
	SetCheckCustomPolicy(v *CreateCheckPolicyResponseBodyCheckCustomPolicy) *CreateCheckPolicyResponseBody
	GetCheckCustomPolicy() *CreateCheckPolicyResponseBodyCheckCustomPolicy
	SetRequestId(v string) *CreateCheckPolicyResponseBody
	GetRequestId() *string
}

type CreateCheckPolicyResponseBody struct {
	// Specific information about the added policy.
	CheckCustomPolicy *CreateCheckPolicyResponseBodyCheckCustomPolicy `json:"CheckCustomPolicy,omitempty" xml:"CheckCustomPolicy,omitempty" type:"Struct"`
	// The ID of this call request, which is a unique identifier generated by Alibaba Cloud for the request and can be used for troubleshooting and problem localization.
	//
	// example:
	//
	// CE500770-42D3-442E-9DDD-156E0F9F****
	RequestId *string `json:"RequestId,omitempty" xml:"RequestId,omitempty"`
}

func (s CreateCheckPolicyResponseBody) String() string {
	return dara.Prettify(s)
}

func (s CreateCheckPolicyResponseBody) GoString() string {
	return s.String()
}

func (s *CreateCheckPolicyResponseBody) GetCheckCustomPolicy() *CreateCheckPolicyResponseBodyCheckCustomPolicy {
	return s.CheckCustomPolicy
}

func (s *CreateCheckPolicyResponseBody) GetRequestId() *string {
	return s.RequestId
}

func (s *CreateCheckPolicyResponseBody) SetCheckCustomPolicy(v *CreateCheckPolicyResponseBodyCheckCustomPolicy) *CreateCheckPolicyResponseBody {
	s.CheckCustomPolicy = v
	return s
}

func (s *CreateCheckPolicyResponseBody) SetRequestId(v string) *CreateCheckPolicyResponseBody {
	s.RequestId = &v
	return s
}

func (s *CreateCheckPolicyResponseBody) Validate() error {
	if s.CheckCustomPolicy != nil {
		if err := s.CheckCustomPolicy.Validate(); err != nil {
			return err
		}
	}
	return nil
}

type CreateCheckPolicyResponseBodyCheckCustomPolicy struct {
	// The type of the policy (indicating whether it is a system or user-defined policy):
	//
	// - **CUSTOM**: User-defined.
	//
	// - **SYSTEM**: System-predefined.
	//
	// example:
	//
	// CUSTOM
	CheckType *string `json:"CheckType,omitempty" xml:"CheckType,omitempty"`
	// The ID of the custom policy.
	//
	// example:
	//
	// 1062**
	PolicyId *int64 `json:"PolicyId,omitempty" xml:"PolicyId,omitempty"`
	// The name of the custom policy.
	//
	// example:
	//
	// TestPolicyName
	PolicyShowName *string `json:"PolicyShowName,omitempty" xml:"PolicyShowName,omitempty"`
	// The policy type for custom check rules:
	//
	// - **STANDARD**: Standard policy type.
	//
	// - **REQUIREMENT**: Requirement policy type.
	//
	// - **SECTION**: Section policy type.
	//
	// example:
	//
	// STANDARD
	PolicyType *string `json:"PolicyType,omitempty" xml:"PolicyType,omitempty"`
	// The name of the associated major policy category:
	//
	// - **AISPM**: AI Configuration Management (AISPM).
	//
	// - **KISPM**: Kubernetes Configuration Management (KSPM).
	//
	// - **IDENTITY_PERMISSION**: Identity and Permission Management (CIEM).
	//
	// - **RISK**: Security Risk.
	//
	// - **COMPLIANCE**: Compliance Risk.
	//
	// example:
	//
	// AISPM
	Type *string `json:"Type,omitempty" xml:"Type,omitempty"`
}

func (s CreateCheckPolicyResponseBodyCheckCustomPolicy) String() string {
	return dara.Prettify(s)
}

func (s CreateCheckPolicyResponseBodyCheckCustomPolicy) GoString() string {
	return s.String()
}

func (s *CreateCheckPolicyResponseBodyCheckCustomPolicy) GetCheckType() *string {
	return s.CheckType
}

func (s *CreateCheckPolicyResponseBodyCheckCustomPolicy) GetPolicyId() *int64 {
	return s.PolicyId
}

func (s *CreateCheckPolicyResponseBodyCheckCustomPolicy) GetPolicyShowName() *string {
	return s.PolicyShowName
}

func (s *CreateCheckPolicyResponseBodyCheckCustomPolicy) GetPolicyType() *string {
	return s.PolicyType
}

func (s *CreateCheckPolicyResponseBodyCheckCustomPolicy) GetType() *string {
	return s.Type
}

func (s *CreateCheckPolicyResponseBodyCheckCustomPolicy) SetCheckType(v string) *CreateCheckPolicyResponseBodyCheckCustomPolicy {
	s.CheckType = &v
	return s
}

func (s *CreateCheckPolicyResponseBodyCheckCustomPolicy) SetPolicyId(v int64) *CreateCheckPolicyResponseBodyCheckCustomPolicy {
	s.PolicyId = &v
	return s
}

func (s *CreateCheckPolicyResponseBodyCheckCustomPolicy) SetPolicyShowName(v string) *CreateCheckPolicyResponseBodyCheckCustomPolicy {
	s.PolicyShowName = &v
	return s
}

func (s *CreateCheckPolicyResponseBodyCheckCustomPolicy) SetPolicyType(v string) *CreateCheckPolicyResponseBodyCheckCustomPolicy {
	s.PolicyType = &v
	return s
}

func (s *CreateCheckPolicyResponseBodyCheckCustomPolicy) SetType(v string) *CreateCheckPolicyResponseBodyCheckCustomPolicy {
	s.Type = &v
	return s
}

func (s *CreateCheckPolicyResponseBodyCheckCustomPolicy) Validate() error {
	return dara.Validate(s)
}
