// This file is auto-generated, don't edit it. Thanks.
package client

import (
	"github.com/alibabacloud-go/tea/dara"
)

type iDescribeSyncAssetTaskLogDetailResponseBody interface {
	dara.Model
	String() string
	GoString() string
	SetPageInfo(v *DescribeSyncAssetTaskLogDetailResponseBodyPageInfo) *DescribeSyncAssetTaskLogDetailResponseBody
	GetPageInfo() *DescribeSyncAssetTaskLogDetailResponseBodyPageInfo
	SetRequestId(v string) *DescribeSyncAssetTaskLogDetailResponseBody
	GetRequestId() *string
	SetTaskRecordDetails(v []*DescribeSyncAssetTaskLogDetailResponseBodyTaskRecordDetails) *DescribeSyncAssetTaskLogDetailResponseBody
	GetTaskRecordDetails() []*DescribeSyncAssetTaskLogDetailResponseBodyTaskRecordDetails
}

type DescribeSyncAssetTaskLogDetailResponseBody struct {
	// The pagination information.
	PageInfo *DescribeSyncAssetTaskLogDetailResponseBodyPageInfo `json:"PageInfo,omitempty" xml:"PageInfo,omitempty" type:"Struct"`
	// The request ID, which is a unique identifier generated by Alibaba Cloud for the request. You can use it to troubleshoot issues.
	//
	// example:
	//
	// 0B48AB3C-84FC-424D-A01D-B9270EF46038
	RequestId *string `json:"RequestId,omitempty" xml:"RequestId,omitempty"`
	// The list of task details.
	TaskRecordDetails []*DescribeSyncAssetTaskLogDetailResponseBodyTaskRecordDetails `json:"TaskRecordDetails,omitempty" xml:"TaskRecordDetails,omitempty" type:"Repeated"`
}

func (s DescribeSyncAssetTaskLogDetailResponseBody) String() string {
	return dara.Prettify(s)
}

func (s DescribeSyncAssetTaskLogDetailResponseBody) GoString() string {
	return s.String()
}

func (s *DescribeSyncAssetTaskLogDetailResponseBody) GetPageInfo() *DescribeSyncAssetTaskLogDetailResponseBodyPageInfo {
	return s.PageInfo
}

func (s *DescribeSyncAssetTaskLogDetailResponseBody) GetRequestId() *string {
	return s.RequestId
}

func (s *DescribeSyncAssetTaskLogDetailResponseBody) GetTaskRecordDetails() []*DescribeSyncAssetTaskLogDetailResponseBodyTaskRecordDetails {
	return s.TaskRecordDetails
}

func (s *DescribeSyncAssetTaskLogDetailResponseBody) SetPageInfo(v *DescribeSyncAssetTaskLogDetailResponseBodyPageInfo) *DescribeSyncAssetTaskLogDetailResponseBody {
	s.PageInfo = v
	return s
}

func (s *DescribeSyncAssetTaskLogDetailResponseBody) SetRequestId(v string) *DescribeSyncAssetTaskLogDetailResponseBody {
	s.RequestId = &v
	return s
}

func (s *DescribeSyncAssetTaskLogDetailResponseBody) SetTaskRecordDetails(v []*DescribeSyncAssetTaskLogDetailResponseBodyTaskRecordDetails) *DescribeSyncAssetTaskLogDetailResponseBody {
	s.TaskRecordDetails = v
	return s
}

func (s *DescribeSyncAssetTaskLogDetailResponseBody) Validate() error {
	if s.PageInfo != nil {
		if err := s.PageInfo.Validate(); err != nil {
			return err
		}
	}
	if s.TaskRecordDetails != nil {
		for _, item := range s.TaskRecordDetails {
			if item != nil {
				if err := item.Validate(); err != nil {
					return err
				}
			}
		}
	}
	return nil
}

type DescribeSyncAssetTaskLogDetailResponseBodyPageInfo struct {
	// The number of IDC scan task detail entries displayed on the current page.
	//
	// example:
	//
	// 4
	Count *int32 `json:"Count,omitempty" xml:"Count,omitempty"`
	// The page number of the current page in a paginated query.
	//
	// example:
	//
	// 1
	CurrentPage *int32 `json:"CurrentPage,omitempty" xml:"CurrentPage,omitempty"`
	// The number of IDC scan task details displayed on each page in a paginated query. Default value: 20, which indicates that up to 20 entries of IDC scan task details are displayed on each page.
	//
	// example:
	//
	// 20
	PageSize *int32 `json:"PageSize,omitempty" xml:"PageSize,omitempty"`
	// The total number of detail entries for the IDC scan task.
	//
	// example:
	//
	// 12
	TotalCount *int32 `json:"TotalCount,omitempty" xml:"TotalCount,omitempty"`
}

func (s DescribeSyncAssetTaskLogDetailResponseBodyPageInfo) String() string {
	return dara.Prettify(s)
}

func (s DescribeSyncAssetTaskLogDetailResponseBodyPageInfo) GoString() string {
	return s.String()
}

func (s *DescribeSyncAssetTaskLogDetailResponseBodyPageInfo) GetCount() *int32 {
	return s.Count
}

func (s *DescribeSyncAssetTaskLogDetailResponseBodyPageInfo) GetCurrentPage() *int32 {
	return s.CurrentPage
}

func (s *DescribeSyncAssetTaskLogDetailResponseBodyPageInfo) GetPageSize() *int32 {
	return s.PageSize
}

func (s *DescribeSyncAssetTaskLogDetailResponseBodyPageInfo) GetTotalCount() *int32 {
	return s.TotalCount
}

func (s *DescribeSyncAssetTaskLogDetailResponseBodyPageInfo) SetCount(v int32) *DescribeSyncAssetTaskLogDetailResponseBodyPageInfo {
	s.Count = &v
	return s
}

func (s *DescribeSyncAssetTaskLogDetailResponseBodyPageInfo) SetCurrentPage(v int32) *DescribeSyncAssetTaskLogDetailResponseBodyPageInfo {
	s.CurrentPage = &v
	return s
}

func (s *DescribeSyncAssetTaskLogDetailResponseBodyPageInfo) SetPageSize(v int32) *DescribeSyncAssetTaskLogDetailResponseBodyPageInfo {
	s.PageSize = &v
	return s
}

func (s *DescribeSyncAssetTaskLogDetailResponseBodyPageInfo) SetTotalCount(v int32) *DescribeSyncAssetTaskLogDetailResponseBodyPageInfo {
	s.TotalCount = &v
	return s
}

func (s *DescribeSyncAssetTaskLogDetailResponseBodyPageInfo) Validate() error {
	return dara.Validate(s)
}

type DescribeSyncAssetTaskLogDetailResponseBodyTaskRecordDetails struct {
	// The total number of assets.
	//
	// example:
	//
	// 5
	AssetCount *int32 `json:"AssetCount,omitempty" xml:"AssetCount,omitempty"`
	// The region where the IDC server is located.
	//
	// example:
	//
	// 浙江杭州
	IdcRegion *string `json:"IdcRegion,omitempty" xml:"IdcRegion,omitempty"`
	// The task ID.
	//
	// example:
	//
	// 6c4e4c36ffc3e5919120b405c2b3****
	LeafTaskId *string `json:"LeafTaskId,omitempty" xml:"LeafTaskId,omitempty"`
	// The status. Valid values:
	//
	// - **INIT**: pending start
	//
	// - **START**: started
	//
	// - **MESSAGE_SEND**: instructions delivered
	//
	// - **SUCCESS**: completed
	//
	// - **FAIL**: failed
	//
	// - **TIMEOUT**: timed out
	//
	// example:
	//
	// INIT
	LeafTaskStatus *string `json:"LeafTaskStatus,omitempty" xml:"LeafTaskStatus,omitempty"`
	// The task description.
	//
	// example:
	//
	// unknown reason
	TaskMsg *string `json:"TaskMsg,omitempty" xml:"TaskMsg,omitempty"`
	// The timestamp of the report time.
	//
	// example:
	//
	// 1671614217000
	TaskReportTime *int64 `json:"TaskReportTime,omitempty" xml:"TaskReportTime,omitempty"`
	// The number of unprotected assets.
	//
	// example:
	//
	// 0
	UnprotectedAssetCount *int32 `json:"UnprotectedAssetCount,omitempty" xml:"UnprotectedAssetCount,omitempty"`
}

func (s DescribeSyncAssetTaskLogDetailResponseBodyTaskRecordDetails) String() string {
	return dara.Prettify(s)
}

func (s DescribeSyncAssetTaskLogDetailResponseBodyTaskRecordDetails) GoString() string {
	return s.String()
}

func (s *DescribeSyncAssetTaskLogDetailResponseBodyTaskRecordDetails) GetAssetCount() *int32 {
	return s.AssetCount
}

func (s *DescribeSyncAssetTaskLogDetailResponseBodyTaskRecordDetails) GetIdcRegion() *string {
	return s.IdcRegion
}

func (s *DescribeSyncAssetTaskLogDetailResponseBodyTaskRecordDetails) GetLeafTaskId() *string {
	return s.LeafTaskId
}

func (s *DescribeSyncAssetTaskLogDetailResponseBodyTaskRecordDetails) GetLeafTaskStatus() *string {
	return s.LeafTaskStatus
}

func (s *DescribeSyncAssetTaskLogDetailResponseBodyTaskRecordDetails) GetTaskMsg() *string {
	return s.TaskMsg
}

func (s *DescribeSyncAssetTaskLogDetailResponseBodyTaskRecordDetails) GetTaskReportTime() *int64 {
	return s.TaskReportTime
}

func (s *DescribeSyncAssetTaskLogDetailResponseBodyTaskRecordDetails) GetUnprotectedAssetCount() *int32 {
	return s.UnprotectedAssetCount
}

func (s *DescribeSyncAssetTaskLogDetailResponseBodyTaskRecordDetails) SetAssetCount(v int32) *DescribeSyncAssetTaskLogDetailResponseBodyTaskRecordDetails {
	s.AssetCount = &v
	return s
}

func (s *DescribeSyncAssetTaskLogDetailResponseBodyTaskRecordDetails) SetIdcRegion(v string) *DescribeSyncAssetTaskLogDetailResponseBodyTaskRecordDetails {
	s.IdcRegion = &v
	return s
}

func (s *DescribeSyncAssetTaskLogDetailResponseBodyTaskRecordDetails) SetLeafTaskId(v string) *DescribeSyncAssetTaskLogDetailResponseBodyTaskRecordDetails {
	s.LeafTaskId = &v
	return s
}

func (s *DescribeSyncAssetTaskLogDetailResponseBodyTaskRecordDetails) SetLeafTaskStatus(v string) *DescribeSyncAssetTaskLogDetailResponseBodyTaskRecordDetails {
	s.LeafTaskStatus = &v
	return s
}

func (s *DescribeSyncAssetTaskLogDetailResponseBodyTaskRecordDetails) SetTaskMsg(v string) *DescribeSyncAssetTaskLogDetailResponseBodyTaskRecordDetails {
	s.TaskMsg = &v
	return s
}

func (s *DescribeSyncAssetTaskLogDetailResponseBodyTaskRecordDetails) SetTaskReportTime(v int64) *DescribeSyncAssetTaskLogDetailResponseBodyTaskRecordDetails {
	s.TaskReportTime = &v
	return s
}

func (s *DescribeSyncAssetTaskLogDetailResponseBodyTaskRecordDetails) SetUnprotectedAssetCount(v int32) *DescribeSyncAssetTaskLogDetailResponseBodyTaskRecordDetails {
	s.UnprotectedAssetCount = &v
	return s
}

func (s *DescribeSyncAssetTaskLogDetailResponseBodyTaskRecordDetails) Validate() error {
	return dara.Validate(s)
}
