// This file is auto-generated, don't edit it. Thanks.
package client

import (
	"github.com/alibabacloud-go/tea/dara"
)

type iGetValidDeductInstancesResponseBody interface {
	dara.Model
	String() string
	GoString() string
	SetData(v *GetValidDeductInstancesResponseBodyData) *GetValidDeductInstancesResponseBody
	GetData() *GetValidDeductInstancesResponseBodyData
	SetRequestId(v string) *GetValidDeductInstancesResponseBody
	GetRequestId() *string
}

type GetValidDeductInstancesResponseBody struct {
	// Returned data.
	Data *GetValidDeductInstancesResponseBodyData `json:"Data,omitempty" xml:"Data,omitempty" type:"Struct"`
	// The ID of this call request, a unique identifier generated by Alibaba Cloud for the request, which can be used to troubleshoot and locate issues.
	//
	// example:
	//
	// 6D56A5C4-9C78-5EB1-9246-60B7FAECA1D5
	RequestId *string `json:"RequestId,omitempty" xml:"RequestId,omitempty"`
}

func (s GetValidDeductInstancesResponseBody) String() string {
	return dara.Prettify(s)
}

func (s GetValidDeductInstancesResponseBody) GoString() string {
	return s.String()
}

func (s *GetValidDeductInstancesResponseBody) GetData() *GetValidDeductInstancesResponseBodyData {
	return s.Data
}

func (s *GetValidDeductInstancesResponseBody) GetRequestId() *string {
	return s.RequestId
}

func (s *GetValidDeductInstancesResponseBody) SetData(v *GetValidDeductInstancesResponseBodyData) *GetValidDeductInstancesResponseBody {
	s.Data = v
	return s
}

func (s *GetValidDeductInstancesResponseBody) SetRequestId(v string) *GetValidDeductInstancesResponseBody {
	s.RequestId = &v
	return s
}

func (s *GetValidDeductInstancesResponseBody) Validate() error {
	if s.Data != nil {
		if err := s.Data.Validate(); err != nil {
			return err
		}
	}
	return nil
}

type GetValidDeductInstancesResponseBodyData struct {
	// Whether eligible for trial. Values:
	//
	// - **true**: Eligible
	//
	// - **false**: Not eligible
	//
	// example:
	//
	// true
	CanTry *bool `json:"CanTry,omitempty" xml:"CanTry,omitempty"`
	// List of resource package usage details.
	DeductPackageList []*GetValidDeductInstancesResponseBodyDataDeductPackageList `json:"DeductPackageList,omitempty" xml:"DeductPackageList,omitempty" type:"Repeated"`
}

func (s GetValidDeductInstancesResponseBodyData) String() string {
	return dara.Prettify(s)
}

func (s GetValidDeductInstancesResponseBodyData) GoString() string {
	return s.String()
}

func (s *GetValidDeductInstancesResponseBodyData) GetCanTry() *bool {
	return s.CanTry
}

func (s *GetValidDeductInstancesResponseBodyData) GetDeductPackageList() []*GetValidDeductInstancesResponseBodyDataDeductPackageList {
	return s.DeductPackageList
}

func (s *GetValidDeductInstancesResponseBodyData) SetCanTry(v bool) *GetValidDeductInstancesResponseBodyData {
	s.CanTry = &v
	return s
}

func (s *GetValidDeductInstancesResponseBodyData) SetDeductPackageList(v []*GetValidDeductInstancesResponseBodyDataDeductPackageList) *GetValidDeductInstancesResponseBodyData {
	s.DeductPackageList = v
	return s
}

func (s *GetValidDeductInstancesResponseBodyData) Validate() error {
	if s.DeductPackageList != nil {
		for _, item := range s.DeductPackageList {
			if item != nil {
				if err := item.Validate(); err != nil {
					return err
				}
			}
		}
	}
	return nil
}

type GetValidDeductInstancesResponseBodyDataDeductPackageList struct {
	// Authorized consumption in the current billing cycle.
	//
	// example:
	//
	// 10
	CurrentPeriodUsed *int64 `json:"CurrentPeriodUsed,omitempty" xml:"CurrentPeriodUsed,omitempty"`
	// End time.
	//
	// example:
	//
	// 1737734400000
	EndTime *int64 `json:"EndTime,omitempty" xml:"EndTime,omitempty"`
	// Total amount of the resource package.
	//
	// example:
	//
	// 1000
	InitCapacity *float64 `json:"InitCapacity,omitempty" xml:"InitCapacity,omitempty"`
	// Resource package instance ID.
	//
	// example:
	//
	// sas_**_dp_cn-2***
	InstanceId *string `json:"InstanceId,omitempty" xml:"InstanceId,omitempty"`
	// Module code. Values:
	//
	// - **POST_HOST**: Host and container protection
	//
	// - **CSPM**: Cloud product configuration check
	//
	// - **VUL**: Vulnerability scan
	//
	// example:
	//
	// POST_HOST
	Module *string `json:"Module,omitempty" xml:"Module,omitempty"`
	// Authorized consumption up to the previous billing cycle.
	//
	// example:
	//
	// 100
	PeriodCapacity *float64 `json:"PeriodCapacity,omitempty" xml:"PeriodCapacity,omitempty"`
	// Start timestamp (milliseconds).
	//
	// example:
	//
	// 1737734400000
	StartTime *int64 `json:"StartTime,omitempty" xml:"StartTime,omitempty"`
	// Resource package status. Values:
	//
	// - **valid**: Valid
	//
	// - **invalid**: Invalid
	//
	// example:
	//
	// Available
	Status *string `json:"Status,omitempty" xml:"Status,omitempty"`
}

func (s GetValidDeductInstancesResponseBodyDataDeductPackageList) String() string {
	return dara.Prettify(s)
}

func (s GetValidDeductInstancesResponseBodyDataDeductPackageList) GoString() string {
	return s.String()
}

func (s *GetValidDeductInstancesResponseBodyDataDeductPackageList) GetCurrentPeriodUsed() *int64 {
	return s.CurrentPeriodUsed
}

func (s *GetValidDeductInstancesResponseBodyDataDeductPackageList) GetEndTime() *int64 {
	return s.EndTime
}

func (s *GetValidDeductInstancesResponseBodyDataDeductPackageList) GetInitCapacity() *float64 {
	return s.InitCapacity
}

func (s *GetValidDeductInstancesResponseBodyDataDeductPackageList) GetInstanceId() *string {
	return s.InstanceId
}

func (s *GetValidDeductInstancesResponseBodyDataDeductPackageList) GetModule() *string {
	return s.Module
}

func (s *GetValidDeductInstancesResponseBodyDataDeductPackageList) GetPeriodCapacity() *float64 {
	return s.PeriodCapacity
}

func (s *GetValidDeductInstancesResponseBodyDataDeductPackageList) GetStartTime() *int64 {
	return s.StartTime
}

func (s *GetValidDeductInstancesResponseBodyDataDeductPackageList) GetStatus() *string {
	return s.Status
}

func (s *GetValidDeductInstancesResponseBodyDataDeductPackageList) SetCurrentPeriodUsed(v int64) *GetValidDeductInstancesResponseBodyDataDeductPackageList {
	s.CurrentPeriodUsed = &v
	return s
}

func (s *GetValidDeductInstancesResponseBodyDataDeductPackageList) SetEndTime(v int64) *GetValidDeductInstancesResponseBodyDataDeductPackageList {
	s.EndTime = &v
	return s
}

func (s *GetValidDeductInstancesResponseBodyDataDeductPackageList) SetInitCapacity(v float64) *GetValidDeductInstancesResponseBodyDataDeductPackageList {
	s.InitCapacity = &v
	return s
}

func (s *GetValidDeductInstancesResponseBodyDataDeductPackageList) SetInstanceId(v string) *GetValidDeductInstancesResponseBodyDataDeductPackageList {
	s.InstanceId = &v
	return s
}

func (s *GetValidDeductInstancesResponseBodyDataDeductPackageList) SetModule(v string) *GetValidDeductInstancesResponseBodyDataDeductPackageList {
	s.Module = &v
	return s
}

func (s *GetValidDeductInstancesResponseBodyDataDeductPackageList) SetPeriodCapacity(v float64) *GetValidDeductInstancesResponseBodyDataDeductPackageList {
	s.PeriodCapacity = &v
	return s
}

func (s *GetValidDeductInstancesResponseBodyDataDeductPackageList) SetStartTime(v int64) *GetValidDeductInstancesResponseBodyDataDeductPackageList {
	s.StartTime = &v
	return s
}

func (s *GetValidDeductInstancesResponseBodyDataDeductPackageList) SetStatus(v string) *GetValidDeductInstancesResponseBodyDataDeductPackageList {
	s.Status = &v
	return s
}

func (s *GetValidDeductInstancesResponseBodyDataDeductPackageList) Validate() error {
	return dara.Validate(s)
}
