// This file is auto-generated, don't edit it. Thanks.
package client

import (
	"github.com/alibabacloud-go/tea/dara"
)

type iGetAegisContainerPluginRuleCriteriaResponseBody interface {
	dara.Model
	String() string
	GoString() string
	SetCriteriaList(v []*GetAegisContainerPluginRuleCriteriaResponseBodyCriteriaList) *GetAegisContainerPluginRuleCriteriaResponseBody
	GetCriteriaList() []*GetAegisContainerPluginRuleCriteriaResponseBodyCriteriaList
	SetRequestId(v string) *GetAegisContainerPluginRuleCriteriaResponseBody
	GetRequestId() *string
}

type GetAegisContainerPluginRuleCriteriaResponseBody struct {
	// The supported search criteria information.
	CriteriaList []*GetAegisContainerPluginRuleCriteriaResponseBodyCriteriaList `json:"CriteriaList,omitempty" xml:"CriteriaList,omitempty" type:"Repeated"`
	// The unique identifier generated by Alibaba Cloud for the request.
	//
	// example:
	//
	// DA8133CC-CCA0-5CF2-BF64-FE7D52C44***
	RequestId *string `json:"RequestId,omitempty" xml:"RequestId,omitempty"`
}

func (s GetAegisContainerPluginRuleCriteriaResponseBody) String() string {
	return dara.Prettify(s)
}

func (s GetAegisContainerPluginRuleCriteriaResponseBody) GoString() string {
	return s.String()
}

func (s *GetAegisContainerPluginRuleCriteriaResponseBody) GetCriteriaList() []*GetAegisContainerPluginRuleCriteriaResponseBodyCriteriaList {
	return s.CriteriaList
}

func (s *GetAegisContainerPluginRuleCriteriaResponseBody) GetRequestId() *string {
	return s.RequestId
}

func (s *GetAegisContainerPluginRuleCriteriaResponseBody) SetCriteriaList(v []*GetAegisContainerPluginRuleCriteriaResponseBodyCriteriaList) *GetAegisContainerPluginRuleCriteriaResponseBody {
	s.CriteriaList = v
	return s
}

func (s *GetAegisContainerPluginRuleCriteriaResponseBody) SetRequestId(v string) *GetAegisContainerPluginRuleCriteriaResponseBody {
	s.RequestId = &v
	return s
}

func (s *GetAegisContainerPluginRuleCriteriaResponseBody) Validate() error {
	if s.CriteriaList != nil {
		for _, item := range s.CriteriaList {
			if item != nil {
				if err := item.Validate(); err != nil {
					return err
				}
			}
		}
	}
	return nil
}

type GetAegisContainerPluginRuleCriteriaResponseBodyCriteriaList struct {
	// The name of the corresponding query condition.
	//
	// - **instanceId**: The container instance ID.
	//
	// - **clusterId**: The cluster ID.
	//
	// - **regionId**: The container region.
	//
	// - **clusterName**: The cluster name.
	//
	// - **clusterType**: The cluster type.
	//
	// - **hostIp**: The public IP address.
	//
	// - **pod**: The pod.
	//
	// - **podIp**: The pod IP address.
	//
	// - **containerId**: The container ID.
	//
	// - **containerScope**: The container type.
	//
	// example:
	//
	// containerScope
	Name *string `json:"Name,omitempty" xml:"Name,omitempty"`
	// The type of query condition. Valid values:
	//
	// - **input**: You must manually enter the query field.
	//
	// - **select**: You must select a subtype of the query condition from the drop-down list.
	//
	// example:
	//
	// select
	Type *string `json:"Type,omitempty" xml:"Type,omitempty"`
	// The list of values.
	//
	// example:
	//
	// NO,YES
	Values *string `json:"Values,omitempty" xml:"Values,omitempty"`
}

func (s GetAegisContainerPluginRuleCriteriaResponseBodyCriteriaList) String() string {
	return dara.Prettify(s)
}

func (s GetAegisContainerPluginRuleCriteriaResponseBodyCriteriaList) GoString() string {
	return s.String()
}

func (s *GetAegisContainerPluginRuleCriteriaResponseBodyCriteriaList) GetName() *string {
	return s.Name
}

func (s *GetAegisContainerPluginRuleCriteriaResponseBodyCriteriaList) GetType() *string {
	return s.Type
}

func (s *GetAegisContainerPluginRuleCriteriaResponseBodyCriteriaList) GetValues() *string {
	return s.Values
}

func (s *GetAegisContainerPluginRuleCriteriaResponseBodyCriteriaList) SetName(v string) *GetAegisContainerPluginRuleCriteriaResponseBodyCriteriaList {
	s.Name = &v
	return s
}

func (s *GetAegisContainerPluginRuleCriteriaResponseBodyCriteriaList) SetType(v string) *GetAegisContainerPluginRuleCriteriaResponseBodyCriteriaList {
	s.Type = &v
	return s
}

func (s *GetAegisContainerPluginRuleCriteriaResponseBodyCriteriaList) SetValues(v string) *GetAegisContainerPluginRuleCriteriaResponseBodyCriteriaList {
	s.Values = &v
	return s
}

func (s *GetAegisContainerPluginRuleCriteriaResponseBodyCriteriaList) Validate() error {
	return dara.Validate(s)
}
