// This file is auto-generated, don't edit it. Thanks.
package client

import (
	"github.com/alibabacloud-go/tea/dara"
)

type iGetServerlessAppAuthDetailResponseBody interface {
	dara.Model
	String() string
	GoString() string
	SetData(v *GetServerlessAppAuthDetailResponseBodyData) *GetServerlessAppAuthDetailResponseBody
	GetData() *GetServerlessAppAuthDetailResponseBodyData
	SetRequestId(v string) *GetServerlessAppAuthDetailResponseBody
	GetRequestId() *string
	SetSuccess(v bool) *GetServerlessAppAuthDetailResponseBody
	GetSuccess() *bool
}

type GetServerlessAppAuthDetailResponseBody struct {
	// Data details.
	Data *GetServerlessAppAuthDetailResponseBodyData `json:"Data,omitempty" xml:"Data,omitempty" type:"Struct"`
	// The ID of this call request, a unique identifier generated by Alibaba Cloud for the request, which can be used to troubleshoot and pinpoint issues.
	//
	// example:
	//
	// 30CBF632-109F-596F-97F2-451C8B2A****
	RequestId *string `json:"RequestId,omitempty" xml:"RequestId,omitempty"`
	// Whether the API call was successful. Values:
	//
	// - **true**: Success
	//
	// - **false**: Failure
	//
	// example:
	//
	// true
	Success *bool `json:"Success,omitempty" xml:"Success,omitempty"`
}

func (s GetServerlessAppAuthDetailResponseBody) String() string {
	return dara.Prettify(s)
}

func (s GetServerlessAppAuthDetailResponseBody) GoString() string {
	return s.String()
}

func (s *GetServerlessAppAuthDetailResponseBody) GetData() *GetServerlessAppAuthDetailResponseBodyData {
	return s.Data
}

func (s *GetServerlessAppAuthDetailResponseBody) GetRequestId() *string {
	return s.RequestId
}

func (s *GetServerlessAppAuthDetailResponseBody) GetSuccess() *bool {
	return s.Success
}

func (s *GetServerlessAppAuthDetailResponseBody) SetData(v *GetServerlessAppAuthDetailResponseBodyData) *GetServerlessAppAuthDetailResponseBody {
	s.Data = v
	return s
}

func (s *GetServerlessAppAuthDetailResponseBody) SetRequestId(v string) *GetServerlessAppAuthDetailResponseBody {
	s.RequestId = &v
	return s
}

func (s *GetServerlessAppAuthDetailResponseBody) SetSuccess(v bool) *GetServerlessAppAuthDetailResponseBody {
	s.Success = &v
	return s
}

func (s *GetServerlessAppAuthDetailResponseBody) Validate() error {
	if s.Data != nil {
		if err := s.Data.Validate(); err != nil {
			return err
		}
	}
	return nil
}

type GetServerlessAppAuthDetailResponseBodyData struct {
	// Application ID.
	//
	// example:
	//
	// c932b7a0***
	AppId *string `json:"AppId,omitempty" xml:"AppId,omitempty"`
	// Number of CPU cores.
	//
	// example:
	//
	// 2
	CoreCount *int32 `json:"CoreCount,omitempty" xml:"CoreCount,omitempty"`
	// Number of instances.
	//
	// example:
	//
	// 1
	InstanceCount *int32 `json:"InstanceCount,omitempty" xml:"InstanceCount,omitempty"`
	// Whether authorization is bound. Values:
	//
	// - **true**: Yes
	//
	// - **false**: No
	//
	// example:
	//
	// true
	IsBind *bool `json:"IsBind,omitempty" xml:"IsBind,omitempty"`
	// Whether it is a post-paid instance. Values:
	//
	// - **true**: Yes
	//
	// - **false**: No
	//
	// example:
	//
	// true
	IsPostPaid *bool `json:"IsPostPaid,omitempty" xml:"IsPostPaid,omitempty"`
	// Serverless post-paid status. Values:
	//
	// - **true**: Active
	//
	// - **false**: Expired
	//
	// example:
	//
	// true
	IsServerlessPostPaidValid *bool `json:"IsServerlessPostPaidValid,omitempty" xml:"IsServerlessPostPaidValid,omitempty"`
	// Pay-as-you-go module switch. Values:
	//
	// - **VUL**: Vulnerability repair module
	//
	// - **CSPM**: Cloud Security Posture Management module
	//
	// - **AGENTLESS**: Agentless detection module
	//
	// - **SERVERLESS**: Serverless security module
	//
	// - **CTDR**: Threat Detection and Response module
	//
	// example:
	//
	// SERVERLESS
	PostPaidModuleSwitch *string `json:"PostPaidModuleSwitch,omitempty" xml:"PostPaidModuleSwitch,omitempty"`
	// Post-paid activation time.
	//
	// example:
	//
	// 1655432638000
	PostPaidOpenTime *int64 `json:"PostPaidOpenTime,omitempty" xml:"PostPaidOpenTime,omitempty"`
	// Post-paid instance status. Values:
	//
	// - **1**: Active
	//
	// - **2**: Suspended due to unpaid bills
	//
	// example:
	//
	// 1
	PostPaidStatus *int32 `json:"PostPaidStatus,omitempty" xml:"PostPaidStatus,omitempty"`
	// Post-paid instance ID.
	//
	// example:
	//
	// 101
	PostpaidInstanceId *string `json:"PostpaidInstanceId,omitempty" xml:"PostpaidInstanceId,omitempty"`
}

func (s GetServerlessAppAuthDetailResponseBodyData) String() string {
	return dara.Prettify(s)
}

func (s GetServerlessAppAuthDetailResponseBodyData) GoString() string {
	return s.String()
}

func (s *GetServerlessAppAuthDetailResponseBodyData) GetAppId() *string {
	return s.AppId
}

func (s *GetServerlessAppAuthDetailResponseBodyData) GetCoreCount() *int32 {
	return s.CoreCount
}

func (s *GetServerlessAppAuthDetailResponseBodyData) GetInstanceCount() *int32 {
	return s.InstanceCount
}

func (s *GetServerlessAppAuthDetailResponseBodyData) GetIsBind() *bool {
	return s.IsBind
}

func (s *GetServerlessAppAuthDetailResponseBodyData) GetIsPostPaid() *bool {
	return s.IsPostPaid
}

func (s *GetServerlessAppAuthDetailResponseBodyData) GetIsServerlessPostPaidValid() *bool {
	return s.IsServerlessPostPaidValid
}

func (s *GetServerlessAppAuthDetailResponseBodyData) GetPostPaidModuleSwitch() *string {
	return s.PostPaidModuleSwitch
}

func (s *GetServerlessAppAuthDetailResponseBodyData) GetPostPaidOpenTime() *int64 {
	return s.PostPaidOpenTime
}

func (s *GetServerlessAppAuthDetailResponseBodyData) GetPostPaidStatus() *int32 {
	return s.PostPaidStatus
}

func (s *GetServerlessAppAuthDetailResponseBodyData) GetPostpaidInstanceId() *string {
	return s.PostpaidInstanceId
}

func (s *GetServerlessAppAuthDetailResponseBodyData) SetAppId(v string) *GetServerlessAppAuthDetailResponseBodyData {
	s.AppId = &v
	return s
}

func (s *GetServerlessAppAuthDetailResponseBodyData) SetCoreCount(v int32) *GetServerlessAppAuthDetailResponseBodyData {
	s.CoreCount = &v
	return s
}

func (s *GetServerlessAppAuthDetailResponseBodyData) SetInstanceCount(v int32) *GetServerlessAppAuthDetailResponseBodyData {
	s.InstanceCount = &v
	return s
}

func (s *GetServerlessAppAuthDetailResponseBodyData) SetIsBind(v bool) *GetServerlessAppAuthDetailResponseBodyData {
	s.IsBind = &v
	return s
}

func (s *GetServerlessAppAuthDetailResponseBodyData) SetIsPostPaid(v bool) *GetServerlessAppAuthDetailResponseBodyData {
	s.IsPostPaid = &v
	return s
}

func (s *GetServerlessAppAuthDetailResponseBodyData) SetIsServerlessPostPaidValid(v bool) *GetServerlessAppAuthDetailResponseBodyData {
	s.IsServerlessPostPaidValid = &v
	return s
}

func (s *GetServerlessAppAuthDetailResponseBodyData) SetPostPaidModuleSwitch(v string) *GetServerlessAppAuthDetailResponseBodyData {
	s.PostPaidModuleSwitch = &v
	return s
}

func (s *GetServerlessAppAuthDetailResponseBodyData) SetPostPaidOpenTime(v int64) *GetServerlessAppAuthDetailResponseBodyData {
	s.PostPaidOpenTime = &v
	return s
}

func (s *GetServerlessAppAuthDetailResponseBodyData) SetPostPaidStatus(v int32) *GetServerlessAppAuthDetailResponseBodyData {
	s.PostPaidStatus = &v
	return s
}

func (s *GetServerlessAppAuthDetailResponseBodyData) SetPostpaidInstanceId(v string) *GetServerlessAppAuthDetailResponseBodyData {
	s.PostpaidInstanceId = &v
	return s
}

func (s *GetServerlessAppAuthDetailResponseBodyData) Validate() error {
	return dara.Validate(s)
}
