// This file is auto-generated, don't edit it. Thanks.
package client

import (
	"github.com/alibabacloud-go/tea/dara"
)

type iListMachineAppsResponseBody interface {
	dara.Model
	String() string
	GoString() string
	SetAppList(v []*ListMachineAppsResponseBodyAppList) *ListMachineAppsResponseBody
	GetAppList() []*ListMachineAppsResponseBodyAppList
	SetPageInfo(v *ListMachineAppsResponseBodyPageInfo) *ListMachineAppsResponseBody
	GetPageInfo() *ListMachineAppsResponseBodyPageInfo
	SetRequestId(v string) *ListMachineAppsResponseBody
	GetRequestId() *string
}

type ListMachineAppsResponseBody struct {
	// Application list.
	AppList []*ListMachineAppsResponseBodyAppList `json:"AppList,omitempty" xml:"AppList,omitempty" type:"Repeated"`
	// Pagination information of the query result.
	PageInfo *ListMachineAppsResponseBodyPageInfo `json:"PageInfo,omitempty" xml:"PageInfo,omitempty" type:"Struct"`
	// The ID of this call request, which is a unique identifier generated by Alibaba Cloud for the request. It can be used to troubleshoot and pinpoint issues.
	//
	// example:
	//
	// 028CF634-5268-5660-9575-48C9ED6B****
	RequestId *string `json:"RequestId,omitempty" xml:"RequestId,omitempty"`
}

func (s ListMachineAppsResponseBody) String() string {
	return dara.Prettify(s)
}

func (s ListMachineAppsResponseBody) GoString() string {
	return s.String()
}

func (s *ListMachineAppsResponseBody) GetAppList() []*ListMachineAppsResponseBodyAppList {
	return s.AppList
}

func (s *ListMachineAppsResponseBody) GetPageInfo() *ListMachineAppsResponseBodyPageInfo {
	return s.PageInfo
}

func (s *ListMachineAppsResponseBody) GetRequestId() *string {
	return s.RequestId
}

func (s *ListMachineAppsResponseBody) SetAppList(v []*ListMachineAppsResponseBodyAppList) *ListMachineAppsResponseBody {
	s.AppList = v
	return s
}

func (s *ListMachineAppsResponseBody) SetPageInfo(v *ListMachineAppsResponseBodyPageInfo) *ListMachineAppsResponseBody {
	s.PageInfo = v
	return s
}

func (s *ListMachineAppsResponseBody) SetRequestId(v string) *ListMachineAppsResponseBody {
	s.RequestId = &v
	return s
}

func (s *ListMachineAppsResponseBody) Validate() error {
	return dara.Validate(s)
}

type ListMachineAppsResponseBodyAppList struct {
	// SAE application ID.
	//
	// example:
	//
	// 5b41f4bf-349f-4263-89b1-9234c034****
	AppId *string `json:"AppId,omitempty" xml:"AppId,omitempty"`
	// SAE application name.
	//
	// example:
	//
	// app-ubuntu
	AppName *string `json:"AppName,omitempty" xml:"AppName,omitempty"`
	// Region ID.
	//
	// example:
	//
	// cn-hangzhou
	AppRegionId *string `json:"AppRegionId,omitempty" xml:"AppRegionId,omitempty"`
}

func (s ListMachineAppsResponseBodyAppList) String() string {
	return dara.Prettify(s)
}

func (s ListMachineAppsResponseBodyAppList) GoString() string {
	return s.String()
}

func (s *ListMachineAppsResponseBodyAppList) GetAppId() *string {
	return s.AppId
}

func (s *ListMachineAppsResponseBodyAppList) GetAppName() *string {
	return s.AppName
}

func (s *ListMachineAppsResponseBodyAppList) GetAppRegionId() *string {
	return s.AppRegionId
}

func (s *ListMachineAppsResponseBodyAppList) SetAppId(v string) *ListMachineAppsResponseBodyAppList {
	s.AppId = &v
	return s
}

func (s *ListMachineAppsResponseBodyAppList) SetAppName(v string) *ListMachineAppsResponseBodyAppList {
	s.AppName = &v
	return s
}

func (s *ListMachineAppsResponseBodyAppList) SetAppRegionId(v string) *ListMachineAppsResponseBodyAppList {
	s.AppRegionId = &v
	return s
}

func (s *ListMachineAppsResponseBodyAppList) Validate() error {
	return dara.Validate(s)
}

type ListMachineAppsResponseBodyPageInfo struct {
	// The current page number in a paginated query.
	//
	// example:
	//
	// 1
	CurrentPage *int32 `json:"CurrentPage,omitempty" xml:"CurrentPage,omitempty"`
	// The maximum number of items to display per page in a paginated query.
	//
	// example:
	//
	// 20
	PageSize *int32 `json:"PageSize,omitempty" xml:"PageSize,omitempty"`
	// The total number of data items.
	//
	// example:
	//
	// 263
	TotalCount *int32 `json:"TotalCount,omitempty" xml:"TotalCount,omitempty"`
}

func (s ListMachineAppsResponseBodyPageInfo) String() string {
	return dara.Prettify(s)
}

func (s ListMachineAppsResponseBodyPageInfo) GoString() string {
	return s.String()
}

func (s *ListMachineAppsResponseBodyPageInfo) GetCurrentPage() *int32 {
	return s.CurrentPage
}

func (s *ListMachineAppsResponseBodyPageInfo) GetPageSize() *int32 {
	return s.PageSize
}

func (s *ListMachineAppsResponseBodyPageInfo) GetTotalCount() *int32 {
	return s.TotalCount
}

func (s *ListMachineAppsResponseBodyPageInfo) SetCurrentPage(v int32) *ListMachineAppsResponseBodyPageInfo {
	s.CurrentPage = &v
	return s
}

func (s *ListMachineAppsResponseBodyPageInfo) SetPageSize(v int32) *ListMachineAppsResponseBodyPageInfo {
	s.PageSize = &v
	return s
}

func (s *ListMachineAppsResponseBodyPageInfo) SetTotalCount(v int32) *ListMachineAppsResponseBodyPageInfo {
	s.TotalCount = &v
	return s
}

func (s *ListMachineAppsResponseBodyPageInfo) Validate() error {
	return dara.Validate(s)
}
