// This file is auto-generated, don't edit it. Thanks.
package client

import (
	"github.com/alibabacloud-go/tea/dara"
)

type iListUserVpcResponseBody interface {
	dara.Model
	String() string
	GoString() string
	SetRequestId(v string) *ListUserVpcResponseBody
	GetRequestId() *string
	SetUserVpcInfos(v []*ListUserVpcResponseBodyUserVpcInfos) *ListUserVpcResponseBody
	GetUserVpcInfos() []*ListUserVpcResponseBodyUserVpcInfos
}

type ListUserVpcResponseBody struct {
	// The ID of the request, which is a unique identifier generated by Alibaba Cloud for this request and can be used to troubleshoot and locate issues.
	//
	// example:
	//
	// A3D7C47D-3F11-57BB-90E8-E5C20C619F37
	RequestId *string `json:"RequestId,omitempty" xml:"RequestId,omitempty"`
	// List of VPC information.
	UserVpcInfos []*ListUserVpcResponseBodyUserVpcInfos `json:"UserVpcInfos,omitempty" xml:"UserVpcInfos,omitempty" type:"Repeated"`
}

func (s ListUserVpcResponseBody) String() string {
	return dara.Prettify(s)
}

func (s ListUserVpcResponseBody) GoString() string {
	return s.String()
}

func (s *ListUserVpcResponseBody) GetRequestId() *string {
	return s.RequestId
}

func (s *ListUserVpcResponseBody) GetUserVpcInfos() []*ListUserVpcResponseBodyUserVpcInfos {
	return s.UserVpcInfos
}

func (s *ListUserVpcResponseBody) SetRequestId(v string) *ListUserVpcResponseBody {
	s.RequestId = &v
	return s
}

func (s *ListUserVpcResponseBody) SetUserVpcInfos(v []*ListUserVpcResponseBodyUserVpcInfos) *ListUserVpcResponseBody {
	s.UserVpcInfos = v
	return s
}

func (s *ListUserVpcResponseBody) Validate() error {
	return dara.Validate(s)
}

type ListUserVpcResponseBodyUserVpcInfos struct {
	// IPv4 network segment of the VPC.
	//
	// example:
	//
	// 192.168.XXX.XXX/16
	CidrBlock *string `json:"CidrBlock,omitempty" xml:"CidrBlock,omitempty"`
	// Creation time.
	//
	// example:
	//
	// 2023-03-30T07:16:02Z
	CreationTime *string `json:"CreationTime,omitempty" xml:"CreationTime,omitempty"`
	// Indicates whether it is the default VPC in the region. Values:
	//
	// - **true**: Yes - **false**: No
	//
	// example:
	//
	// true
	Default *bool `json:"Default,omitempty" xml:"Default,omitempty"`
	// Description of the VPC.
	//
	// example:
	//
	// This is my VPC.
	Description *string `json:"Description,omitempty" xml:"Description,omitempty"`
	// Modification time.
	//
	// example:
	//
	// 2023-03-30T07:16:02Z
	ModifyTime *string `json:"ModifyTime,omitempty" xml:"ModifyTime,omitempty"`
	// Region
	//
	// example:
	//
	// cn-hangzhou
	RegionId *string `json:"RegionId,omitempty" xml:"RegionId,omitempty"`
	// Status of the VPC. Values:
	//
	// - **Pending**: Configuring
	//
	// - **Available**: Available
	//
	// example:
	//
	// Available
	Status *string `json:"Status,omitempty" xml:"Status,omitempty"`
	// ID of the VPC router.
	//
	// example:
	//
	// vrt-bp1jcg5cmxjbl9xgc****
	VRouterId *string `json:"VRouterId,omitempty" xml:"VRouterId,omitempty"`
	// ID of the VPC.
	//
	// example:
	//
	// vpc-bp1qpo0kug3a20qqe****
	VpcId *string `json:"VpcId,omitempty" xml:"VpcId,omitempty"`
	// Name of the VPC.
	//
	// example:
	//
	// Vpc-1
	VpcName *string `json:"VpcName,omitempty" xml:"VpcName,omitempty"`
}

func (s ListUserVpcResponseBodyUserVpcInfos) String() string {
	return dara.Prettify(s)
}

func (s ListUserVpcResponseBodyUserVpcInfos) GoString() string {
	return s.String()
}

func (s *ListUserVpcResponseBodyUserVpcInfos) GetCidrBlock() *string {
	return s.CidrBlock
}

func (s *ListUserVpcResponseBodyUserVpcInfos) GetCreationTime() *string {
	return s.CreationTime
}

func (s *ListUserVpcResponseBodyUserVpcInfos) GetDefault() *bool {
	return s.Default
}

func (s *ListUserVpcResponseBodyUserVpcInfos) GetDescription() *string {
	return s.Description
}

func (s *ListUserVpcResponseBodyUserVpcInfos) GetModifyTime() *string {
	return s.ModifyTime
}

func (s *ListUserVpcResponseBodyUserVpcInfos) GetRegionId() *string {
	return s.RegionId
}

func (s *ListUserVpcResponseBodyUserVpcInfos) GetStatus() *string {
	return s.Status
}

func (s *ListUserVpcResponseBodyUserVpcInfos) GetVRouterId() *string {
	return s.VRouterId
}

func (s *ListUserVpcResponseBodyUserVpcInfos) GetVpcId() *string {
	return s.VpcId
}

func (s *ListUserVpcResponseBodyUserVpcInfos) GetVpcName() *string {
	return s.VpcName
}

func (s *ListUserVpcResponseBodyUserVpcInfos) SetCidrBlock(v string) *ListUserVpcResponseBodyUserVpcInfos {
	s.CidrBlock = &v
	return s
}

func (s *ListUserVpcResponseBodyUserVpcInfos) SetCreationTime(v string) *ListUserVpcResponseBodyUserVpcInfos {
	s.CreationTime = &v
	return s
}

func (s *ListUserVpcResponseBodyUserVpcInfos) SetDefault(v bool) *ListUserVpcResponseBodyUserVpcInfos {
	s.Default = &v
	return s
}

func (s *ListUserVpcResponseBodyUserVpcInfos) SetDescription(v string) *ListUserVpcResponseBodyUserVpcInfos {
	s.Description = &v
	return s
}

func (s *ListUserVpcResponseBodyUserVpcInfos) SetModifyTime(v string) *ListUserVpcResponseBodyUserVpcInfos {
	s.ModifyTime = &v
	return s
}

func (s *ListUserVpcResponseBodyUserVpcInfos) SetRegionId(v string) *ListUserVpcResponseBodyUserVpcInfos {
	s.RegionId = &v
	return s
}

func (s *ListUserVpcResponseBodyUserVpcInfos) SetStatus(v string) *ListUserVpcResponseBodyUserVpcInfos {
	s.Status = &v
	return s
}

func (s *ListUserVpcResponseBodyUserVpcInfos) SetVRouterId(v string) *ListUserVpcResponseBodyUserVpcInfos {
	s.VRouterId = &v
	return s
}

func (s *ListUserVpcResponseBodyUserVpcInfos) SetVpcId(v string) *ListUserVpcResponseBodyUserVpcInfos {
	s.VpcId = &v
	return s
}

func (s *ListUserVpcResponseBodyUserVpcInfos) SetVpcName(v string) *ListUserVpcResponseBodyUserVpcInfos {
	s.VpcName = &v
	return s
}

func (s *ListUserVpcResponseBodyUserVpcInfos) Validate() error {
	return dara.Validate(s)
}
