// This file is auto-generated, don't edit it. Thanks.
package client

import (
	"github.com/alibabacloud-go/tea/dara"
)

type iListAegisForLingjunStatusResponseBody interface {
	dara.Model
	String() string
	GoString() string
	SetInvokeTasks(v []*ListAegisForLingjunStatusResponseBodyInvokeTasks) *ListAegisForLingjunStatusResponseBody
	GetInvokeTasks() []*ListAegisForLingjunStatusResponseBodyInvokeTasks
	SetRequestId(v string) *ListAegisForLingjunStatusResponseBody
	GetRequestId() *string
	SetSuccess(v bool) *ListAegisForLingjunStatusResponseBody
	GetSuccess() *bool
}

type ListAegisForLingjunStatusResponseBody struct {
	// List of returned installation tasks.
	InvokeTasks []*ListAegisForLingjunStatusResponseBodyInvokeTasks `json:"InvokeTasks,omitempty" xml:"InvokeTasks,omitempty" type:"Repeated"`
	// The ID of this request, which is a unique identifier generated by Alibaba Cloud for this request and can be used for troubleshooting and problem localization.
	//
	// example:
	//
	// F8B6F758-BCD4-597A-8A2C-DA5A552C****
	RequestId *string `json:"RequestId,omitempty" xml:"RequestId,omitempty"`
	// Indicates whether the API call was successful. Values:
	//
	// - **true**: Success
	//
	// - **false**: Failure
	//
	// example:
	//
	// true
	Success *bool `json:"Success,omitempty" xml:"Success,omitempty"`
}

func (s ListAegisForLingjunStatusResponseBody) String() string {
	return dara.Prettify(s)
}

func (s ListAegisForLingjunStatusResponseBody) GoString() string {
	return s.String()
}

func (s *ListAegisForLingjunStatusResponseBody) GetInvokeTasks() []*ListAegisForLingjunStatusResponseBodyInvokeTasks {
	return s.InvokeTasks
}

func (s *ListAegisForLingjunStatusResponseBody) GetRequestId() *string {
	return s.RequestId
}

func (s *ListAegisForLingjunStatusResponseBody) GetSuccess() *bool {
	return s.Success
}

func (s *ListAegisForLingjunStatusResponseBody) SetInvokeTasks(v []*ListAegisForLingjunStatusResponseBodyInvokeTasks) *ListAegisForLingjunStatusResponseBody {
	s.InvokeTasks = v
	return s
}

func (s *ListAegisForLingjunStatusResponseBody) SetRequestId(v string) *ListAegisForLingjunStatusResponseBody {
	s.RequestId = &v
	return s
}

func (s *ListAegisForLingjunStatusResponseBody) SetSuccess(v bool) *ListAegisForLingjunStatusResponseBody {
	s.Success = &v
	return s
}

func (s *ListAegisForLingjunStatusResponseBody) Validate() error {
	if s.InvokeTasks != nil {
		for _, item := range s.InvokeTasks {
			if item != nil {
				if err := item.Validate(); err != nil {
					return err
				}
			}
		}
	}
	return nil
}

type ListAegisForLingjunStatusResponseBodyInvokeTasks struct {
	// Installation task ID for the Lingjun machine.
	//
	// example:
	//
	// t-bj05dlbzple****
	InvokeId *string `json:"InvokeId,omitempty" xml:"InvokeId,omitempty"`
	// Installation processing result. Values:
	//
	// - success: Installation successful
	//
	// - fail: Installation failed
	//
	// example:
	//
	// success
	Result *string `json:"Result,omitempty" xml:"Result,omitempty"`
	// Installation status. Values:
	//
	// - **1**: Installation successful
	//
	// - **0**: Installation failed
	//
	// example:
	//
	// 1
	Status *int32 `json:"Status,omitempty" xml:"Status,omitempty"`
	// Unique UUID for Lingjun bare metal.
	//
	// example:
	//
	// inet-8e3fbd56-122c-4011-b692-4d048076****
	Uuid *string `json:"Uuid,omitempty" xml:"Uuid,omitempty"`
}

func (s ListAegisForLingjunStatusResponseBodyInvokeTasks) String() string {
	return dara.Prettify(s)
}

func (s ListAegisForLingjunStatusResponseBodyInvokeTasks) GoString() string {
	return s.String()
}

func (s *ListAegisForLingjunStatusResponseBodyInvokeTasks) GetInvokeId() *string {
	return s.InvokeId
}

func (s *ListAegisForLingjunStatusResponseBodyInvokeTasks) GetResult() *string {
	return s.Result
}

func (s *ListAegisForLingjunStatusResponseBodyInvokeTasks) GetStatus() *int32 {
	return s.Status
}

func (s *ListAegisForLingjunStatusResponseBodyInvokeTasks) GetUuid() *string {
	return s.Uuid
}

func (s *ListAegisForLingjunStatusResponseBodyInvokeTasks) SetInvokeId(v string) *ListAegisForLingjunStatusResponseBodyInvokeTasks {
	s.InvokeId = &v
	return s
}

func (s *ListAegisForLingjunStatusResponseBodyInvokeTasks) SetResult(v string) *ListAegisForLingjunStatusResponseBodyInvokeTasks {
	s.Result = &v
	return s
}

func (s *ListAegisForLingjunStatusResponseBodyInvokeTasks) SetStatus(v int32) *ListAegisForLingjunStatusResponseBodyInvokeTasks {
	s.Status = &v
	return s
}

func (s *ListAegisForLingjunStatusResponseBodyInvokeTasks) SetUuid(v string) *ListAegisForLingjunStatusResponseBodyInvokeTasks {
	s.Uuid = &v
	return s
}

func (s *ListAegisForLingjunStatusResponseBodyInvokeTasks) Validate() error {
	return dara.Validate(s)
}
