// This file is auto-generated, don't edit it. Thanks.
package client

import (
	"github.com/alibabacloud-go/tea/dara"
)

type iUpdateInstanceRequest interface {
	dara.Model
	String() string
	GoString() string
	SetRegionId(v string) *UpdateInstanceRequest
	GetRegionId() *string
	SetAutoBackup(v bool) *UpdateInstanceRequest
	GetAutoBackup() *bool
	SetAutoPay(v bool) *UpdateInstanceRequest
	GetAutoPay() *bool
	SetComponents(v []*UpdateInstanceRequestComponents) *UpdateInstanceRequest
	GetComponents() []*UpdateInstanceRequestComponents
	SetConfiguration(v string) *UpdateInstanceRequest
	GetConfiguration() *string
	SetHa(v bool) *UpdateInstanceRequest
	GetHa() *bool
	SetInstanceId(v string) *UpdateInstanceRequest
	GetInstanceId() *string
	SetInstanceName(v string) *UpdateInstanceRequest
	GetInstanceName() *string
	SetClientToken(v string) *UpdateInstanceRequest
	GetClientToken() *string
}

type UpdateInstanceRequest struct {
	// The region ID.
	//
	// example:
	//
	// cn-beijing
	RegionId *string `json:"RegionId,omitempty" xml:"RegionId,omitempty"`
	// Specifies whether to enable automatic backup.
	//
	// example:
	//
	// true
	AutoBackup *bool `json:"autoBackup,omitempty" xml:"autoBackup,omitempty"`
	AutoPay    *bool `json:"autoPay,omitempty" xml:"autoPay,omitempty"`
	// The component information.
	Components []*UpdateInstanceRequestComponents `json:"components,omitempty" xml:"components,omitempty" type:"Repeated"`
	// The configuration information.
	//
	// example:
	//
	// rootCoord:\\n  maxDatabaseNum: 64
	Configuration *string `json:"configuration,omitempty" xml:"configuration,omitempty"`
	// Specifies whether to enable high availability.
	//
	// example:
	//
	// true
	Ha *bool `json:"ha,omitempty" xml:"ha,omitempty"`
	// The instance ID.
	//
	// This parameter is required.
	//
	// example:
	//
	// c-xxxx
	InstanceId *string `json:"instanceId,omitempty" xml:"instanceId,omitempty"`
	// The instance name.
	//
	// example:
	//
	// milvus-test
	InstanceName *string `json:"instanceName,omitempty" xml:"instanceName,omitempty"`
	// The client token that is used to ensure the idempotence of the request. This parameter value is generated by the client and must be unique among different requests. The value can be up to 64 ASCII characters in length.
	//
	// example:
	//
	// xxx
	ClientToken *string `json:"clientToken,omitempty" xml:"clientToken,omitempty"`
}

func (s UpdateInstanceRequest) String() string {
	return dara.Prettify(s)
}

func (s UpdateInstanceRequest) GoString() string {
	return s.String()
}

func (s *UpdateInstanceRequest) GetRegionId() *string {
	return s.RegionId
}

func (s *UpdateInstanceRequest) GetAutoBackup() *bool {
	return s.AutoBackup
}

func (s *UpdateInstanceRequest) GetAutoPay() *bool {
	return s.AutoPay
}

func (s *UpdateInstanceRequest) GetComponents() []*UpdateInstanceRequestComponents {
	return s.Components
}

func (s *UpdateInstanceRequest) GetConfiguration() *string {
	return s.Configuration
}

func (s *UpdateInstanceRequest) GetHa() *bool {
	return s.Ha
}

func (s *UpdateInstanceRequest) GetInstanceId() *string {
	return s.InstanceId
}

func (s *UpdateInstanceRequest) GetInstanceName() *string {
	return s.InstanceName
}

func (s *UpdateInstanceRequest) GetClientToken() *string {
	return s.ClientToken
}

func (s *UpdateInstanceRequest) SetRegionId(v string) *UpdateInstanceRequest {
	s.RegionId = &v
	return s
}

func (s *UpdateInstanceRequest) SetAutoBackup(v bool) *UpdateInstanceRequest {
	s.AutoBackup = &v
	return s
}

func (s *UpdateInstanceRequest) SetAutoPay(v bool) *UpdateInstanceRequest {
	s.AutoPay = &v
	return s
}

func (s *UpdateInstanceRequest) SetComponents(v []*UpdateInstanceRequestComponents) *UpdateInstanceRequest {
	s.Components = v
	return s
}

func (s *UpdateInstanceRequest) SetConfiguration(v string) *UpdateInstanceRequest {
	s.Configuration = &v
	return s
}

func (s *UpdateInstanceRequest) SetHa(v bool) *UpdateInstanceRequest {
	s.Ha = &v
	return s
}

func (s *UpdateInstanceRequest) SetInstanceId(v string) *UpdateInstanceRequest {
	s.InstanceId = &v
	return s
}

func (s *UpdateInstanceRequest) SetInstanceName(v string) *UpdateInstanceRequest {
	s.InstanceName = &v
	return s
}

func (s *UpdateInstanceRequest) SetClientToken(v string) *UpdateInstanceRequest {
	s.ClientToken = &v
	return s
}

func (s *UpdateInstanceRequest) Validate() error {
	if s.Components != nil {
		for _, item := range s.Components {
			if item != nil {
				if err := item.Validate(); err != nil {
					return err
				}
			}
		}
	}
	return nil
}

type UpdateInstanceRequestComponents struct {
	// The number of compute units (CUs).
	//
	// This parameter is required.
	//
	// example:
	//
	// 8
	CuNum    *int32                                   `json:"cuNum,omitempty" xml:"cuNum,omitempty"`
	CuType   *string                                  `json:"cuType,omitempty" xml:"cuType,omitempty"`
	DataDisk *UpdateInstanceRequestComponentsDataDisk `json:"dataDisk,omitempty" xml:"dataDisk,omitempty" type:"Struct"`
	PayType  *string                                  `json:"payType,omitempty" xml:"payType,omitempty"`
	// The number of replicas.
	//
	// This parameter is required.
	//
	// example:
	//
	// 1
	Replica *int32 `json:"replica,omitempty" xml:"replica,omitempty"`
	// The component type.
	//
	// This parameter is required.
	//
	// example:
	//
	// standalone
	Type *string `json:"type,omitempty" xml:"type,omitempty"`
}

func (s UpdateInstanceRequestComponents) String() string {
	return dara.Prettify(s)
}

func (s UpdateInstanceRequestComponents) GoString() string {
	return s.String()
}

func (s *UpdateInstanceRequestComponents) GetCuNum() *int32 {
	return s.CuNum
}

func (s *UpdateInstanceRequestComponents) GetCuType() *string {
	return s.CuType
}

func (s *UpdateInstanceRequestComponents) GetDataDisk() *UpdateInstanceRequestComponentsDataDisk {
	return s.DataDisk
}

func (s *UpdateInstanceRequestComponents) GetPayType() *string {
	return s.PayType
}

func (s *UpdateInstanceRequestComponents) GetReplica() *int32 {
	return s.Replica
}

func (s *UpdateInstanceRequestComponents) GetType() *string {
	return s.Type
}

func (s *UpdateInstanceRequestComponents) SetCuNum(v int32) *UpdateInstanceRequestComponents {
	s.CuNum = &v
	return s
}

func (s *UpdateInstanceRequestComponents) SetCuType(v string) *UpdateInstanceRequestComponents {
	s.CuType = &v
	return s
}

func (s *UpdateInstanceRequestComponents) SetDataDisk(v *UpdateInstanceRequestComponentsDataDisk) *UpdateInstanceRequestComponents {
	s.DataDisk = v
	return s
}

func (s *UpdateInstanceRequestComponents) SetPayType(v string) *UpdateInstanceRequestComponents {
	s.PayType = &v
	return s
}

func (s *UpdateInstanceRequestComponents) SetReplica(v int32) *UpdateInstanceRequestComponents {
	s.Replica = &v
	return s
}

func (s *UpdateInstanceRequestComponents) SetType(v string) *UpdateInstanceRequestComponents {
	s.Type = &v
	return s
}

func (s *UpdateInstanceRequestComponents) Validate() error {
	if s.DataDisk != nil {
		if err := s.DataDisk.Validate(); err != nil {
			return err
		}
	}
	return nil
}

type UpdateInstanceRequestComponentsDataDisk struct {
	// example:
	//
	// true
	Enabled *bool `json:"enabled,omitempty" xml:"enabled,omitempty"`
	// example:
	//
	// PL1
	PerformanceLevel *string `json:"performanceLevel,omitempty" xml:"performanceLevel,omitempty"`
	// example:
	//
	// 100
	Size *int32 `json:"size,omitempty" xml:"size,omitempty"`
	// example:
	//
	// alicloud-disk-essd-pl1
	StorageClass *string `json:"storageClass,omitempty" xml:"storageClass,omitempty"`
}

func (s UpdateInstanceRequestComponentsDataDisk) String() string {
	return dara.Prettify(s)
}

func (s UpdateInstanceRequestComponentsDataDisk) GoString() string {
	return s.String()
}

func (s *UpdateInstanceRequestComponentsDataDisk) GetEnabled() *bool {
	return s.Enabled
}

func (s *UpdateInstanceRequestComponentsDataDisk) GetPerformanceLevel() *string {
	return s.PerformanceLevel
}

func (s *UpdateInstanceRequestComponentsDataDisk) GetSize() *int32 {
	return s.Size
}

func (s *UpdateInstanceRequestComponentsDataDisk) GetStorageClass() *string {
	return s.StorageClass
}

func (s *UpdateInstanceRequestComponentsDataDisk) SetEnabled(v bool) *UpdateInstanceRequestComponentsDataDisk {
	s.Enabled = &v
	return s
}

func (s *UpdateInstanceRequestComponentsDataDisk) SetPerformanceLevel(v string) *UpdateInstanceRequestComponentsDataDisk {
	s.PerformanceLevel = &v
	return s
}

func (s *UpdateInstanceRequestComponentsDataDisk) SetSize(v int32) *UpdateInstanceRequestComponentsDataDisk {
	s.Size = &v
	return s
}

func (s *UpdateInstanceRequestComponentsDataDisk) SetStorageClass(v string) *UpdateInstanceRequestComponentsDataDisk {
	s.StorageClass = &v
	return s
}

func (s *UpdateInstanceRequestComponentsDataDisk) Validate() error {
	return dara.Validate(s)
}
