// This file is auto-generated, don't edit it. Thanks.
package client

import (
	"github.com/alibabacloud-go/tea/dara"
)

type iUpdateSmsSignResponseBody interface {
	dara.Model
	String() string
	GoString() string
	SetCode(v string) *UpdateSmsSignResponseBody
	GetCode() *string
	SetMessage(v string) *UpdateSmsSignResponseBody
	GetMessage() *string
	SetOrderId(v string) *UpdateSmsSignResponseBody
	GetOrderId() *string
	SetRequestId(v string) *UpdateSmsSignResponseBody
	GetRequestId() *string
	SetSignName(v string) *UpdateSmsSignResponseBody
	GetSignName() *string
}

type UpdateSmsSignResponseBody struct {
	// The status code of the request. Valid values:
	//
	// - OK: The request was successful.
	//
	// - For other error codes, see [Error codes](https://help.aliyun.com/document_detail/101346.html).
	//
	// example:
	//
	// OK
	Code *string `json:"Code,omitempty" xml:"Code,omitempty"`
	// The description of the status code.
	//
	// example:
	//
	// OK
	Message *string `json:"Message,omitempty" xml:"Message,omitempty"`
	// The order ID.
	//
	// Reviewers use this ID to look up the submission. Provide this order ID to request an expedited review.
	//
	// example:
	//
	// 2004417****
	OrderId *string `json:"OrderId,omitempty" xml:"OrderId,omitempty"`
	// The unique identifier for the request, generated by Alibaba Cloud. Use this ID to troubleshoot issues.
	//
	// example:
	//
	// A90E4451-FED7-49D2-87C8-00700A8C4D1D
	RequestId *string `json:"RequestId,omitempty" xml:"RequestId,omitempty"`
	// The updated signature name.
	//
	// example:
	//
	// 登录验证
	SignName *string `json:"SignName,omitempty" xml:"SignName,omitempty"`
}

func (s UpdateSmsSignResponseBody) String() string {
	return dara.Prettify(s)
}

func (s UpdateSmsSignResponseBody) GoString() string {
	return s.String()
}

func (s *UpdateSmsSignResponseBody) GetCode() *string {
	return s.Code
}

func (s *UpdateSmsSignResponseBody) GetMessage() *string {
	return s.Message
}

func (s *UpdateSmsSignResponseBody) GetOrderId() *string {
	return s.OrderId
}

func (s *UpdateSmsSignResponseBody) GetRequestId() *string {
	return s.RequestId
}

func (s *UpdateSmsSignResponseBody) GetSignName() *string {
	return s.SignName
}

func (s *UpdateSmsSignResponseBody) SetCode(v string) *UpdateSmsSignResponseBody {
	s.Code = &v
	return s
}

func (s *UpdateSmsSignResponseBody) SetMessage(v string) *UpdateSmsSignResponseBody {
	s.Message = &v
	return s
}

func (s *UpdateSmsSignResponseBody) SetOrderId(v string) *UpdateSmsSignResponseBody {
	s.OrderId = &v
	return s
}

func (s *UpdateSmsSignResponseBody) SetRequestId(v string) *UpdateSmsSignResponseBody {
	s.RequestId = &v
	return s
}

func (s *UpdateSmsSignResponseBody) SetSignName(v string) *UpdateSmsSignResponseBody {
	s.SignName = &v
	return s
}

func (s *UpdateSmsSignResponseBody) Validate() error {
	return dara.Validate(s)
}
