// This file is auto-generated, don't edit it. Thanks.
package client

import (
	"github.com/alibabacloud-go/tea/dara"
)

type iSetDomainResponseBody interface {
	dara.Model
	String() string
	GoString() string
	SetDomainBindingStatus(v string) *SetDomainResponseBody
	GetDomainBindingStatus() *string
	SetDomainLegalStatus(v string) *SetDomainResponseBody
	GetDomainLegalStatus() *string
	SetDomainName(v string) *SetDomainResponseBody
	GetDomainName() *string
	SetDomainRemark(v string) *SetDomainResponseBody
	GetDomainRemark() *string
	SetDomainWebSocketStatus(v string) *SetDomainResponseBody
	GetDomainWebSocketStatus() *string
	SetGroupId(v string) *SetDomainResponseBody
	GetGroupId() *string
	SetRequestId(v string) *SetDomainResponseBody
	GetRequestId() *string
	SetSubDomain(v string) *SetDomainResponseBody
	GetSubDomain() *string
}

type SetDomainResponseBody struct {
	// The binding status of the custom domain name. Valid values:
	//
	// 	- **BINDING**: The domain name has been bound.
	//
	// 	- **BOUND**: The domain name has not been bound.
	//
	// example:
	//
	// BINDING
	DomainBindingStatus *string `json:"DomainBindingStatus,omitempty" xml:"DomainBindingStatus,omitempty"`
	// The validity status of the domain name. Valid values:
	//
	// 	- **NORMAL**: The domain name is valid.
	//
	// 	- **ABNORMAL**: The domain name is invalid. This status affects API calls and must be resolved as soon as possible.
	//
	// example:
	//
	// NORMAL
	DomainLegalStatus *string `json:"DomainLegalStatus,omitempty" xml:"DomainLegalStatus,omitempty"`
	// The custom domain name.
	//
	// example:
	//
	// api.demo.com
	DomainName *string `json:"DomainName,omitempty" xml:"DomainName,omitempty"`
	// The remarks on the domain name, such as the cause of an exception.
	//
	// example:
	//
	// None
	DomainRemark *string `json:"DomainRemark,omitempty" xml:"DomainRemark,omitempty"`
	// The status of the domain name that uses the WebSocket feature.
	//
	// example:
	//
	// NORMAL
	DomainWebSocketStatus *string `json:"DomainWebSocketStatus,omitempty" xml:"DomainWebSocketStatus,omitempty"`
	// The ID of the API group. This ID is generated by the system and globally unique.
	//
	// example:
	//
	// 927d50c0f2e54b359919923d908bb015
	GroupId *string `json:"GroupId,omitempty" xml:"GroupId,omitempty"`
	// The ID of the request.
	//
	// example:
	//
	// 0AA90E87-3506-5AA6-AFFB-A4D53B4F6231
	RequestId *string `json:"RequestId,omitempty" xml:"RequestId,omitempty"`
	// The second-level domain name assigned to the API group. This domain name is used to test API calls.
	//
	// example:
	//
	// xxx-cn-hangzhou.alicloudapi.com
	SubDomain *string `json:"SubDomain,omitempty" xml:"SubDomain,omitempty"`
}

func (s SetDomainResponseBody) String() string {
	return dara.Prettify(s)
}

func (s SetDomainResponseBody) GoString() string {
	return s.String()
}

func (s *SetDomainResponseBody) GetDomainBindingStatus() *string {
	return s.DomainBindingStatus
}

func (s *SetDomainResponseBody) GetDomainLegalStatus() *string {
	return s.DomainLegalStatus
}

func (s *SetDomainResponseBody) GetDomainName() *string {
	return s.DomainName
}

func (s *SetDomainResponseBody) GetDomainRemark() *string {
	return s.DomainRemark
}

func (s *SetDomainResponseBody) GetDomainWebSocketStatus() *string {
	return s.DomainWebSocketStatus
}

func (s *SetDomainResponseBody) GetGroupId() *string {
	return s.GroupId
}

func (s *SetDomainResponseBody) GetRequestId() *string {
	return s.RequestId
}

func (s *SetDomainResponseBody) GetSubDomain() *string {
	return s.SubDomain
}

func (s *SetDomainResponseBody) SetDomainBindingStatus(v string) *SetDomainResponseBody {
	s.DomainBindingStatus = &v
	return s
}

func (s *SetDomainResponseBody) SetDomainLegalStatus(v string) *SetDomainResponseBody {
	s.DomainLegalStatus = &v
	return s
}

func (s *SetDomainResponseBody) SetDomainName(v string) *SetDomainResponseBody {
	s.DomainName = &v
	return s
}

func (s *SetDomainResponseBody) SetDomainRemark(v string) *SetDomainResponseBody {
	s.DomainRemark = &v
	return s
}

func (s *SetDomainResponseBody) SetDomainWebSocketStatus(v string) *SetDomainResponseBody {
	s.DomainWebSocketStatus = &v
	return s
}

func (s *SetDomainResponseBody) SetGroupId(v string) *SetDomainResponseBody {
	s.GroupId = &v
	return s
}

func (s *SetDomainResponseBody) SetRequestId(v string) *SetDomainResponseBody {
	s.RequestId = &v
	return s
}

func (s *SetDomainResponseBody) SetSubDomain(v string) *SetDomainResponseBody {
	s.SubDomain = &v
	return s
}

func (s *SetDomainResponseBody) Validate() error {
	return dara.Validate(s)
}
