// This file is auto-generated, don't edit it. Thanks.
package client

import (
	"github.com/alibabacloud-go/tea/dara"
)

type iResetUserPasswordResponseBody interface {
	dara.Model
	String() string
	GoString() string
	SetNewPassword(v string) *ResetUserPasswordResponseBody
	GetNewPassword() *string
	SetRequestId(v string) *ResetUserPasswordResponseBody
	GetRequestId() *string
}

type ResetUserPasswordResponseBody struct {
	// The new password.
	//
	// > This parameter is returned only when the new password is automatically generated by the system.
	//
	// example:
	//
	// W2koInFIm0Wy2wVZ$oB)MzD$nY!G****
	NewPassword *string `json:"NewPassword,omitempty" xml:"NewPassword,omitempty"`
	// The request ID.
	//
	// example:
	//
	// F44F02EC-70D1-5E51-8E8E-FA9AC4EF952A
	RequestId *string `json:"RequestId,omitempty" xml:"RequestId,omitempty"`
}

func (s ResetUserPasswordResponseBody) String() string {
	return dara.Prettify(s)
}

func (s ResetUserPasswordResponseBody) GoString() string {
	return s.String()
}

func (s *ResetUserPasswordResponseBody) GetNewPassword() *string {
	return s.NewPassword
}

func (s *ResetUserPasswordResponseBody) GetRequestId() *string {
	return s.RequestId
}

func (s *ResetUserPasswordResponseBody) SetNewPassword(v string) *ResetUserPasswordResponseBody {
	s.NewPassword = &v
	return s
}

func (s *ResetUserPasswordResponseBody) SetRequestId(v string) *ResetUserPasswordResponseBody {
	s.RequestId = &v
	return s
}

func (s *ResetUserPasswordResponseBody) Validate() error {
	return dara.Validate(s)
}
