// This file is auto-generated, don't edit it. Thanks.
package client

import (
	"github.com/alibabacloud-go/tea/dara"
)

type iGetLoginTokenRequest interface {
	dara.Model
	String() string
	GoString() string
	SetAuthenticationCode(v string) *GetLoginTokenRequest
	GetAuthenticationCode() *string
	SetAvailableFeatures(v map[string]*string) *GetLoginTokenRequest
	GetAvailableFeatures() map[string]*string
	SetClientId(v string) *GetLoginTokenRequest
	GetClientId() *string
	SetClientName(v string) *GetLoginTokenRequest
	GetClientName() *string
	SetClientOS(v string) *GetLoginTokenRequest
	GetClientOS() *string
	SetClientType(v string) *GetLoginTokenRequest
	GetClientType() *string
	SetClientVersion(v string) *GetLoginTokenRequest
	GetClientVersion() *string
	SetCurrentStage(v string) *GetLoginTokenRequest
	GetCurrentStage() *string
	SetDirectoryId(v string) *GetLoginTokenRequest
	GetDirectoryId() *string
	SetEndUserId(v string) *GetLoginTokenRequest
	GetEndUserId() *string
	SetKeepAlive(v bool) *GetLoginTokenRequest
	GetKeepAlive() *bool
	SetKeepAliveToken(v string) *GetLoginTokenRequest
	GetKeepAliveToken() *string
	SetNewPassword(v string) *GetLoginTokenRequest
	GetNewPassword() *string
	SetOfficeSiteId(v string) *GetLoginTokenRequest
	GetOfficeSiteId() *string
	SetOldPassword(v string) *GetLoginTokenRequest
	GetOldPassword() *string
	SetPassword(v string) *GetLoginTokenRequest
	GetPassword() *string
	SetRegionId(v string) *GetLoginTokenRequest
	GetRegionId() *string
	SetSessionId(v string) *GetLoginTokenRequest
	GetSessionId() *string
	SetTokenCode(v string) *GetLoginTokenRequest
	GetTokenCode() *string
	SetUuid(v string) *GetLoginTokenRequest
	GetUuid() *string
}

type GetLoginTokenRequest struct {
	// The security code generated by the virtual MFA device. This parameter is required when `CurrentStage` is set to `MFAVerify`.
	//
	// example:
	//
	// 47****
	AuthenticationCode *string            `json:"AuthenticationCode,omitempty" xml:"AuthenticationCode,omitempty"`
	AvailableFeatures  map[string]*string `json:"AvailableFeatures,omitempty" xml:"AvailableFeatures,omitempty"`
	// The unique ID generated by the client.
	//
	// This parameter is required.
	//
	// example:
	//
	// f4a0dc8e-1702-4728-9a60-95b27a35****
	ClientId   *string `json:"ClientId,omitempty" xml:"ClientId,omitempty"`
	ClientName *string `json:"ClientName,omitempty" xml:"ClientName,omitempty"`
	// The operating system of the device on which the client runs.
	//
	// example:
	//
	// Windows_NT 10.0.18363 x64
	ClientOS *string `json:"ClientOS,omitempty" xml:"ClientOS,omitempty"`
	// The type of the Elastic Desktop Service software client.
	//
	// example:
	//
	// WINDOWS
	ClientType *string `json:"ClientType,omitempty" xml:"ClientType,omitempty"`
	// The client version. If you use the Elastic Desktop Service client, you can view this parameter in the **About*	- dialog box on the client logon page.
	//
	// example:
	//
	// 2.1.0-R-20210731.151756
	ClientVersion *string `json:"ClientVersion,omitempty" xml:"ClientVersion,omitempty"`
	// The current logon authentication stage. The stages are as follows:
	//
	// - `ADPassword`: verifies user information. Specify this value when authenticating with the credentials of a convenience account or an AD account.
	//
	// - `MFABind`: binds a virtual MFA device.
	//
	// - `MFAVerify`: verifies the security code generated by the virtual MFA device.
	//
	// - `TokenVerify`: performs client secondary authentication.
	//
	// - `ChangePassword`: changes the user password.
	//
	// - `KeepAliveVerify`: exchanges a valid KeepAliveToken for a LoginToken.
	//
	// example:
	//
	// ADPassword
	CurrentStage *string `json:"CurrentStage,omitempty" xml:"CurrentStage,omitempty"`
	// The office network ID, which has the same meaning as `OfficeSiteId`. We recommend that you stop using `DirectoryId` and use `OfficeSiteId` instead. You can specify only one of `DirectoryId` and `OfficeSiteId`, not both.
	//
	// example:
	//
	// cn-hangzhou+dir-885351****
	DirectoryId *string `json:"DirectoryId,omitempty" xml:"DirectoryId,omitempty"`
	// The username of the convenience user or AD user. This parameter is required when `CurrentStage` is set to `ADPassword`.
	//
	// example:
	//
	// alice
	EndUserId *string `json:"EndUserId,omitempty" xml:"EndUserId,omitempty"`
	// Specifies whether to keep the logon session alive.
	//
	// example:
	//
	// false
	KeepAlive *bool `json:"KeepAlive,omitempty" xml:"KeepAlive,omitempty"`
	// The token used to keep the logon session alive. After a successful logon with the keep-alive option enabled, the operation returns a `KeepAliveToken`. While the `KeepAliveToken` is valid, you can call the `GetLoginToken` operation with `CurrentStage` set to `KeepAliveVerify` to exchange it for a logon credential (LoginToken). This parameter is required when `CurrentStage` is set to `KeepAliveVerify`.
	//
	// example:
	//
	// hide
	KeepAliveToken *string `json:"KeepAliveToken,omitempty" xml:"KeepAliveToken,omitempty"`
	// The new password. This parameter is required when `CurrentStage` is set to `ChangePassword`.
	//
	// example:
	//
	// NewPassword
	NewPassword *string `json:"NewPassword,omitempty" xml:"NewPassword,omitempty"`
	// The office network ID.
	//
	// example:
	//
	// cn-hangzhou+dir-885351****
	OfficeSiteId *string `json:"OfficeSiteId,omitempty" xml:"OfficeSiteId,omitempty"`
	// The old password. This parameter is required when `CurrentStage` is set to `ChangePassword`.
	//
	// example:
	//
	// OldPassword
	OldPassword *string `json:"OldPassword,omitempty" xml:"OldPassword,omitempty"`
	// The password of the convenience user or AD user. This parameter is required when `CurrentStage` is set to `ADPassword`.
	//
	// example:
	//
	// Password1234
	Password *string `json:"Password,omitempty" xml:"Password,omitempty"`
	// The region ID. You can call [DescribeRegions](https://help.aliyun.com/document_detail/196646.html) to query the regions supported by Elastic Desktop Service.
	//
	// This parameter is required.
	//
	// example:
	//
	// cn-hangzhou
	RegionId *string `json:"RegionId,omitempty" xml:"RegionId,omitempty"`
	// The session ID for logon.
	//
	// - If no virtual MFA device is bound or client secondary authentication is not enabled, you do not need to specify `SessionId`.
	//
	// - If a virtual MFA device is bound or client secondary authentication is enabled, you must specify `SessionId` for the authentication stages after `ADPassword`. You can obtain `SessionId` from the response of the convenience account verification (when the `GetLoginToken` request is in the `ADPassword` stage).
	//
	// example:
	//
	// cd45e873-650d-4d70-acb9-f996187a****
	SessionId *string `json:"SessionId,omitempty" xml:"SessionId,omitempty"`
	// If client secondary authentication is enabled in the Elastic Desktop Service console and the current logon user is identified as risky, a secondary authentication verification code is sent to the end user\\"s email address. This parameter is required when `CurrentStage` is set to `TokenVerify`.
	//
	// example:
	//
	// 63****
	TokenCode *string `json:"TokenCode,omitempty" xml:"TokenCode,omitempty"`
	// The unique identifier of the client. If you use the Elastic Desktop Service client, you can view this parameter in the **About*	- dialog box on the client logon page.
	//
	// example:
	//
	// C78CA9E99315687575DD2844C1F3****
	Uuid *string `json:"Uuid,omitempty" xml:"Uuid,omitempty"`
}

func (s GetLoginTokenRequest) String() string {
	return dara.Prettify(s)
}

func (s GetLoginTokenRequest) GoString() string {
	return s.String()
}

func (s *GetLoginTokenRequest) GetAuthenticationCode() *string {
	return s.AuthenticationCode
}

func (s *GetLoginTokenRequest) GetAvailableFeatures() map[string]*string {
	return s.AvailableFeatures
}

func (s *GetLoginTokenRequest) GetClientId() *string {
	return s.ClientId
}

func (s *GetLoginTokenRequest) GetClientName() *string {
	return s.ClientName
}

func (s *GetLoginTokenRequest) GetClientOS() *string {
	return s.ClientOS
}

func (s *GetLoginTokenRequest) GetClientType() *string {
	return s.ClientType
}

func (s *GetLoginTokenRequest) GetClientVersion() *string {
	return s.ClientVersion
}

func (s *GetLoginTokenRequest) GetCurrentStage() *string {
	return s.CurrentStage
}

func (s *GetLoginTokenRequest) GetDirectoryId() *string {
	return s.DirectoryId
}

func (s *GetLoginTokenRequest) GetEndUserId() *string {
	return s.EndUserId
}

func (s *GetLoginTokenRequest) GetKeepAlive() *bool {
	return s.KeepAlive
}

func (s *GetLoginTokenRequest) GetKeepAliveToken() *string {
	return s.KeepAliveToken
}

func (s *GetLoginTokenRequest) GetNewPassword() *string {
	return s.NewPassword
}

func (s *GetLoginTokenRequest) GetOfficeSiteId() *string {
	return s.OfficeSiteId
}

func (s *GetLoginTokenRequest) GetOldPassword() *string {
	return s.OldPassword
}

func (s *GetLoginTokenRequest) GetPassword() *string {
	return s.Password
}

func (s *GetLoginTokenRequest) GetRegionId() *string {
	return s.RegionId
}

func (s *GetLoginTokenRequest) GetSessionId() *string {
	return s.SessionId
}

func (s *GetLoginTokenRequest) GetTokenCode() *string {
	return s.TokenCode
}

func (s *GetLoginTokenRequest) GetUuid() *string {
	return s.Uuid
}

func (s *GetLoginTokenRequest) SetAuthenticationCode(v string) *GetLoginTokenRequest {
	s.AuthenticationCode = &v
	return s
}

func (s *GetLoginTokenRequest) SetAvailableFeatures(v map[string]*string) *GetLoginTokenRequest {
	s.AvailableFeatures = v
	return s
}

func (s *GetLoginTokenRequest) SetClientId(v string) *GetLoginTokenRequest {
	s.ClientId = &v
	return s
}

func (s *GetLoginTokenRequest) SetClientName(v string) *GetLoginTokenRequest {
	s.ClientName = &v
	return s
}

func (s *GetLoginTokenRequest) SetClientOS(v string) *GetLoginTokenRequest {
	s.ClientOS = &v
	return s
}

func (s *GetLoginTokenRequest) SetClientType(v string) *GetLoginTokenRequest {
	s.ClientType = &v
	return s
}

func (s *GetLoginTokenRequest) SetClientVersion(v string) *GetLoginTokenRequest {
	s.ClientVersion = &v
	return s
}

func (s *GetLoginTokenRequest) SetCurrentStage(v string) *GetLoginTokenRequest {
	s.CurrentStage = &v
	return s
}

func (s *GetLoginTokenRequest) SetDirectoryId(v string) *GetLoginTokenRequest {
	s.DirectoryId = &v
	return s
}

func (s *GetLoginTokenRequest) SetEndUserId(v string) *GetLoginTokenRequest {
	s.EndUserId = &v
	return s
}

func (s *GetLoginTokenRequest) SetKeepAlive(v bool) *GetLoginTokenRequest {
	s.KeepAlive = &v
	return s
}

func (s *GetLoginTokenRequest) SetKeepAliveToken(v string) *GetLoginTokenRequest {
	s.KeepAliveToken = &v
	return s
}

func (s *GetLoginTokenRequest) SetNewPassword(v string) *GetLoginTokenRequest {
	s.NewPassword = &v
	return s
}

func (s *GetLoginTokenRequest) SetOfficeSiteId(v string) *GetLoginTokenRequest {
	s.OfficeSiteId = &v
	return s
}

func (s *GetLoginTokenRequest) SetOldPassword(v string) *GetLoginTokenRequest {
	s.OldPassword = &v
	return s
}

func (s *GetLoginTokenRequest) SetPassword(v string) *GetLoginTokenRequest {
	s.Password = &v
	return s
}

func (s *GetLoginTokenRequest) SetRegionId(v string) *GetLoginTokenRequest {
	s.RegionId = &v
	return s
}

func (s *GetLoginTokenRequest) SetSessionId(v string) *GetLoginTokenRequest {
	s.SessionId = &v
	return s
}

func (s *GetLoginTokenRequest) SetTokenCode(v string) *GetLoginTokenRequest {
	s.TokenCode = &v
	return s
}

func (s *GetLoginTokenRequest) SetUuid(v string) *GetLoginTokenRequest {
	s.Uuid = &v
	return s
}

func (s *GetLoginTokenRequest) Validate() error {
	return dara.Validate(s)
}
