// This file is auto-generated, don't edit it. Thanks.
package client

import (
	"github.com/alibabacloud-go/tea/dara"
)

type iCreateUdfFileRequest interface {
	dara.Model
	String() string
	GoString() string
	SetClassName(v string) *CreateUdfFileRequest
	GetClassName() *string
	SetCmdDescription(v string) *CreateUdfFileRequest
	GetCmdDescription() *string
	SetCreateFolderIfNotExists(v bool) *CreateUdfFileRequest
	GetCreateFolderIfNotExists() *bool
	SetExample(v string) *CreateUdfFileRequest
	GetExample() *string
	SetFileFolderPath(v string) *CreateUdfFileRequest
	GetFileFolderPath() *string
	SetFileName(v string) *CreateUdfFileRequest
	GetFileName() *string
	SetFunctionType(v string) *CreateUdfFileRequest
	GetFunctionType() *string
	SetParameterDescription(v string) *CreateUdfFileRequest
	GetParameterDescription() *string
	SetProjectId(v int64) *CreateUdfFileRequest
	GetProjectId() *int64
	SetProjectIdentifier(v string) *CreateUdfFileRequest
	GetProjectIdentifier() *string
	SetResources(v string) *CreateUdfFileRequest
	GetResources() *string
	SetReturnValue(v string) *CreateUdfFileRequest
	GetReturnValue() *string
	SetUdfDescription(v string) *CreateUdfFileRequest
	GetUdfDescription() *string
}

type CreateUdfFileRequest struct {
	// This parameter is required.
	//
	// example:
	//
	// com.alibaba.DataWorks.api.udf.StringConcat
	ClassName *string `json:"ClassName,omitempty" xml:"ClassName,omitempty"`
	// example:
	//
	// StringConcat(String... substrs)
	CmdDescription *string `json:"CmdDescription,omitempty" xml:"CmdDescription,omitempty"`
	// example:
	//
	// false
	CreateFolderIfNotExists *bool `json:"CreateFolderIfNotExists,omitempty" xml:"CreateFolderIfNotExists,omitempty"`
	// example:
	//
	// StringConcat(\\"a\\", \\"b\\", \\"c\\")
	Example *string `json:"Example,omitempty" xml:"Example,omitempty"`
	// This parameter is required.
	//
	// example:
	//
	// Business_process/First_Business_Process/function/string_processing
	FileFolderPath *string `json:"FileFolderPath,omitempty" xml:"FileFolderPath,omitempty"`
	// This parameter is required.
	//
	// example:
	//
	// StringConcat
	FileName *string `json:"FileName,omitempty" xml:"FileName,omitempty"`
	// This parameter is required.
	//
	// example:
	//
	// STRING
	FunctionType *string `json:"FunctionType,omitempty" xml:"FunctionType,omitempty"`
	// example:
	//
	// List of strings to be connected
	ParameterDescription *string `json:"ParameterDescription,omitempty" xml:"ParameterDescription,omitempty"`
	// example:
	//
	// 10000
	ProjectId *int64 `json:"ProjectId,omitempty" xml:"ProjectId,omitempty"`
	// example:
	//
	// dw_project
	ProjectIdentifier *string `json:"ProjectIdentifier,omitempty" xml:"ProjectIdentifier,omitempty"`
	// This parameter is required.
	//
	// example:
	//
	// string-concat-1.0.0.jar,commons-lang-2.6.jar
	Resources *string `json:"Resources,omitempty" xml:"Resources,omitempty"`
	// example:
	//
	// New strings generated by concatenating all strings before and after the input order
	ReturnValue *string `json:"ReturnValue,omitempty" xml:"ReturnValue,omitempty"`
	// example:
	//
	// Concatenate several strings to generate a new string
	UdfDescription *string `json:"UdfDescription,omitempty" xml:"UdfDescription,omitempty"`
}

func (s CreateUdfFileRequest) String() string {
	return dara.Prettify(s)
}

func (s CreateUdfFileRequest) GoString() string {
	return s.String()
}

func (s *CreateUdfFileRequest) GetClassName() *string {
	return s.ClassName
}

func (s *CreateUdfFileRequest) GetCmdDescription() *string {
	return s.CmdDescription
}

func (s *CreateUdfFileRequest) GetCreateFolderIfNotExists() *bool {
	return s.CreateFolderIfNotExists
}

func (s *CreateUdfFileRequest) GetExample() *string {
	return s.Example
}

func (s *CreateUdfFileRequest) GetFileFolderPath() *string {
	return s.FileFolderPath
}

func (s *CreateUdfFileRequest) GetFileName() *string {
	return s.FileName
}

func (s *CreateUdfFileRequest) GetFunctionType() *string {
	return s.FunctionType
}

func (s *CreateUdfFileRequest) GetParameterDescription() *string {
	return s.ParameterDescription
}

func (s *CreateUdfFileRequest) GetProjectId() *int64 {
	return s.ProjectId
}

func (s *CreateUdfFileRequest) GetProjectIdentifier() *string {
	return s.ProjectIdentifier
}

func (s *CreateUdfFileRequest) GetResources() *string {
	return s.Resources
}

func (s *CreateUdfFileRequest) GetReturnValue() *string {
	return s.ReturnValue
}

func (s *CreateUdfFileRequest) GetUdfDescription() *string {
	return s.UdfDescription
}

func (s *CreateUdfFileRequest) SetClassName(v string) *CreateUdfFileRequest {
	s.ClassName = &v
	return s
}

func (s *CreateUdfFileRequest) SetCmdDescription(v string) *CreateUdfFileRequest {
	s.CmdDescription = &v
	return s
}

func (s *CreateUdfFileRequest) SetCreateFolderIfNotExists(v bool) *CreateUdfFileRequest {
	s.CreateFolderIfNotExists = &v
	return s
}

func (s *CreateUdfFileRequest) SetExample(v string) *CreateUdfFileRequest {
	s.Example = &v
	return s
}

func (s *CreateUdfFileRequest) SetFileFolderPath(v string) *CreateUdfFileRequest {
	s.FileFolderPath = &v
	return s
}

func (s *CreateUdfFileRequest) SetFileName(v string) *CreateUdfFileRequest {
	s.FileName = &v
	return s
}

func (s *CreateUdfFileRequest) SetFunctionType(v string) *CreateUdfFileRequest {
	s.FunctionType = &v
	return s
}

func (s *CreateUdfFileRequest) SetParameterDescription(v string) *CreateUdfFileRequest {
	s.ParameterDescription = &v
	return s
}

func (s *CreateUdfFileRequest) SetProjectId(v int64) *CreateUdfFileRequest {
	s.ProjectId = &v
	return s
}

func (s *CreateUdfFileRequest) SetProjectIdentifier(v string) *CreateUdfFileRequest {
	s.ProjectIdentifier = &v
	return s
}

func (s *CreateUdfFileRequest) SetResources(v string) *CreateUdfFileRequest {
	s.Resources = &v
	return s
}

func (s *CreateUdfFileRequest) SetReturnValue(v string) *CreateUdfFileRequest {
	s.ReturnValue = &v
	return s
}

func (s *CreateUdfFileRequest) SetUdfDescription(v string) *CreateUdfFileRequest {
	s.UdfDescription = &v
	return s
}

func (s *CreateUdfFileRequest) Validate() error {
	return dara.Validate(s)
}
