// This file is auto-generated, don't edit it. Thanks.
package client

import (
	"github.com/alibabacloud-go/tea/dara"
)

type iQueryColumnarLogSSEResponseBody interface {
	dara.Model
	String() string
	GoString() string
	SetAccessDeniedDetail(v *QueryColumnarLogSSEResponseBodyAccessDeniedDetail) *QueryColumnarLogSSEResponseBody
	GetAccessDeniedDetail() *QueryColumnarLogSSEResponseBodyAccessDeniedDetail
	SetAppliedOffset(v int64) *QueryColumnarLogSSEResponseBody
	GetAppliedOffset() *int64
	SetAppliedRowLimit(v int64) *QueryColumnarLogSSEResponseBody
	GetAppliedRowLimit() *int64
	SetCode(v string) *QueryColumnarLogSSEResponseBody
	GetCode() *string
	SetHasMore(v bool) *QueryColumnarLogSSEResponseBody
	GetHasMore() *bool
	SetMessage(v string) *QueryColumnarLogSSEResponseBody
	GetMessage() *string
	SetPartial(v bool) *QueryColumnarLogSSEResponseBody
	GetPartial() *bool
	SetQueryElapsedTimeMilliseconds(v int64) *QueryColumnarLogSSEResponseBody
	GetQueryElapsedTimeMilliseconds() *int64
	SetQueryId(v string) *QueryColumnarLogSSEResponseBody
	GetQueryId() *string
	SetRecords(v []map[string]*string) *QueryColumnarLogSSEResponseBody
	GetRecords() []map[string]*string
	SetRecordsSizeBytes(v int64) *QueryColumnarLogSSEResponseBody
	GetRecordsSizeBytes() *int64
	SetRequestId(v string) *QueryColumnarLogSSEResponseBody
	GetRequestId() *string
	SetRetryable(v bool) *QueryColumnarLogSSEResponseBody
	GetRetryable() *bool
	SetReturnedRowCount(v int64) *QueryColumnarLogSSEResponseBody
	GetReturnedRowCount() *int64
	SetSequence(v int64) *QueryColumnarLogSSEResponseBody
	GetSequence() *int64
	SetType(v string) *QueryColumnarLogSSEResponseBody
	GetType() *string
}

type QueryColumnarLogSSEResponseBody struct {
	// The details of the access denial.
	AccessDeniedDetail *QueryColumnarLogSSEResponseBodyAccessDeniedDetail `json:"AccessDeniedDetail,omitempty" xml:"AccessDeniedDetail,omitempty" type:"Struct"`
	// Returned only when Type is EOF. The top-level SQL LIMIT offset actually applied by the service. The value is 0 if the SQL statement does not specify an offset.
	//
	// example:
	//
	// 0
	AppliedOffset *int64 `json:"AppliedOffset,omitempty" xml:"AppliedOffset,omitempty"`
	// Returned only when Type is EOF. The maximum number of rows actually applied by the service after combining the top-level SQL LIMIT, MaxResultRows, and the current service policy. This value does not include the extra row used to detect HasMore.
	//
	// example:
	//
	// 1000
	AppliedRowLimit *int64 `json:"AppliedRowLimit,omitempty" xml:"AppliedRowLimit,omitempty"`
	// The stable error code. This field is returned only when Type is ERROR. Handle errors based on this field instead of relying on the Message text.
	//
	// example:
	//
	// InternalError
	Code *string `json:"Code,omitempty" xml:"Code,omitempty"`
	// Returned only when Type is EOF. Indicates whether the service or API row limit truncated the SQL submitted by the caller. A value of false when the SQL statement has a smaller LIMIT that was fully executed does not indicate that no more data exists in the underlying table.
	//
	// example:
	//
	// False
	HasMore *bool `json:"HasMore,omitempty" xml:"HasMore,omitempty"`
	// The error summary. This field is returned only when Type is ERROR.
	//
	// example:
	//
	// Query execution failed
	Message *string `json:"Message,omitempty" xml:"Message,omitempty"`
	// Indicates whether at least one RECORD event was sent before the ERROR occurred. A value of true indicates that the results already received by the caller are incomplete and must not be treated as complete query results.
	Partial *bool `json:"Partial,omitempty" xml:"Partial,omitempty"`
	// Returned only when Type is EOF. The elapsed time from the start of JDBC statement execution to the completion of reading the last result row or probe row. Unit: milliseconds.
	//
	// example:
	//
	// 125
	QueryElapsedTimeMilliseconds *int64 `json:"QueryElapsedTimeMilliseconds,omitempty" xml:"QueryElapsedTimeMilliseconds,omitempty"`
	// The unique identifier generated by the service for this JDBC query. All events in the same SSE stream share the same QueryId.
	//
	// example:
	//
	// 5d3d88ea-3df0-4c2d-a8bb-2ec423b86b56
	QueryId *string `json:"QueryId,omitempty" xml:"QueryId,omitempty"`
	// Returned only when Type is RECORD. A batch of query results carried by this event. Each row is a JSON key-value object that maps column names to text values. SQL NULL values are encoded as the string null.
	Records []map[string]*string `json:"Records,omitempty" xml:"Records,omitempty" type:"Repeated"`
	// Returned only when Type is EOF. The sum of UTF-8 bytes of the JSON objects for all returned rows. This value does not include arrays, SSE frames, or fixed response fields.
	//
	// example:
	//
	// 8192
	RecordsSizeBytes *int64 `json:"RecordsSizeBytes,omitempty" xml:"RecordsSizeBytes,omitempty"`
	// The request ID. The same ID is used across all stages of the request, including access, authentication, routing, query execution, and all SSE events, to facilitate end-to-end troubleshooting.
	//
	// example:
	//
	// C457B28E-9CAB-4B77-B5C6-5D71B7870B6E
	RequestId *string `json:"RequestId,omitempty" xml:"RequestId,omitempty"`
	// Indicates whether the current ERROR is suitable for retry. A value of true indicates that you can retry the request based on the suggestion returned with the error. A value of false indicates that you need to modify the request or contact the service team for troubleshooting.
	//
	// example:
	//
	// true
	Retryable *bool `json:"Retryable,omitempty" xml:"Retryable,omitempty"`
	// Returned only when Type is EOF. The total number of result rows actually returned in this SSE stream.
	//
	// example:
	//
	// 100
	ReturnedRowCount *int64 `json:"ReturnedRowCount,omitempty" xml:"ReturnedRowCount,omitempty"`
	// The sequence number of the RECORD event, starting from 1 and incrementing. This field indicates the event order and does not represent the result row offset.
	//
	// example:
	//
	// 1
	Sequence *int64 `json:"Sequence,omitempty" xml:"Sequence,omitempty"`
	// The SSE event type. RECORD indicates a batch of query results. EOF indicates that the query has completed. ERROR indicates that the query ended abnormally.
	//
	// example:
	//
	// RECORD
	Type *string `json:"Type,omitempty" xml:"Type,omitempty"`
}

func (s QueryColumnarLogSSEResponseBody) String() string {
	return dara.Prettify(s)
}

func (s QueryColumnarLogSSEResponseBody) GoString() string {
	return s.String()
}

func (s *QueryColumnarLogSSEResponseBody) GetAccessDeniedDetail() *QueryColumnarLogSSEResponseBodyAccessDeniedDetail {
	return s.AccessDeniedDetail
}

func (s *QueryColumnarLogSSEResponseBody) GetAppliedOffset() *int64 {
	return s.AppliedOffset
}

func (s *QueryColumnarLogSSEResponseBody) GetAppliedRowLimit() *int64 {
	return s.AppliedRowLimit
}

func (s *QueryColumnarLogSSEResponseBody) GetCode() *string {
	return s.Code
}

func (s *QueryColumnarLogSSEResponseBody) GetHasMore() *bool {
	return s.HasMore
}

func (s *QueryColumnarLogSSEResponseBody) GetMessage() *string {
	return s.Message
}

func (s *QueryColumnarLogSSEResponseBody) GetPartial() *bool {
	return s.Partial
}

func (s *QueryColumnarLogSSEResponseBody) GetQueryElapsedTimeMilliseconds() *int64 {
	return s.QueryElapsedTimeMilliseconds
}

func (s *QueryColumnarLogSSEResponseBody) GetQueryId() *string {
	return s.QueryId
}

func (s *QueryColumnarLogSSEResponseBody) GetRecords() []map[string]*string {
	return s.Records
}

func (s *QueryColumnarLogSSEResponseBody) GetRecordsSizeBytes() *int64 {
	return s.RecordsSizeBytes
}

func (s *QueryColumnarLogSSEResponseBody) GetRequestId() *string {
	return s.RequestId
}

func (s *QueryColumnarLogSSEResponseBody) GetRetryable() *bool {
	return s.Retryable
}

func (s *QueryColumnarLogSSEResponseBody) GetReturnedRowCount() *int64 {
	return s.ReturnedRowCount
}

func (s *QueryColumnarLogSSEResponseBody) GetSequence() *int64 {
	return s.Sequence
}

func (s *QueryColumnarLogSSEResponseBody) GetType() *string {
	return s.Type
}

func (s *QueryColumnarLogSSEResponseBody) SetAccessDeniedDetail(v *QueryColumnarLogSSEResponseBodyAccessDeniedDetail) *QueryColumnarLogSSEResponseBody {
	s.AccessDeniedDetail = v
	return s
}

func (s *QueryColumnarLogSSEResponseBody) SetAppliedOffset(v int64) *QueryColumnarLogSSEResponseBody {
	s.AppliedOffset = &v
	return s
}

func (s *QueryColumnarLogSSEResponseBody) SetAppliedRowLimit(v int64) *QueryColumnarLogSSEResponseBody {
	s.AppliedRowLimit = &v
	return s
}

func (s *QueryColumnarLogSSEResponseBody) SetCode(v string) *QueryColumnarLogSSEResponseBody {
	s.Code = &v
	return s
}

func (s *QueryColumnarLogSSEResponseBody) SetHasMore(v bool) *QueryColumnarLogSSEResponseBody {
	s.HasMore = &v
	return s
}

func (s *QueryColumnarLogSSEResponseBody) SetMessage(v string) *QueryColumnarLogSSEResponseBody {
	s.Message = &v
	return s
}

func (s *QueryColumnarLogSSEResponseBody) SetPartial(v bool) *QueryColumnarLogSSEResponseBody {
	s.Partial = &v
	return s
}

func (s *QueryColumnarLogSSEResponseBody) SetQueryElapsedTimeMilliseconds(v int64) *QueryColumnarLogSSEResponseBody {
	s.QueryElapsedTimeMilliseconds = &v
	return s
}

func (s *QueryColumnarLogSSEResponseBody) SetQueryId(v string) *QueryColumnarLogSSEResponseBody {
	s.QueryId = &v
	return s
}

func (s *QueryColumnarLogSSEResponseBody) SetRecords(v []map[string]*string) *QueryColumnarLogSSEResponseBody {
	s.Records = v
	return s
}

func (s *QueryColumnarLogSSEResponseBody) SetRecordsSizeBytes(v int64) *QueryColumnarLogSSEResponseBody {
	s.RecordsSizeBytes = &v
	return s
}

func (s *QueryColumnarLogSSEResponseBody) SetRequestId(v string) *QueryColumnarLogSSEResponseBody {
	s.RequestId = &v
	return s
}

func (s *QueryColumnarLogSSEResponseBody) SetRetryable(v bool) *QueryColumnarLogSSEResponseBody {
	s.Retryable = &v
	return s
}

func (s *QueryColumnarLogSSEResponseBody) SetReturnedRowCount(v int64) *QueryColumnarLogSSEResponseBody {
	s.ReturnedRowCount = &v
	return s
}

func (s *QueryColumnarLogSSEResponseBody) SetSequence(v int64) *QueryColumnarLogSSEResponseBody {
	s.Sequence = &v
	return s
}

func (s *QueryColumnarLogSSEResponseBody) SetType(v string) *QueryColumnarLogSSEResponseBody {
	s.Type = &v
	return s
}

func (s *QueryColumnarLogSSEResponseBody) Validate() error {
	if s.AccessDeniedDetail != nil {
		if err := s.AccessDeniedDetail.Validate(); err != nil {
			return err
		}
	}
	return nil
}

type QueryColumnarLogSSEResponseBodyAccessDeniedDetail struct {
	// As described above.
	//
	// example:
	//
	// xxx
	AuthAction *string `json:"AuthAction,omitempty" xml:"AuthAction,omitempty"`
	// The display name of the authentication principal.
	//
	// example:
	//
	// xxx
	AuthPrincipalDisplayName *string `json:"AuthPrincipalDisplayName,omitempty" xml:"AuthPrincipalDisplayName,omitempty"`
	// The owner ID of the authentication principal.
	//
	// example:
	//
	// 111
	AuthPrincipalOwnerId *string `json:"AuthPrincipalOwnerId,omitempty" xml:"AuthPrincipalOwnerId,omitempty"`
	// The identity type used for authentication in the request. Valid values:
	//
	// - SubUser: RAM user.
	//
	// - AssumedRoleUser: RAM role.
	//
	// - Federated: SSO federated identity.
	//
	// example:
	//
	// 222
	AuthPrincipalType *string `json:"AuthPrincipalType,omitempty" xml:"AuthPrincipalType,omitempty"`
	// The encoded diagnostic message.
	//
	// example:
	//
	// AQEAAAAAaKPfwjY0MzMyODRGLUZCQkQtNTA1RS04MUUxLTc5NTkzODk2MUIzMg==
	EncodedDiagnosticMessage *string `json:"EncodedDiagnosticMessage,omitempty" xml:"EncodedDiagnosticMessage,omitempty"`
	// NoPermissionType
	//
	// example:
	//
	// ImplicitDeny
	NoPermissionType *string `json:"NoPermissionType,omitempty" xml:"NoPermissionType,omitempty"`
	// The policy type.
	//
	// example:
	//
	// PRIORITY
	PolicyType *string `json:"PolicyType,omitempty" xml:"PolicyType,omitempty"`
}

func (s QueryColumnarLogSSEResponseBodyAccessDeniedDetail) String() string {
	return dara.Prettify(s)
}

func (s QueryColumnarLogSSEResponseBodyAccessDeniedDetail) GoString() string {
	return s.String()
}

func (s *QueryColumnarLogSSEResponseBodyAccessDeniedDetail) GetAuthAction() *string {
	return s.AuthAction
}

func (s *QueryColumnarLogSSEResponseBodyAccessDeniedDetail) GetAuthPrincipalDisplayName() *string {
	return s.AuthPrincipalDisplayName
}

func (s *QueryColumnarLogSSEResponseBodyAccessDeniedDetail) GetAuthPrincipalOwnerId() *string {
	return s.AuthPrincipalOwnerId
}

func (s *QueryColumnarLogSSEResponseBodyAccessDeniedDetail) GetAuthPrincipalType() *string {
	return s.AuthPrincipalType
}

func (s *QueryColumnarLogSSEResponseBodyAccessDeniedDetail) GetEncodedDiagnosticMessage() *string {
	return s.EncodedDiagnosticMessage
}

func (s *QueryColumnarLogSSEResponseBodyAccessDeniedDetail) GetNoPermissionType() *string {
	return s.NoPermissionType
}

func (s *QueryColumnarLogSSEResponseBodyAccessDeniedDetail) GetPolicyType() *string {
	return s.PolicyType
}

func (s *QueryColumnarLogSSEResponseBodyAccessDeniedDetail) SetAuthAction(v string) *QueryColumnarLogSSEResponseBodyAccessDeniedDetail {
	s.AuthAction = &v
	return s
}

func (s *QueryColumnarLogSSEResponseBodyAccessDeniedDetail) SetAuthPrincipalDisplayName(v string) *QueryColumnarLogSSEResponseBodyAccessDeniedDetail {
	s.AuthPrincipalDisplayName = &v
	return s
}

func (s *QueryColumnarLogSSEResponseBodyAccessDeniedDetail) SetAuthPrincipalOwnerId(v string) *QueryColumnarLogSSEResponseBodyAccessDeniedDetail {
	s.AuthPrincipalOwnerId = &v
	return s
}

func (s *QueryColumnarLogSSEResponseBodyAccessDeniedDetail) SetAuthPrincipalType(v string) *QueryColumnarLogSSEResponseBodyAccessDeniedDetail {
	s.AuthPrincipalType = &v
	return s
}

func (s *QueryColumnarLogSSEResponseBodyAccessDeniedDetail) SetEncodedDiagnosticMessage(v string) *QueryColumnarLogSSEResponseBodyAccessDeniedDetail {
	s.EncodedDiagnosticMessage = &v
	return s
}

func (s *QueryColumnarLogSSEResponseBodyAccessDeniedDetail) SetNoPermissionType(v string) *QueryColumnarLogSSEResponseBodyAccessDeniedDetail {
	s.NoPermissionType = &v
	return s
}

func (s *QueryColumnarLogSSEResponseBodyAccessDeniedDetail) SetPolicyType(v string) *QueryColumnarLogSSEResponseBodyAccessDeniedDetail {
	s.PolicyType = &v
	return s
}

func (s *QueryColumnarLogSSEResponseBodyAccessDeniedDetail) Validate() error {
	return dara.Validate(s)
}
