// This file is auto-generated, don't edit it. Thanks.
package client

import (
	"github.com/alibabacloud-go/tea/dara"
)

type iCreateTransitUploadPolicyRequest interface {
	dara.Model
	String() string
	GoString() string
	SetExpireMs(v int64) *CreateTransitUploadPolicyRequest
	GetExpireMs() *int64
	SetFileShowName(v string) *CreateTransitUploadPolicyRequest
	GetFileShowName() *string
	SetNetwork(v string) *CreateTransitUploadPolicyRequest
	GetNetwork() *string
	SetPathPrefix(v string) *CreateTransitUploadPolicyRequest
	GetPathPrefix() *string
}

type CreateTransitUploadPolicyRequest struct {
	// The validity period of the upload policy and the Transit record, in milliseconds. Valid values: 1000 to 604800000. The value is rounded down to the nearest whole second. If `ExpireMs` is omitted or a `null` placeholder is passed through the gateway\\"s canonical field, the default validity period is `604800000` milliseconds (7 days).
	//
	// example:
	//
	// 604800000
	ExpireMs *int64 `json:"ExpireMs,omitempty" xml:"ExpireMs,omitempty"`
	// The display name of the file. The value must be 1 to 512 characters in length. The object key is generated by the server and is not guaranteed to contain the original file name.
	//
	// This parameter is required.
	//
	// example:
	//
	// code-review.zip
	FileShowName *string `json:"FileShowName,omitempty" xml:"FileShowName,omitempty"`
	// The network type of the upload address. Valid values: `public` and `internal`. Default value: `public`.
	//
	// example:
	//
	// public
	Network *string `json:"Network,omitempty" xml:"Network,omitempty"`
	// The path prefix used for object key isolation. This prefix has no Artifact business directory semantics. Default value: `default`.
	//
	// example:
	//
	// skill-bundle
	PathPrefix *string `json:"PathPrefix,omitempty" xml:"PathPrefix,omitempty"`
}

func (s CreateTransitUploadPolicyRequest) String() string {
	return dara.Prettify(s)
}

func (s CreateTransitUploadPolicyRequest) GoString() string {
	return s.String()
}

func (s *CreateTransitUploadPolicyRequest) GetExpireMs() *int64 {
	return s.ExpireMs
}

func (s *CreateTransitUploadPolicyRequest) GetFileShowName() *string {
	return s.FileShowName
}

func (s *CreateTransitUploadPolicyRequest) GetNetwork() *string {
	return s.Network
}

func (s *CreateTransitUploadPolicyRequest) GetPathPrefix() *string {
	return s.PathPrefix
}

func (s *CreateTransitUploadPolicyRequest) SetExpireMs(v int64) *CreateTransitUploadPolicyRequest {
	s.ExpireMs = &v
	return s
}

func (s *CreateTransitUploadPolicyRequest) SetFileShowName(v string) *CreateTransitUploadPolicyRequest {
	s.FileShowName = &v
	return s
}

func (s *CreateTransitUploadPolicyRequest) SetNetwork(v string) *CreateTransitUploadPolicyRequest {
	s.Network = &v
	return s
}

func (s *CreateTransitUploadPolicyRequest) SetPathPrefix(v string) *CreateTransitUploadPolicyRequest {
	s.PathPrefix = &v
	return s
}

func (s *CreateTransitUploadPolicyRequest) Validate() error {
	return dara.Validate(s)
}
