// This file is auto-generated, don't edit it. Thanks.
package client

import (
	"github.com/alibabacloud-go/tea/dara"
)

type iCreatePipelineRequest interface {
	dara.Model
	String() string
	GoString() string
	SetDescription(v string) *CreatePipelineRequest
	GetDescription() *string
	SetExecutePolicy(v *CreatePipelineRequestExecutePolicy) *CreatePipelineRequest
	GetExecutePolicy() *CreatePipelineRequestExecutePolicy
	SetPipeline(v *CreatePipelineRequestPipeline) *CreatePipelineRequest
	GetPipeline() *CreatePipelineRequestPipeline
	SetPipelineName(v string) *CreatePipelineRequest
	GetPipelineName() *string
	SetSink(v *CreatePipelineRequestSink) *CreatePipelineRequest
	GetSink() *CreatePipelineRequestSink
	SetSource(v *CreatePipelineRequestSource) *CreatePipelineRequest
	GetSource() *CreatePipelineRequestSource
	SetClientToken(v string) *CreatePipelineRequest
	GetClientToken() *string
}

type CreatePipelineRequest struct {
	// The description of the pipeline. Maximum length: 256 characters.
	//
	// example:
	//
	// Collect trace data from SLS and perform data cleaning into a dataset
	Description *string `json:"description,omitempty" xml:"description,omitempty"`
	// The scheduling method.
	//
	// example:
	//
	// {"mode":"RunOnce","runOnce":{"fromTime":1735660800,"toTime":1735664400}}
	ExecutePolicy *CreatePipelineRequestExecutePolicy `json:"executePolicy,omitempty" xml:"executePolicy,omitempty" type:"Struct"`
	// The pipeline configuration, including node orchestration.
	//
	// example:
	//
	// {"nodes":[{"id":"select-fields","type":"project","parameters":{"question":"user_query"}}]}
	Pipeline *CreatePipelineRequestPipeline `json:"pipeline,omitempty" xml:"pipeline,omitempty" type:"Struct"`
	// The name of the pipeline. The name must be 3 to 63 characters in length and can contain only lowercase letters, digits, and hyphens (-).
	//
	// example:
	//
	// my-pipeline
	PipelineName *string `json:"pipelineName,omitempty" xml:"pipelineName,omitempty"`
	// The pipeline sink, which is the data write destination.
	Sink *CreatePipelineRequestSink `json:"sink,omitempty" xml:"sink,omitempty" type:"Struct"`
	// The data source for the pipeline.
	//
	// example:
	//
	// {"type":"logstore","logstore":{"project":"my-sls-project","logstore":"agent-logs"},"inputFields":[{"name":"question","type":"text"}]}
	Source *CreatePipelineRequestSource `json:"source,omitempty" xml:"source,omitempty" type:"Struct"`
	// The idempotency token. This is a unique string generated by the client to ensure the idempotency of the create operation.
	//
	// example:
	//
	// a1b2c3d4-1234-5678-90ab-cdef12345678
	ClientToken *string `json:"clientToken,omitempty" xml:"clientToken,omitempty"`
}

func (s CreatePipelineRequest) String() string {
	return dara.Prettify(s)
}

func (s CreatePipelineRequest) GoString() string {
	return s.String()
}

func (s *CreatePipelineRequest) GetDescription() *string {
	return s.Description
}

func (s *CreatePipelineRequest) GetExecutePolicy() *CreatePipelineRequestExecutePolicy {
	return s.ExecutePolicy
}

func (s *CreatePipelineRequest) GetPipeline() *CreatePipelineRequestPipeline {
	return s.Pipeline
}

func (s *CreatePipelineRequest) GetPipelineName() *string {
	return s.PipelineName
}

func (s *CreatePipelineRequest) GetSink() *CreatePipelineRequestSink {
	return s.Sink
}

func (s *CreatePipelineRequest) GetSource() *CreatePipelineRequestSource {
	return s.Source
}

func (s *CreatePipelineRequest) GetClientToken() *string {
	return s.ClientToken
}

func (s *CreatePipelineRequest) SetDescription(v string) *CreatePipelineRequest {
	s.Description = &v
	return s
}

func (s *CreatePipelineRequest) SetExecutePolicy(v *CreatePipelineRequestExecutePolicy) *CreatePipelineRequest {
	s.ExecutePolicy = v
	return s
}

func (s *CreatePipelineRequest) SetPipeline(v *CreatePipelineRequestPipeline) *CreatePipelineRequest {
	s.Pipeline = v
	return s
}

func (s *CreatePipelineRequest) SetPipelineName(v string) *CreatePipelineRequest {
	s.PipelineName = &v
	return s
}

func (s *CreatePipelineRequest) SetSink(v *CreatePipelineRequestSink) *CreatePipelineRequest {
	s.Sink = v
	return s
}

func (s *CreatePipelineRequest) SetSource(v *CreatePipelineRequestSource) *CreatePipelineRequest {
	s.Source = v
	return s
}

func (s *CreatePipelineRequest) SetClientToken(v string) *CreatePipelineRequest {
	s.ClientToken = &v
	return s
}

func (s *CreatePipelineRequest) Validate() error {
	if s.ExecutePolicy != nil {
		if err := s.ExecutePolicy.Validate(); err != nil {
			return err
		}
	}
	if s.Pipeline != nil {
		if err := s.Pipeline.Validate(); err != nil {
			return err
		}
	}
	if s.Sink != nil {
		if err := s.Sink.Validate(); err != nil {
			return err
		}
	}
	if s.Source != nil {
		if err := s.Source.Validate(); err != nil {
			return err
		}
	}
	return nil
}

type CreatePipelineRequestExecutePolicy struct {
	// The continuous execution configuration. This is used when the type is trace. The processing frequency is a fixed value managed by the server.
	//
	// example:
	//
	// {"fromTime":1735660800}
	Continuous *CreatePipelineRequestExecutePolicyContinuous `json:"continuous,omitempty" xml:"continuous,omitempty" type:"Struct"`
	// The scheduling mode. Valid values: RunOnce (single execution) and Scheduled (periodic scheduling).
	//
	// example:
	//
	// RunOnce
	Mode *string `json:"mode,omitempty" xml:"mode,omitempty"`
	// The single execution configuration. This parameter is required only when the mode is RunOnce.
	//
	// example:
	//
	// {"fromTime":1735660800,"toTime":1735664400}
	RunOnce *CreatePipelineRequestExecutePolicyRunOnce `json:"runOnce,omitempty" xml:"runOnce,omitempty" type:"Struct"`
	// The periodic scheduling configuration. This parameter is required only when the mode is Scheduled.
	//
	// example:
	//
	// {"interval":"1h","fromTime":1735660800}
	Scheduled *CreatePipelineRequestExecutePolicyScheduled `json:"scheduled,omitempty" xml:"scheduled,omitempty" type:"Struct"`
}

func (s CreatePipelineRequestExecutePolicy) String() string {
	return dara.Prettify(s)
}

func (s CreatePipelineRequestExecutePolicy) GoString() string {
	return s.String()
}

func (s *CreatePipelineRequestExecutePolicy) GetContinuous() *CreatePipelineRequestExecutePolicyContinuous {
	return s.Continuous
}

func (s *CreatePipelineRequestExecutePolicy) GetMode() *string {
	return s.Mode
}

func (s *CreatePipelineRequestExecutePolicy) GetRunOnce() *CreatePipelineRequestExecutePolicyRunOnce {
	return s.RunOnce
}

func (s *CreatePipelineRequestExecutePolicy) GetScheduled() *CreatePipelineRequestExecutePolicyScheduled {
	return s.Scheduled
}

func (s *CreatePipelineRequestExecutePolicy) SetContinuous(v *CreatePipelineRequestExecutePolicyContinuous) *CreatePipelineRequestExecutePolicy {
	s.Continuous = v
	return s
}

func (s *CreatePipelineRequestExecutePolicy) SetMode(v string) *CreatePipelineRequestExecutePolicy {
	s.Mode = &v
	return s
}

func (s *CreatePipelineRequestExecutePolicy) SetRunOnce(v *CreatePipelineRequestExecutePolicyRunOnce) *CreatePipelineRequestExecutePolicy {
	s.RunOnce = v
	return s
}

func (s *CreatePipelineRequestExecutePolicy) SetScheduled(v *CreatePipelineRequestExecutePolicyScheduled) *CreatePipelineRequestExecutePolicy {
	s.Scheduled = v
	return s
}

func (s *CreatePipelineRequestExecutePolicy) Validate() error {
	if s.Continuous != nil {
		if err := s.Continuous.Validate(); err != nil {
			return err
		}
	}
	if s.RunOnce != nil {
		if err := s.RunOnce.Validate(); err != nil {
			return err
		}
	}
	if s.Scheduled != nil {
		if err := s.Scheduled.Validate(); err != nil {
			return err
		}
	}
	return nil
}

type CreatePipelineRequestExecutePolicyContinuous struct {
	// The bootstrap start time in UNIX seconds. It has the same precision as runOnce or scheduled fromTime. Millisecond values greater than or equal to 1e12 are automatically converted. The cursor starts from this time aligned to the grid and catches up window by window. After catching up, it switches to minute intervals. By default, it starts from the current time and processes only incremental data.
	//
	// example:
	//
	// 1735660800
	FromTime *int64 `json:"fromTime,omitempty" xml:"fromTime,omitempty"`
}

func (s CreatePipelineRequestExecutePolicyContinuous) String() string {
	return dara.Prettify(s)
}

func (s CreatePipelineRequestExecutePolicyContinuous) GoString() string {
	return s.String()
}

func (s *CreatePipelineRequestExecutePolicyContinuous) GetFromTime() *int64 {
	return s.FromTime
}

func (s *CreatePipelineRequestExecutePolicyContinuous) SetFromTime(v int64) *CreatePipelineRequestExecutePolicyContinuous {
	s.FromTime = &v
	return s
}

func (s *CreatePipelineRequestExecutePolicyContinuous) Validate() error {
	return dara.Validate(s)
}

type CreatePipelineRequestExecutePolicyRunOnce struct {
	// The start time of the data processing window in UNIX seconds. The value must be less than the toTime value.
	//
	// example:
	//
	// 1735660800
	FromTime *int64 `json:"fromTime,omitempty" xml:"fromTime,omitempty"`
	// The end time of the data processing window in UNIX seconds. The value must be greater than the fromTime value.
	//
	// example:
	//
	// 1735747200
	ToTime *int64 `json:"toTime,omitempty" xml:"toTime,omitempty"`
}

func (s CreatePipelineRequestExecutePolicyRunOnce) String() string {
	return dara.Prettify(s)
}

func (s CreatePipelineRequestExecutePolicyRunOnce) GoString() string {
	return s.String()
}

func (s *CreatePipelineRequestExecutePolicyRunOnce) GetFromTime() *int64 {
	return s.FromTime
}

func (s *CreatePipelineRequestExecutePolicyRunOnce) GetToTime() *int64 {
	return s.ToTime
}

func (s *CreatePipelineRequestExecutePolicyRunOnce) SetFromTime(v int64) *CreatePipelineRequestExecutePolicyRunOnce {
	s.FromTime = &v
	return s
}

func (s *CreatePipelineRequestExecutePolicyRunOnce) SetToTime(v int64) *CreatePipelineRequestExecutePolicyRunOnce {
	s.ToTime = &v
	return s
}

func (s *CreatePipelineRequestExecutePolicyRunOnce) Validate() error {
	return dara.Validate(s)
}

type CreatePipelineRequestExecutePolicyScheduled struct {
	// The start time of the scheduling in UNIX milliseconds.
	//
	// example:
	//
	// 1735660800000
	FromTime *int64 `json:"fromTime,omitempty" xml:"fromTime,omitempty"`
	// The scheduling interval. Valid values: 1h, 6h, 12h, and 1d.
	//
	// example:
	//
	// 1h
	Interval *string `json:"interval,omitempty" xml:"interval,omitempty"`
}

func (s CreatePipelineRequestExecutePolicyScheduled) String() string {
	return dara.Prettify(s)
}

func (s CreatePipelineRequestExecutePolicyScheduled) GoString() string {
	return s.String()
}

func (s *CreatePipelineRequestExecutePolicyScheduled) GetFromTime() *int64 {
	return s.FromTime
}

func (s *CreatePipelineRequestExecutePolicyScheduled) GetInterval() *string {
	return s.Interval
}

func (s *CreatePipelineRequestExecutePolicyScheduled) SetFromTime(v int64) *CreatePipelineRequestExecutePolicyScheduled {
	s.FromTime = &v
	return s
}

func (s *CreatePipelineRequestExecutePolicyScheduled) SetInterval(v string) *CreatePipelineRequestExecutePolicyScheduled {
	s.Interval = &v
	return s
}

func (s *CreatePipelineRequestExecutePolicyScheduled) Validate() error {
	return dara.Validate(s)
}

type CreatePipelineRequestPipeline struct {
	// The list of nodes.
	//
	// example:
	//
	// [{"id":"select-fields","type":"project","parameters":{}}]
	Nodes []*CreatePipelineRequestPipelineNodes `json:"nodes,omitempty" xml:"nodes,omitempty" type:"Repeated"`
}

func (s CreatePipelineRequestPipeline) String() string {
	return dara.Prettify(s)
}

func (s CreatePipelineRequestPipeline) GoString() string {
	return s.String()
}

func (s *CreatePipelineRequestPipeline) GetNodes() []*CreatePipelineRequestPipelineNodes {
	return s.Nodes
}

func (s *CreatePipelineRequestPipeline) SetNodes(v []*CreatePipelineRequestPipelineNodes) *CreatePipelineRequestPipeline {
	s.Nodes = v
	return s
}

func (s *CreatePipelineRequestPipeline) Validate() error {
	if s.Nodes != nil {
		for _, item := range s.Nodes {
			if item != nil {
				if err := item.Validate(); err != nil {
					return err
				}
			}
		}
	}
	return nil
}

type CreatePipelineRequestPipelineNodes struct {
	// The ID of the node.
	//
	// example:
	//
	// node-1
	Id *string `json:"id,omitempty" xml:"id,omitempty"`
	// The parameters of the node. This is a key-value structure and varies based on the node type.
	Parameters map[string]interface{} `json:"parameters,omitempty" xml:"parameters,omitempty"`
	// The type of the node.
	//
	// example:
	//
	// transform
	Type *string `json:"type,omitempty" xml:"type,omitempty"`
}

func (s CreatePipelineRequestPipelineNodes) String() string {
	return dara.Prettify(s)
}

func (s CreatePipelineRequestPipelineNodes) GoString() string {
	return s.String()
}

func (s *CreatePipelineRequestPipelineNodes) GetId() *string {
	return s.Id
}

func (s *CreatePipelineRequestPipelineNodes) GetParameters() map[string]interface{} {
	return s.Parameters
}

func (s *CreatePipelineRequestPipelineNodes) GetType() *string {
	return s.Type
}

func (s *CreatePipelineRequestPipelineNodes) SetId(v string) *CreatePipelineRequestPipelineNodes {
	s.Id = &v
	return s
}

func (s *CreatePipelineRequestPipelineNodes) SetParameters(v map[string]interface{}) *CreatePipelineRequestPipelineNodes {
	s.Parameters = v
	return s
}

func (s *CreatePipelineRequestPipelineNodes) SetType(v string) *CreatePipelineRequestPipelineNodes {
	s.Type = &v
	return s
}

func (s *CreatePipelineRequestPipelineNodes) Validate() error {
	return dara.Validate(s)
}

type CreatePipelineRequestSink struct {
	// The conditional routing configuration. This is used only when sink.type is set to condition.
	Condition *CreatePipelineRequestSinkCondition `json:"condition,omitempty" xml:"condition,omitempty" type:"Struct"`
	// The destination dataset configuration for the dataset sink. This is used only when sink.type is set to dataset.
	Dataset *CreatePipelineRequestSinkDataset `json:"dataset,omitempty" xml:"dataset,omitempty" type:"Struct"`
	// The destination type. Currently, dataset is supported.
	//
	// example:
	//
	// Dataset
	Type *string `json:"type,omitempty" xml:"type,omitempty"`
}

func (s CreatePipelineRequestSink) String() string {
	return dara.Prettify(s)
}

func (s CreatePipelineRequestSink) GoString() string {
	return s.String()
}

func (s *CreatePipelineRequestSink) GetCondition() *CreatePipelineRequestSinkCondition {
	return s.Condition
}

func (s *CreatePipelineRequestSink) GetDataset() *CreatePipelineRequestSinkDataset {
	return s.Dataset
}

func (s *CreatePipelineRequestSink) GetType() *string {
	return s.Type
}

func (s *CreatePipelineRequestSink) SetCondition(v *CreatePipelineRequestSinkCondition) *CreatePipelineRequestSink {
	s.Condition = v
	return s
}

func (s *CreatePipelineRequestSink) SetDataset(v *CreatePipelineRequestSinkDataset) *CreatePipelineRequestSink {
	s.Dataset = v
	return s
}

func (s *CreatePipelineRequestSink) SetType(v string) *CreatePipelineRequestSink {
	s.Type = &v
	return s
}

func (s *CreatePipelineRequestSink) Validate() error {
	if s.Condition != nil {
		if err := s.Condition.Validate(); err != nil {
			return err
		}
	}
	if s.Dataset != nil {
		if err := s.Dataset.Validate(); err != nil {
			return err
		}
	}
	return nil
}

type CreatePipelineRequestSinkCondition struct {
	// The default write destination used when no conditional route is matched.
	DefaultSink *CreatePipelineRequestSinkConditionDefaultSink `json:"defaultSink,omitempty" xml:"defaultSink,omitempty" type:"Struct"`
	// The route matching mode. Currently, only all is supported.
	//
	// example:
	//
	// all
	MatchMode *string `json:"matchMode,omitempty" xml:"matchMode,omitempty"`
	// The list of conditional routes.
	Routes []*CreatePipelineRequestSinkConditionRoutes `json:"routes,omitempty" xml:"routes,omitempty" type:"Repeated"`
}

func (s CreatePipelineRequestSinkCondition) String() string {
	return dara.Prettify(s)
}

func (s CreatePipelineRequestSinkCondition) GoString() string {
	return s.String()
}

func (s *CreatePipelineRequestSinkCondition) GetDefaultSink() *CreatePipelineRequestSinkConditionDefaultSink {
	return s.DefaultSink
}

func (s *CreatePipelineRequestSinkCondition) GetMatchMode() *string {
	return s.MatchMode
}

func (s *CreatePipelineRequestSinkCondition) GetRoutes() []*CreatePipelineRequestSinkConditionRoutes {
	return s.Routes
}

func (s *CreatePipelineRequestSinkCondition) SetDefaultSink(v *CreatePipelineRequestSinkConditionDefaultSink) *CreatePipelineRequestSinkCondition {
	s.DefaultSink = v
	return s
}

func (s *CreatePipelineRequestSinkCondition) SetMatchMode(v string) *CreatePipelineRequestSinkCondition {
	s.MatchMode = &v
	return s
}

func (s *CreatePipelineRequestSinkCondition) SetRoutes(v []*CreatePipelineRequestSinkConditionRoutes) *CreatePipelineRequestSinkCondition {
	s.Routes = v
	return s
}

func (s *CreatePipelineRequestSinkCondition) Validate() error {
	if s.DefaultSink != nil {
		if err := s.DefaultSink.Validate(); err != nil {
			return err
		}
	}
	if s.Routes != nil {
		for _, item := range s.Routes {
			if item != nil {
				if err := item.Validate(); err != nil {
					return err
				}
			}
		}
	}
	return nil
}

type CreatePipelineRequestSinkConditionDefaultSink struct {
	// The default destination dataset.
	Dataset *CreatePipelineRequestSinkConditionDefaultSinkDataset `json:"dataset,omitempty" xml:"dataset,omitempty" type:"Struct"`
	// The default destination type. Currently, only dataset is supported.
	//
	// example:
	//
	// dataset
	Type *string `json:"type,omitempty" xml:"type,omitempty"`
}

func (s CreatePipelineRequestSinkConditionDefaultSink) String() string {
	return dara.Prettify(s)
}

func (s CreatePipelineRequestSinkConditionDefaultSink) GoString() string {
	return s.String()
}

func (s *CreatePipelineRequestSinkConditionDefaultSink) GetDataset() *CreatePipelineRequestSinkConditionDefaultSinkDataset {
	return s.Dataset
}

func (s *CreatePipelineRequestSinkConditionDefaultSink) GetType() *string {
	return s.Type
}

func (s *CreatePipelineRequestSinkConditionDefaultSink) SetDataset(v *CreatePipelineRequestSinkConditionDefaultSinkDataset) *CreatePipelineRequestSinkConditionDefaultSink {
	s.Dataset = v
	return s
}

func (s *CreatePipelineRequestSinkConditionDefaultSink) SetType(v string) *CreatePipelineRequestSinkConditionDefaultSink {
	s.Type = &v
	return s
}

func (s *CreatePipelineRequestSinkConditionDefaultSink) Validate() error {
	if s.Dataset != nil {
		if err := s.Dataset.Validate(); err != nil {
			return err
		}
	}
	return nil
}

type CreatePipelineRequestSinkConditionDefaultSinkDataset struct {
	// The name of the agent space to which the default destination dataset belongs.
	//
	// example:
	//
	// my-agent-space
	AgentSpace *string `json:"agentSpace,omitempty" xml:"agentSpace,omitempty"`
	// The name of the default destination dataset.
	//
	// example:
	//
	// other-result
	Dataset *string `json:"dataset,omitempty" xml:"dataset,omitempty"`
}

func (s CreatePipelineRequestSinkConditionDefaultSinkDataset) String() string {
	return dara.Prettify(s)
}

func (s CreatePipelineRequestSinkConditionDefaultSinkDataset) GoString() string {
	return s.String()
}

func (s *CreatePipelineRequestSinkConditionDefaultSinkDataset) GetAgentSpace() *string {
	return s.AgentSpace
}

func (s *CreatePipelineRequestSinkConditionDefaultSinkDataset) GetDataset() *string {
	return s.Dataset
}

func (s *CreatePipelineRequestSinkConditionDefaultSinkDataset) SetAgentSpace(v string) *CreatePipelineRequestSinkConditionDefaultSinkDataset {
	s.AgentSpace = &v
	return s
}

func (s *CreatePipelineRequestSinkConditionDefaultSinkDataset) SetDataset(v string) *CreatePipelineRequestSinkConditionDefaultSinkDataset {
	s.Dataset = &v
	return s
}

func (s *CreatePipelineRequestSinkConditionDefaultSinkDataset) Validate() error {
	return dara.Validate(s)
}

type CreatePipelineRequestSinkConditionRoutes struct {
	// The route expression in Search Processing Language (SPL). Only where, project, and extend are supported.
	//
	// example:
	//
	// 	- | where intent = \\"refund\\"
	Expression *string `json:"expression,omitempty" xml:"expression,omitempty"`
	// The route ID.
	//
	// example:
	//
	// refund
	Id *string `json:"id,omitempty" xml:"id,omitempty"`
	// The write destination for the route.
	Sink *CreatePipelineRequestSinkConditionRoutesSink `json:"sink,omitempty" xml:"sink,omitempty" type:"Struct"`
}

func (s CreatePipelineRequestSinkConditionRoutes) String() string {
	return dara.Prettify(s)
}

func (s CreatePipelineRequestSinkConditionRoutes) GoString() string {
	return s.String()
}

func (s *CreatePipelineRequestSinkConditionRoutes) GetExpression() *string {
	return s.Expression
}

func (s *CreatePipelineRequestSinkConditionRoutes) GetId() *string {
	return s.Id
}

func (s *CreatePipelineRequestSinkConditionRoutes) GetSink() *CreatePipelineRequestSinkConditionRoutesSink {
	return s.Sink
}

func (s *CreatePipelineRequestSinkConditionRoutes) SetExpression(v string) *CreatePipelineRequestSinkConditionRoutes {
	s.Expression = &v
	return s
}

func (s *CreatePipelineRequestSinkConditionRoutes) SetId(v string) *CreatePipelineRequestSinkConditionRoutes {
	s.Id = &v
	return s
}

func (s *CreatePipelineRequestSinkConditionRoutes) SetSink(v *CreatePipelineRequestSinkConditionRoutesSink) *CreatePipelineRequestSinkConditionRoutes {
	s.Sink = v
	return s
}

func (s *CreatePipelineRequestSinkConditionRoutes) Validate() error {
	if s.Sink != nil {
		if err := s.Sink.Validate(); err != nil {
			return err
		}
	}
	return nil
}

type CreatePipelineRequestSinkConditionRoutesSink struct {
	// The destination dataset for the route.
	Dataset *CreatePipelineRequestSinkConditionRoutesSinkDataset `json:"dataset,omitempty" xml:"dataset,omitempty" type:"Struct"`
	// The destination type for the route. Currently, only dataset is supported.
	//
	// example:
	//
	// dataset
	Type *string `json:"type,omitempty" xml:"type,omitempty"`
}

func (s CreatePipelineRequestSinkConditionRoutesSink) String() string {
	return dara.Prettify(s)
}

func (s CreatePipelineRequestSinkConditionRoutesSink) GoString() string {
	return s.String()
}

func (s *CreatePipelineRequestSinkConditionRoutesSink) GetDataset() *CreatePipelineRequestSinkConditionRoutesSinkDataset {
	return s.Dataset
}

func (s *CreatePipelineRequestSinkConditionRoutesSink) GetType() *string {
	return s.Type
}

func (s *CreatePipelineRequestSinkConditionRoutesSink) SetDataset(v *CreatePipelineRequestSinkConditionRoutesSinkDataset) *CreatePipelineRequestSinkConditionRoutesSink {
	s.Dataset = v
	return s
}

func (s *CreatePipelineRequestSinkConditionRoutesSink) SetType(v string) *CreatePipelineRequestSinkConditionRoutesSink {
	s.Type = &v
	return s
}

func (s *CreatePipelineRequestSinkConditionRoutesSink) Validate() error {
	if s.Dataset != nil {
		if err := s.Dataset.Validate(); err != nil {
			return err
		}
	}
	return nil
}

type CreatePipelineRequestSinkConditionRoutesSinkDataset struct {
	// The name of the agent space to which the destination dataset belongs.
	//
	// example:
	//
	// my-agent-space
	AgentSpace *string `json:"agentSpace,omitempty" xml:"agentSpace,omitempty"`
	// The name of the destination dataset.
	//
	// example:
	//
	// refund-result
	Dataset *string `json:"dataset,omitempty" xml:"dataset,omitempty"`
}

func (s CreatePipelineRequestSinkConditionRoutesSinkDataset) String() string {
	return dara.Prettify(s)
}

func (s CreatePipelineRequestSinkConditionRoutesSinkDataset) GoString() string {
	return s.String()
}

func (s *CreatePipelineRequestSinkConditionRoutesSinkDataset) GetAgentSpace() *string {
	return s.AgentSpace
}

func (s *CreatePipelineRequestSinkConditionRoutesSinkDataset) GetDataset() *string {
	return s.Dataset
}

func (s *CreatePipelineRequestSinkConditionRoutesSinkDataset) SetAgentSpace(v string) *CreatePipelineRequestSinkConditionRoutesSinkDataset {
	s.AgentSpace = &v
	return s
}

func (s *CreatePipelineRequestSinkConditionRoutesSinkDataset) SetDataset(v string) *CreatePipelineRequestSinkConditionRoutesSinkDataset {
	s.Dataset = &v
	return s
}

func (s *CreatePipelineRequestSinkConditionRoutesSinkDataset) Validate() error {
	return dara.Validate(s)
}

type CreatePipelineRequestSinkDataset struct {
	// The name of the agent space to which the destination dataset belongs.
	//
	// example:
	//
	// my-agent-space
	AgentSpace *string `json:"agentSpace,omitempty" xml:"agentSpace,omitempty"`
	// The name of the destination dataset.
	//
	// example:
	//
	// my-dataset
	Dataset *string `json:"dataset,omitempty" xml:"dataset,omitempty"`
}

func (s CreatePipelineRequestSinkDataset) String() string {
	return dara.Prettify(s)
}

func (s CreatePipelineRequestSinkDataset) GoString() string {
	return s.String()
}

func (s *CreatePipelineRequestSinkDataset) GetAgentSpace() *string {
	return s.AgentSpace
}

func (s *CreatePipelineRequestSinkDataset) GetDataset() *string {
	return s.Dataset
}

func (s *CreatePipelineRequestSinkDataset) SetAgentSpace(v string) *CreatePipelineRequestSinkDataset {
	s.AgentSpace = &v
	return s
}

func (s *CreatePipelineRequestSinkDataset) SetDataset(v string) *CreatePipelineRequestSinkDataset {
	s.Dataset = &v
	return s
}

func (s *CreatePipelineRequestSinkDataset) Validate() error {
	return dara.Validate(s)
}

type CreatePipelineRequestSource struct {
	// The dataset datasource config under the current agent space.
	//
	// example:
	//
	// {"dataset":"my-dataset","filter":"status = \\"pending\\""}
	Dataset *CreatePipelineRequestSourceDataset `json:"dataset,omitempty" xml:"dataset,omitempty" type:"Struct"`
	// The input fields and their data types. This applies to all data source types.
	//
	// example:
	//
	// [{"name":"question","type":"text"}]
	InputFields []*CreatePipelineRequestSourceInputFields `json:"inputFields,omitempty" xml:"inputFields,omitempty" type:"Repeated"`
	// The Simple Log Service Logstore datasource config.
	//
	// example:
	//
	// {"project":"my-sls-project","logstore":"agent-logs"}
	Logstore *CreatePipelineRequestSourceLogstore `json:"logstore,omitempty" xml:"logstore,omitempty" type:"Struct"`
	// The trajectory data configuration. This is optional and takes effect only when the type is set to trace. It retrieves ATIF standard trajectory data from the trajectory scrubbing service and extends it based on features.
	//
	// example:
	//
	// {"enrich":{"enabled":true,"columns":["input","output"]}}
	Trajectory *CreatePipelineRequestSourceTrajectory `json:"trajectory,omitempty" xml:"trajectory,omitempty" type:"Struct"`
	// The data source type. Currently, Simple Log Service is supported.
	//
	// example:
	//
	// SLS
	Type *string `json:"type,omitempty" xml:"type,omitempty"`
}

func (s CreatePipelineRequestSource) String() string {
	return dara.Prettify(s)
}

func (s CreatePipelineRequestSource) GoString() string {
	return s.String()
}

func (s *CreatePipelineRequestSource) GetDataset() *CreatePipelineRequestSourceDataset {
	return s.Dataset
}

func (s *CreatePipelineRequestSource) GetInputFields() []*CreatePipelineRequestSourceInputFields {
	return s.InputFields
}

func (s *CreatePipelineRequestSource) GetLogstore() *CreatePipelineRequestSourceLogstore {
	return s.Logstore
}

func (s *CreatePipelineRequestSource) GetTrajectory() *CreatePipelineRequestSourceTrajectory {
	return s.Trajectory
}

func (s *CreatePipelineRequestSource) GetType() *string {
	return s.Type
}

func (s *CreatePipelineRequestSource) SetDataset(v *CreatePipelineRequestSourceDataset) *CreatePipelineRequestSource {
	s.Dataset = v
	return s
}

func (s *CreatePipelineRequestSource) SetInputFields(v []*CreatePipelineRequestSourceInputFields) *CreatePipelineRequestSource {
	s.InputFields = v
	return s
}

func (s *CreatePipelineRequestSource) SetLogstore(v *CreatePipelineRequestSourceLogstore) *CreatePipelineRequestSource {
	s.Logstore = v
	return s
}

func (s *CreatePipelineRequestSource) SetTrajectory(v *CreatePipelineRequestSourceTrajectory) *CreatePipelineRequestSource {
	s.Trajectory = v
	return s
}

func (s *CreatePipelineRequestSource) SetType(v string) *CreatePipelineRequestSource {
	s.Type = &v
	return s
}

func (s *CreatePipelineRequestSource) Validate() error {
	if s.Dataset != nil {
		if err := s.Dataset.Validate(); err != nil {
			return err
		}
	}
	if s.InputFields != nil {
		for _, item := range s.InputFields {
			if item != nil {
				if err := item.Validate(); err != nil {
					return err
				}
			}
		}
	}
	if s.Logstore != nil {
		if err := s.Logstore.Validate(); err != nil {
			return err
		}
	}
	if s.Trajectory != nil {
		if err := s.Trajectory.Validate(); err != nil {
			return err
		}
	}
	return nil
}

type CreatePipelineRequestSourceDataset struct {
	// The name of the source dataset.
	//
	// example:
	//
	// my-dataset
	Dataset *string `json:"dataset,omitempty" xml:"dataset,omitempty"`
	// The data filter condition for the dataset.
	//
	// example:
	//
	// status = \\"pending\\"
	Filter *string `json:"filter,omitempty" xml:"filter,omitempty"`
}

func (s CreatePipelineRequestSourceDataset) String() string {
	return dara.Prettify(s)
}

func (s CreatePipelineRequestSourceDataset) GoString() string {
	return s.String()
}

func (s *CreatePipelineRequestSourceDataset) GetDataset() *string {
	return s.Dataset
}

func (s *CreatePipelineRequestSourceDataset) GetFilter() *string {
	return s.Filter
}

func (s *CreatePipelineRequestSourceDataset) SetDataset(v string) *CreatePipelineRequestSourceDataset {
	s.Dataset = &v
	return s
}

func (s *CreatePipelineRequestSourceDataset) SetFilter(v string) *CreatePipelineRequestSourceDataset {
	s.Filter = &v
	return s
}

func (s *CreatePipelineRequestSourceDataset) Validate() error {
	return dara.Validate(s)
}

type CreatePipelineRequestSourceInputFields struct {
	// The name of the field.
	//
	// example:
	//
	// question
	Name *string `json:"name,omitempty" xml:"name,omitempty"`
	// The data type of the field. Valid values: text, long, double, and json.
	//
	// example:
	//
	// text
	Type *string `json:"type,omitempty" xml:"type,omitempty"`
}

func (s CreatePipelineRequestSourceInputFields) String() string {
	return dara.Prettify(s)
}

func (s CreatePipelineRequestSourceInputFields) GoString() string {
	return s.String()
}

func (s *CreatePipelineRequestSourceInputFields) GetName() *string {
	return s.Name
}

func (s *CreatePipelineRequestSourceInputFields) GetType() *string {
	return s.Type
}

func (s *CreatePipelineRequestSourceInputFields) SetName(v string) *CreatePipelineRequestSourceInputFields {
	s.Name = &v
	return s
}

func (s *CreatePipelineRequestSourceInputFields) SetType(v string) *CreatePipelineRequestSourceInputFields {
	s.Type = &v
	return s
}

func (s *CreatePipelineRequestSourceInputFields) Validate() error {
	return dara.Validate(s)
}

type CreatePipelineRequestSourceLogstore struct {
	// The name of the Simple Log Service Logstore.
	//
	// example:
	//
	// my-sls-logstore
	Logstore *string `json:"logstore,omitempty" xml:"logstore,omitempty"`
	// The name of the Simple Log Service project.
	//
	// example:
	//
	// my-sls-project
	Project *string `json:"project,omitempty" xml:"project,omitempty"`
	// The data filtered query statement, which uses the Simple Log Service query and analysis syntax.
	//
	// example:
	//
	// 	- | SELECT *
	Query *string `json:"query,omitempty" xml:"query,omitempty"`
}

func (s CreatePipelineRequestSourceLogstore) String() string {
	return dara.Prettify(s)
}

func (s CreatePipelineRequestSourceLogstore) GoString() string {
	return s.String()
}

func (s *CreatePipelineRequestSourceLogstore) GetLogstore() *string {
	return s.Logstore
}

func (s *CreatePipelineRequestSourceLogstore) GetProject() *string {
	return s.Project
}

func (s *CreatePipelineRequestSourceLogstore) GetQuery() *string {
	return s.Query
}

func (s *CreatePipelineRequestSourceLogstore) SetLogstore(v string) *CreatePipelineRequestSourceLogstore {
	s.Logstore = &v
	return s
}

func (s *CreatePipelineRequestSourceLogstore) SetProject(v string) *CreatePipelineRequestSourceLogstore {
	s.Project = &v
	return s
}

func (s *CreatePipelineRequestSourceLogstore) SetQuery(v string) *CreatePipelineRequestSourceLogstore {
	s.Query = &v
	return s
}

func (s *CreatePipelineRequestSourceLogstore) Validate() error {
	return dara.Validate(s)
}

type CreatePipelineRequestSourceTrajectory struct {
	// The trajectory enrichment configuration. It mounts trajectory data into the scrubbing results based on the trace_id. When writing to a dataset, the data is stored in the fixed agent_trajectory column, where the column value is the trajectory JSON content.
	//
	// example:
	//
	// {"enabled":true,"columns":["input","output"]}
	Enrich *CreatePipelineRequestSourceTrajectoryEnrich `json:"enrich,omitempty" xml:"enrich,omitempty" type:"Struct"`
}

func (s CreatePipelineRequestSourceTrajectory) String() string {
	return dara.Prettify(s)
}

func (s CreatePipelineRequestSourceTrajectory) GoString() string {
	return s.String()
}

func (s *CreatePipelineRequestSourceTrajectory) GetEnrich() *CreatePipelineRequestSourceTrajectoryEnrich {
	return s.Enrich
}

func (s *CreatePipelineRequestSourceTrajectory) SetEnrich(v *CreatePipelineRequestSourceTrajectoryEnrich) *CreatePipelineRequestSourceTrajectory {
	s.Enrich = v
	return s
}

func (s *CreatePipelineRequestSourceTrajectory) Validate() error {
	if s.Enrich != nil {
		if err := s.Enrich.Validate(); err != nil {
			return err
		}
	}
	return nil
}

type CreatePipelineRequestSourceTrajectoryEnrich struct {
	// The list of enrichment columns. This parameter is retained for backward compatibility. The current implementation outputs only the fixed agent_trajectory column, and this parameter no longer affects the output.
	//
	// example:
	//
	// ["input","output","session_id"]
	Columns []*string `json:"columns,omitempty" xml:"columns,omitempty" type:"Repeated"`
	// Specifies whether to enable trajectory enrichment.
	//
	// example:
	//
	// false
	Enabled *bool `json:"enabled,omitempty" xml:"enabled,omitempty"`
}

func (s CreatePipelineRequestSourceTrajectoryEnrich) String() string {
	return dara.Prettify(s)
}

func (s CreatePipelineRequestSourceTrajectoryEnrich) GoString() string {
	return s.String()
}

func (s *CreatePipelineRequestSourceTrajectoryEnrich) GetColumns() []*string {
	return s.Columns
}

func (s *CreatePipelineRequestSourceTrajectoryEnrich) GetEnabled() *bool {
	return s.Enabled
}

func (s *CreatePipelineRequestSourceTrajectoryEnrich) SetColumns(v []*string) *CreatePipelineRequestSourceTrajectoryEnrich {
	s.Columns = v
	return s
}

func (s *CreatePipelineRequestSourceTrajectoryEnrich) SetEnabled(v bool) *CreatePipelineRequestSourceTrajectoryEnrich {
	s.Enabled = &v
	return s
}

func (s *CreatePipelineRequestSourceTrajectoryEnrich) Validate() error {
	return dara.Validate(s)
}
