// This file is auto-generated, don't edit it. Thanks.
package client

import (
	"github.com/alibabacloud-go/tea/dara"
)

type iStartReverseWriterRequest interface {
	dara.Model
	String() string
	GoString() string
	SetCheckPoint(v string) *StartReverseWriterRequest
	GetCheckPoint() *string
	SetDtsJobId(v string) *StartReverseWriterRequest
	GetDtsJobId() *string
	SetResourceGroupId(v string) *StartReverseWriterRequest
	GetResourceGroupId() *string
}

type StartReverseWriterRequest struct {
	// The checkpoint of the incremental write module. The value is a UNIX timestamp.
	//
	// > Default value: the checkpoint that is automatically saved by DTS when the original task is stopped.
	//
	// example:
	//
	// 1695613785
	CheckPoint *string `json:"CheckPoint,omitempty" xml:"CheckPoint,omitempty"`
	// The ID of the task generated by calling the **CreateReverseDtsJob*	- operation.
	//
	// This parameter is required.
	//
	// example:
	//
	// n99m9jx822k****
	DtsJobId *string `json:"DtsJobId,omitempty" xml:"DtsJobId,omitempty"`
	// The resource group ID. This is a global parameter and does not need to be passed in for this operation.
	//
	// example:
	//
	// 资源组ID，全局参数，当前API无需传入。
	ResourceGroupId *string `json:"ResourceGroupId,omitempty" xml:"ResourceGroupId,omitempty"`
}

func (s StartReverseWriterRequest) String() string {
	return dara.Prettify(s)
}

func (s StartReverseWriterRequest) GoString() string {
	return s.String()
}

func (s *StartReverseWriterRequest) GetCheckPoint() *string {
	return s.CheckPoint
}

func (s *StartReverseWriterRequest) GetDtsJobId() *string {
	return s.DtsJobId
}

func (s *StartReverseWriterRequest) GetResourceGroupId() *string {
	return s.ResourceGroupId
}

func (s *StartReverseWriterRequest) SetCheckPoint(v string) *StartReverseWriterRequest {
	s.CheckPoint = &v
	return s
}

func (s *StartReverseWriterRequest) SetDtsJobId(v string) *StartReverseWriterRequest {
	s.DtsJobId = &v
	return s
}

func (s *StartReverseWriterRequest) SetResourceGroupId(v string) *StartReverseWriterRequest {
	s.ResourceGroupId = &v
	return s
}

func (s *StartReverseWriterRequest) Validate() error {
	return dara.Validate(s)
}
